SET search_path = matrimony_shared, pg_temp;
SET ROLE nsm_owner;
-- 009: Pan-Telugu Geographic Expansion: Andhra Pradesh (26 reorganized districts,
-- 773 mandals and major municipal towns) + Pan-India / Diaspora onboarding facilities.

-- 1. Expand matrimonial_id check constraint to support AP (Andhra Pradesh) and IN (Rest of India/Diaspora)
ALTER TABLE profiles DROP CONSTRAINT IF EXISTS ck_profiles_matrimonial_id;
ALTER TABLE profiles ADD CONSTRAINT ck_profiles_matrimonial_id
  CHECK (matrimonial_id ~ '^NSM-(TG|AP|IN)-[A-Z]{4}-[0-9]{4}-[0-9]{4,}$');

-- 2. Insert 26 Andhra Pradesh districts and other-state
INSERT INTO districts (slug, code, name_en, name_te) VALUES
  ('srikakulam', 'SKLM', 'Srikakulam', 'శ్రీకాకుళం'),
  ('vizianagaram', 'VZNR', 'Vizianagaram', 'విజయనగరం'),
  ('parvathipuram-manyam', 'PMNM', 'Parvathipuram Manyam', 'పార్వతీపురం మన్యం'),
  ('alluri-sitharama-raju', 'ASRJ', 'Alluri Sitharama Raju', 'అల్లూరి సీతారామరాజు'),
  ('visakhapatnam', 'VSPM', 'Visakhapatnam', 'విశాఖపట్నం'),
  ('anakapalli', 'AKPL', 'Anakapalli', 'అనకాపల్లి'),
  ('kakinada', 'KKND', 'Kakinada', 'కాకినాడ'),
  ('konaseema', 'KNSM', 'Dr. B.R. Ambedkar Konaseema', 'డా. బి.ఆర్. అంబేద్కర్ కోనసీమ'),
  ('east-godavari', 'EGOD', 'East Godavari', 'తూర్పు గోదావరి'),
  ('west-godavari', 'WGOD', 'West Godavari', 'పశ్చిమ గోదావరి'),
  ('eluru', 'ELRU', 'Eluru', 'ఏలూరు'),
  ('krishna', 'KSHN', 'Krishna', 'కృష్ణా'),
  ('vijayawada-ntr', 'VNTR', 'NTR (Vijayawada)', 'ఎన్టీఆర్ (విజయవాడ)'),
  ('guntur', 'GNTR', 'Guntur', 'గుంటూరు'),
  ('palnadu', 'PLND', 'Palnadu', 'పల్నాడు'),
  ('bapatla', 'BPTL', 'Bapatla', 'బాపట్ల'),
  ('prakasam', 'PKSM', 'Prakasam', 'ప్రకాశం'),
  ('sri-potti-sriramulu-nellore', 'SPSN', 'Sri Potti Sriramulu Nellore', 'శ్రీ పొట్టి శ్రీరాములు నెల్లూరు'),
  ('kurnool', 'KRNL', 'Kurnool', 'కర్నూలు'),
  ('nandyal', 'NDYL', 'Nandyal', 'నంద్యాల'),
  ('anantapur', 'ANTP', 'Ananthapuramu', 'అనంతపురం'),
  ('sri-sathya-sai', 'SSSI', 'Sri Sathya Sai', 'శ్రీ సత్యసాయి'),
  ('kadapa-ysr', 'KYSR', 'YSR Kadapa', 'వైఎస్సార్ కడప'),
  ('annamayya', 'ANMY', 'Annamayya', 'అన్నమయ్య'),
  ('tirupati', 'TRPT', 'Tirupati', 'తిరుపతి'),
  ('chittoor', 'CHTR', 'Chittoor', 'చిత్తూరు'),
  ('other-state', 'OTHR', 'Other State / Diaspora', 'ఇతర రాష్ట్రాలు / విదేశాలు')
ON CONFLICT (slug) DO UPDATE SET code = EXCLUDED.code, name_en = EXCLUDED.name_en, name_te = EXCLUDED.name_te;

-- 3. Insert other-mandal and 773 Andhra Pradesh mandals
INSERT INTO mandals (district, slug, name_en, name_te) VALUES
  ('other-state', 'other-mandal', 'Other Mandal / Town / Diaspora', 'ఇతర మండలం / పట్టణం / విదేశాలు'),
  ('srikakulam', 'amadalavalasa', 'Amadalavalasa', 'ఆమదాలవలస'),
  ('srikakulam', 'burja', 'Burja', 'బూర్జ'),
  ('srikakulam', 'etcherla', 'Etcherla', 'ఎచ్చెర్ల'),
  ('srikakulam', 'ganguvarisigadam', 'Ganguvarisigadam', 'గంగువారిసిగడం'),
  ('srikakulam', 'gara', 'Gara', 'గార'),
  ('srikakulam', 'hiramandalam', 'Hiramandalam', 'హీరమండలం'),
  ('srikakulam', 'ichchapuram', 'Ichchapuram', 'ఇచ్ఛాపురం'),
  ('srikakulam', 'jalumuru', 'Jalumuru', 'జలుమూరు'),
  ('srikakulam', 'kanchili', 'Kanchili', 'కంచిలి'),
  ('srikakulam', 'kaviti', 'Kaviti', 'కవిటి'),
  ('srikakulam', 'kotabommali', 'Kotabommali', 'కోటబొమ్మాళి'),
  ('srikakulam', 'lakshminarsupeta', 'Lakshminarsupeta', 'లక్ష్మీనర్సుపేట'),
  ('srikakulam', 'laveru', 'Laveru', 'లావేరు'),
  ('srikakulam', 'mandasa', 'Mandasa', 'మందస'),
  ('srikakulam', 'meliaputti', 'Meliaputti', 'మేళియాపుట్టి'),
  ('srikakulam', 'nandigam', 'Nandigam', 'నందిగాం'),
  ('srikakulam', 'narasannapeta', 'Narasannapeta', 'నరసన్నపేట'),
  ('srikakulam', 'palasa', 'Palasa / Kasibugga', 'పలాస / కాశీబుగ్గ'),
  ('srikakulam', 'pathapatnam', 'Pathapatnam', 'పాతపట్నం'),
  ('srikakulam', 'polaki', 'Polaki', 'పోలాకి'),
  ('srikakulam', 'ponduru', 'Ponduru Khadi', 'పొందూరు'),
  ('srikakulam', 'ranastalam', 'Ranastalam', 'రణస్థలం'),
  ('srikakulam', 'santhabommali', 'Santhabommali', 'సంతబొమ్మాళి'),
  ('srikakulam', 'saravakota', 'Saravakota', 'సారవకోట'),
  ('srikakulam', 'sarubujjili', 'Sarubujjili', 'సారుబుజ్జిలి'),
  ('srikakulam', 'sompeta', 'Sompeta', 'సోంపేట'),
  ('srikakulam', 'srikakulam-rural', 'Srikakulam Rural', 'శ్రీకాకుళం రూరల్'),
  ('srikakulam', 'srikakulam-urban', 'Srikakulam Urban', 'శ్రీకాకుళం అర్బన్'),
  ('srikakulam', 'tekkali', 'Tekkali', 'టెక్కలి'),
  ('srikakulam', 'vajrapukothuru', 'Vajrapukothuru', 'వజ్రపుకొత్తూరు'),
  ('vizianagaram', 'badangi', 'Badangi', 'బాడాంగి'),
  ('vizianagaram', 'bhogapuram', 'Bhogapuram Airport Zone', 'భోగాపురం'),
  ('vizianagaram', 'bobbili', 'Bobbili Heritage Town', 'బొబ్బిలి'),
  ('vizianagaram', 'bondapalle', 'Bondapalle', 'బొండపల్లి'),
  ('vizianagaram', 'cheepurupalle', 'Cheepurupalle', 'చీపురుపల్లి'),
  ('vizianagaram', 'dattirajeru', 'Dattirajeru', 'దత్తిరాజేరు'),
  ('vizianagaram', 'denkada', 'Denkada', 'డెంకాడ'),
  ('vizianagaram', 'gajapathinagaram', 'Gajapathinagaram', 'గజపతినగరం'),
  ('vizianagaram', 'gantyada', 'Gantyada', 'గంట్యాడ'),
  ('vizianagaram', 'garividi', 'Garividi', 'గరివిడి'),
  ('vizianagaram', 'gurla', 'Gurla', 'గుర్ల'),
  ('vizianagaram', 'jami', 'Jami', 'జామి'),
  ('vizianagaram', 'kothavalasa', 'Kothavalasa', 'కొత్తవలస'),
  ('vizianagaram', 'lakkavarapukota', 'Lakkavarapukota', 'లక్కవరపుకోట'),
  ('vizianagaram', 'mentada', 'Mentada', 'మెంటాడ'),
  ('vizianagaram', 'merakamudidam', 'Merakamudidam', 'మెరకముడిదాం'),
  ('vizianagaram', 'nellimarla', 'Nellimarla', 'నెల్లిమర్ల'),
  ('vizianagaram', 'pusapatirega', 'Pusapatirega', 'పూసపాటిరేగ'),
  ('vizianagaram', 'rajam', 'Rajam', 'రాజాం'),
  ('vizianagaram', 'ramabhadrapuram', 'Ramabhadrapuram', 'రామభద్రపురం'),
  ('vizianagaram', 'regidi-amadalavalasa', 'Regidi Amadalavalasa', 'రేగిడి ఆమదాలవలస'),
  ('vizianagaram', 'sringavarapukota', 'S.Kota (Sringavarapukota)', 'శృంగవరపుకోట'),
  ('vizianagaram', 'santhakaviti', 'Santhakaviti', 'సంతకవిటి'),
  ('vizianagaram', 'srungavarapukota', 'Srungavarapukota', 'శృంగవరపుకోట (ఎస్.కోట)'),
  ('vizianagaram', 'therlam', 'Therlam', 'తెర్లాం'),
  ('vizianagaram', 'vangara', 'Vangara', 'వంగర'),
  ('vizianagaram', 'vepada', 'Vepada', 'వేపాడ'),
  ('vizianagaram', 'vizianagaram-rural', 'Vizianagaram Rural', 'విజయనగరం రూరల్'),
  ('vizianagaram', 'vizianagaram-urban', 'Vizianagaram Urban', 'విజయనగరం అర్బన్'),
  ('parvathipuram-manyam', 'balijipeta', 'Balijipeta', 'బలిజిపేట'),
  ('parvathipuram-manyam', 'bhamini', 'Bhamini', 'భామినీ'),
  ('parvathipuram-manyam', 'garugubilli', 'Garugubilli', 'గరుగుబిల్లి'),
  ('parvathipuram-manyam', 'gummalakshmipuram', 'Gummalakshmipuram', 'గుమ్మలక్ష్మీపురం'),
  ('parvathipuram-manyam', 'gummalaxmipuram', 'Gummalaxmipuram', 'గుమ్మలక్ష్మీపురం'),
  ('parvathipuram-manyam', 'jiyyammavalasa', 'Jiyyammavalasa', 'జియ్యమ్మవలస'),
  ('parvathipuram-manyam', 'komarada', 'Komarada', 'కొమరాడ'),
  ('parvathipuram-manyam', 'kurupam', 'Kurupam', 'కురుపాం'),
  ('parvathipuram-manyam', 'makkuva', 'Makkuva', 'మక్కువ'),
  ('parvathipuram-manyam', 'pachipenta', 'Pachipenta', 'పాచిపెంట'),
  ('parvathipuram-manyam', 'palakonda', 'Palakonda', 'పాలకొండ'),
  ('parvathipuram-manyam', 'parvathipuram', 'Parvathipuram Headquarters', 'పార్వతీపురం'),
  ('parvathipuram-manyam', 'salur', 'Salur', 'సాలూరు'),
  ('parvathipuram-manyam', 'seethampeta', 'Seethampeta', 'సీతంపేట'),
  ('parvathipuram-manyam', 'seethanagaram', 'Seethanagaram', 'సీతానగరం'),
  ('parvathipuram-manyam', 'veeraghattam', 'Veeraghattam', 'వీరఘట్టం'),
  ('alluri-sitharama-raju', 'addateegala', 'Addateegala', 'అడ్డతీగల'),
  ('alluri-sitharama-raju', 'ananthagiri', 'Ananthagiri Borra Caves', 'అనంతగిరి'),
  ('alluri-sitharama-raju', 'araku-valley', 'Araku Valley Coffee Hills', 'అరకు లోయ'),
  ('alluri-sitharama-raju', 'chintapalle', 'Chintapalle Lambasingi', 'చింతపల్లి (లంబసింగి)'),
  ('alluri-sitharama-raju', 'chintoor', 'Chintoor / Koonavaram', 'చింతూరు / కూనవరం'),
  ('alluri-sitharama-raju', 'chintur', 'Chintur', 'చింతూరు'),
  ('alluri-sitharama-raju', 'devipatnam', 'Devipatnam', 'దేవీపట్నం'),
  ('alluri-sitharama-raju', 'dumbriguda', 'Dumbriguda', 'డుంబ్రిగుడ'),
  ('alluri-sitharama-raju', 'etapaka', 'Etapaka', 'ఎటపాక'),
  ('alluri-sitharama-raju', 'g-madugula', 'G. Madugula', 'జి. మాడుగుల'),
  ('alluri-sitharama-raju', 'gangavaram-asr', 'Gangavaram', 'గంగవరం'),
  ('alluri-sitharama-raju', 'gudem-kotha-veedhi', 'Gudem Kotha Veedhi', 'గూడెం కొత్తవీధి'),
  ('alluri-sitharama-raju', 'gurthedu', 'Gurthedu', 'గూర్తేడు'),
  ('alluri-sitharama-raju', 'hukumpeta', 'Hukumpeta', 'హుకుంపేట'),
  ('alluri-sitharama-raju', 'koyyuru', 'Koyyuru', 'కొయ్యూరు'),
  ('alluri-sitharama-raju', 'kunavaram', 'Kunavaram', 'కూనవరం'),
  ('alluri-sitharama-raju', 'maredumilli', 'Maredumilli Eco Forest', 'మారేడుమిల్లి'),
  ('alluri-sitharama-raju', 'munchingiputtu', 'Munchingi Puttu', 'ముంచింగిపుట్టు'),
  ('alluri-sitharama-raju', 'paderu', 'Paderu Headquarters', 'పాడేరు'),
  ('alluri-sitharama-raju', 'pedabayalu', 'Pedabayalu', 'పెదబయలు'),
  ('alluri-sitharama-raju', 'rajavommangi', 'Rajavommangi', 'రాజవొమ్మంగి'),
  ('alluri-sitharama-raju', 'rampachodavaram', 'Rampachodavaram Godavari Basin', 'రంపచోడవరం'),
  ('alluri-sitharama-raju', 'vararamachandrapuram', 'Vararamachandrapuram', 'వరరామచంద్రపురం (వి.ఆర్.పురం)'),
  ('alluri-sitharama-raju', 'y-ramavaram', 'Y. Ramavaram', 'వై.రామవరం'),
  ('visakhapatnam', 'anandapuram', 'Anandapuram', 'ఆనందపురం'),
  ('visakhapatnam', 'bheemunipatnam', 'Bheemunipatnam (Bheemili Beach)', 'భీమునిపట్నం'),
  ('visakhapatnam', 'gajuwaka', 'Gajuwaka Industrial Hub', 'గాజువాక'),
  ('visakhapatnam', 'gopalapatnam', 'Gopalapatnam / Simhachalam', 'గోపాలపట్నం (సింహాచలం)'),
  ('visakhapatnam', 'madhurawada', 'Madhurawada / IT SEZ', 'మధురవాడ'),
  ('visakhapatnam', 'maharanipeta', 'Maharanipeta (Collectorate)', 'మహారాణిపేట'),
  ('visakhapatnam', 'mulagada', 'Mulagada', 'ములగాడ'),
  ('visakhapatnam', 'mvp-colony', 'MVP Colony / Beach Road', 'ఎం.వి.పి. కాలనీ'),
  ('visakhapatnam', 'padmanabham', 'Padmanabham', 'పద్మనాభం'),
  ('visakhapatnam', 'pedagantyada', 'Pedagantyada Steel Plant', 'పెదగంట్యాడ'),
  ('visakhapatnam', 'pendurthi', 'Pendurthi', 'పెందుర్తి'),
  ('visakhapatnam', 'seethammadhara', 'Seethammadhara', 'సీతమ్మధార'),
  ('visakhapatnam', 'visakhapatnam-rural', 'Visakhapatnam Rural', 'విశాఖపట్నం రూరల్'),
  ('anakapalli', 'anakapalle', 'Anakapalle Jaggery Market', 'అనకాపల్లి'),
  ('anakapalli', 'anakapalli', 'Anakapalli', 'అనకాపల్లి'),
  ('anakapalli', 'atchutapuram', 'Atchutapuram SEZ', 'అచ్యుతాపురం'),
  ('anakapalli', 'butchayyapeta', 'Butchayyapeta', 'బుచ్చయ్యపేట'),
  ('anakapalli', 'cheedikada', 'Cheedikada', 'చీడికాడ'),
  ('anakapalli', 'chodavaram', 'Chodavaram', 'చోడవరం'),
  ('anakapalli', 'devarapalle', 'Devarapalle', 'దేవరపల్లి'),
  ('anakapalli', 'devarapalli', 'Devarapalli', 'దేవరపల్లి'),
  ('anakapalli', 'golugonda', 'Golugonda', 'గొలుగొండ'),
  ('anakapalli', 'k-kotapadu', 'K. Kotapadu', 'కె. కోటపాడు'),
  ('anakapalli', 'kasimkota', 'Kasimkota', 'కాశీంకోట'),
  ('anakapalli', 'kotauratla', 'Kotauratla', 'కోటవురట్ల'),
  ('anakapalli', 'madugula', 'Madugula Halwa Heritage', 'మాడుగుల'),
  ('anakapalli', 'makavarapalem', 'Makavarapalem', 'మాకవరపాలెం'),
  ('anakapalli', 'munagapaka', 'Munagapaka', 'మునగపాక'),
  ('anakapalli', 'nakkapalle', 'Nakkapalle', 'నక్కపల్లి'),
  ('anakapalli', 'narsipatnam', 'Narsipatnam', 'నర్సీపట్నం'),
  ('anakapalli', 'nathavaram', 'Nathavaram', 'నాతవరం'),
  ('anakapalli', 'paravada', 'Paravada', 'పరవాడ'),
  ('anakapalli', 'parawada', 'Parawada Pharma City', 'పరవాడ'),
  ('anakapalli', 'payakaraopeta', 'Payakaraopeta', 'పాయకరావుపేట'),
  ('anakapalli', 'rambilli', 'Rambilli Coastal', 'రాంబిల్లి'),
  ('anakapalli', 'ravikamatham', 'Ravikamatham', 'రావికమతం'),
  ('anakapalli', 'rolugunta', 'Rolugunta', 'రోలుగుంట'),
  ('anakapalli', 's-rayavaram', 'S. Rayavaram', 'ఎస్. రాయవరం'),
  ('anakapalli', 'sabbavaram', 'Sabbavaram', 'సబ్బవరం'),
  ('anakapalli', 'sarvasiddhi-rayavaram', 'Sarvasiddhi Rayavaram', 'ఎస్.రాయవరం'),
  ('anakapalli', 'yelamanchili', 'Yelamanchili', 'యలమంచిలి'),
  ('kakinada', 'gandepalle', 'Gandepalle', 'గండేపల్లి'),
  ('kakinada', 'gollaprolu', 'Gollaprolu', 'గొల్లప్రోలు'),
  ('kakinada', 'jaggampeta', 'Jaggampeta', 'జగ్గంపేట'),
  ('kakinada', 'kajuluru', 'Kajuluru', 'కాజులూరు'),
  ('kakinada', 'kakinada-urban', 'Kakinada Port & Smart City', 'కాకినాడ అర్బన్'),
  ('kakinada', 'kakinada-rural', 'Kakinada Rural', 'కాకినాడ రూరల్'),
  ('kakinada', 'kakinada-urban-mandal', 'Kakinada Urban', 'కాకినాడ అర్బన్'),
  ('kakinada', 'karapa', 'Karapa', 'కరప'),
  ('kakinada', 'kirlampudi', 'Kirlampudi', 'కిర్లంపూడి'),
  ('kakinada', 'kotananduru', 'Kotananduru', 'కోటనందూరు'),
  ('kakinada', 'kothapalle', 'Kothapalle', 'కొత్తపల్లె'),
  ('kakinada', 'pedapudi', 'Pedapudi', 'పెదపూడి'),
  ('kakinada', 'peddapuram', 'Peddapuram', 'పెద్దాపురం'),
  ('kakinada', 'pithapuram', 'Pithapuram Sripada Kshetram', 'పిఠాపురం'),
  ('kakinada', 'prathipadu-kkn', 'Prathipadu', 'ప్రత్తిపాడు'),
  ('kakinada', 'rowthulapudi', 'Rowthulapudi', 'రౌతులపూడి'),
  ('kakinada', 'samalkota', 'Samalkota Pancharama Kshetram', 'సామర్లకోట'),
  ('kakinada', 'sankhavaram', 'Sankhavaram', 'శంఖవరం'),
  ('kakinada', 'thallarevu', 'Thallarevu Coringa Mangroves', 'తాళ్లరేవు'),
  ('kakinada', 'thondangi', 'Thondangi', 'తొండంగి'),
  ('kakinada', 'tuni', 'Tuni Betel Leaf Market', 'తుని'),
  ('kakinada', 'u-kothapalli', 'U. Kothapalli Uppada Beach', 'ఉప్పాడ కొత్తపల్లి'),
  ('kakinada', 'yeleswaram', 'Yeleswaram', 'ఏలేశ్వరం'),
  ('konaseema', 'ainavilli', 'Ainavilli Siddhi Vinayaka', 'ఐనవిల్లి'),
  ('konaseema', 'alamuru', 'Alamuru', 'ఆలమూరు'),
  ('konaseema', 'allavaram', 'Allavaram', 'అల్లవరం'),
  ('konaseema', 'amalapuram', 'Amalapuram Headquarters', 'అమలాపురం'),
  ('konaseema', 'ambajipeta', 'Ambajipeta Coconut Center', 'అంబాజీపేట'),
  ('konaseema', 'atreyapuram', 'Atreyapuram Pootharekulu Hub', 'ఆత్రేయపురం'),
  ('konaseema', 'i-polavaram', 'I. Polavaram', 'ఐ.పోలవరం'),
  ('konaseema', 'k-gangavaram', 'K. Gangavaram', 'కె.గంగవరం'),
  ('konaseema', 'kapileswarapuram', 'Kapileswarapuram Zamindari Heritage', 'కపిలేశ్వరపురం'),
  ('konaseema', 'katrenikona', 'Katrenikona', 'కత్రేనికోన'),
  ('konaseema', 'kothapeta', 'Kothapeta', 'కొత్తపేట'),
  ('konaseema', 'malikipuram', 'Malikipuram (Dindi Resorts)', 'మలికిపురం'),
  ('konaseema', 'mamidikuduru', 'Mamidikuduru', 'మామిడికుదురు'),
  ('konaseema', 'mandapeta', 'Mandapeta Rice Mill City', 'మండపేట'),
  ('konaseema', 'mummidivaram', 'Mummidivaram Balayogi Kshetram', 'ముమ్మిడివరం'),
  ('konaseema', 'p-gannavaram', 'P. Gannavaram Aqueduct', 'పి. గన్నవరం'),
  ('konaseema', 'ramachandrapuram', 'Ramachandrapuram Draksharamam', 'రామచంద్రపురం'),
  ('konaseema', 'ravulapalem', 'Ravulapalem Banana Market Hub', 'రావులపాలెం'),
  ('konaseema', 'rayavaram', 'Rayavaram', 'రాయవరం'),
  ('konaseema', 'razole', 'Razole Scenic Coconut Delta', 'రాజోలు'),
  ('konaseema', 'sakhinetipalle', 'Sakhinetipalle', 'సఖినేటిపల్లి'),
  ('konaseema', 'sakinetipalli', 'Sakinetipalli Antarvedi Sangamam', 'సఖినేటిపల్లి (అంతర్వేది)'),
  ('konaseema', 'uppalaguptam', 'Uppalaguptam', 'ఉప్పలగుప్తం'),
  ('east-godavari', 'anaparthi', 'Anaparthi', 'అనపర్తి'),
  ('east-godavari', 'biccavolu', 'Biccavolu', 'బిక్కవోలు'),
  ('east-godavari', 'bikkavolu', 'Bikkavolu Historic Chalukya Temples', 'బిక్కవోలు'),
  ('east-godavari', 'chagallu', 'Chagallu Sugars', 'చాగల్లు'),
  ('east-godavari', 'devarapalle-eg', 'Devarapalle', 'దేవరపల్లి'),
  ('east-godavari', 'gokavaram', 'Gokavaram', 'గోకవరం'),
  ('east-godavari', 'gopalapuram', 'Gopalapuram', 'గోపాలపురం'),
  ('east-godavari', 'kadiam', 'Kadiam Flora Nurseries', 'కడియం'),
  ('east-godavari', 'kapileswarapuram', 'Kapileswarapuram', 'కపిలేశ్వరపురం'),
  ('east-godavari', 'korukonda', 'Korukonda Lakshmi Narasimha Swamy', 'కోరుకొండ'),
  ('east-godavari', 'kovvur', 'Kovvur Goshpada Kshetram', 'కొవ్వూరు'),
  ('east-godavari', 'mandapeta', 'Mandapeta', 'మండపేట'),
  ('east-godavari', 'nallajerla', 'Nallajerla', 'నల్లజర్ల'),
  ('east-godavari', 'nidadavole', 'Nidadavole Junction', 'నిడదవోలు'),
  ('east-godavari', 'peravali', 'Peravali', 'పేరవలి'),
  ('east-godavari', 'rajahmundry-rural', 'Rajahmundry Rural', 'రాజమండ్రి రూరల్'),
  ('east-godavari', 'rajahmundry-urban', 'Rajahmundry Urban', 'రాజమండ్రి అర్బన్'),
  ('east-godavari', 'rajamahendravaram-rural', 'Rajamahendravaram Rural', 'రాజమండ్రి రూరల్'),
  ('east-godavari', 'rajamahendravaram-urban', 'Rajamahendravaram Urban (Rajahmundry)', 'రాజమండ్రి అర్బన్'),
  ('east-godavari', 'rajanagaram', 'Rajanagaram Education Hub', 'రాజానగరం'),
  ('east-godavari', 'rangampeta', 'Rangampeta', 'రంగంపేట'),
  ('east-godavari', 'rayavaram', 'Rayavaram', 'రాయవరం'),
  ('east-godavari', 'seethanagaram', 'Seethanagaram', 'సీతానగరం'),
  ('east-godavari', 'tallapudi', 'Tallapudi', 'తాళ్లపూడి'),
  ('east-godavari', 'undrajavaram', 'Undrajavaram', 'ఉండ్రాజవరం'),
  ('west-godavari', 'achanta', 'Achanta Rameswara Swamy', 'ఆచంట'),
  ('west-godavari', 'akividu', 'Akividu Aquaculture Hub', 'ఆకివీడు'),
  ('west-godavari', 'attili', 'Attili', 'అత్తిలి'),
  ('west-godavari', 'bhimavaram', 'Bhimavaram Somarama Kshetram', 'భీమవరం'),
  ('west-godavari', 'ganapavaram', 'Ganapavaram', 'గణపవరం'),
  ('west-godavari', 'iragavaram', 'Iragavaram', 'ఇరగవరం'),
  ('west-godavari', 'kalla', 'Kalla', 'కళ్ల'),
  ('west-godavari', 'mogalthur', 'Mogalthur Heritage Town', 'మొగల్తూరు'),
  ('west-godavari', 'narasapuram', 'Narasapuram Lace & Port Town', 'నర్సాపురం'),
  ('west-godavari', 'palacoderu', 'Palacoderu', 'పాలకోడేరు'),
  ('west-godavari', 'palakollu', 'Palakollu Ksheerarama Kshetram', 'పాలకొల్లు'),
  ('west-godavari', 'pentapadu', 'Pentapadu', 'పెంటపాడు'),
  ('west-godavari', 'penugonda', 'Penugonda Vasavi Kanyaka Parameswari', 'పెనుగొండ'),
  ('west-godavari', 'penumantra', 'Penumantra', 'పెనుమంత్ర'),
  ('west-godavari', 'poduru', 'Poduru', 'పోడూరు'),
  ('west-godavari', 'tadepalligudem', 'Tadepalligudem NIT & Trade Center', 'తాడేపల్లిగూడెం'),
  ('west-godavari', 'tanuku', 'Tanuku Andhra Sugars Industrial Town', 'తణుకు'),
  ('west-godavari', 'undi', 'Undi', 'ఉండి'),
  ('west-godavari', 'veeravasaram', 'Veeravasaram', 'వీరవాసరం'),
  ('west-godavari', 'yelamanchili-wg', 'Yelamanchili', 'యలమంచిలి'),
  ('eluru', 'agiripalli', 'Agiripalli Shobhanachala Swamy', 'ఆగిరిపల్లి'),
  ('eluru', 'bhimadole', 'Bhimadole', 'భీమడోలు'),
  ('eluru', 'buttayagudem', 'Buttayagudem', 'బుట్టాయగూడెం'),
  ('eluru', 'chatrai', 'Chatrai', 'చాట్రాయి'),
  ('eluru', 'chintalapudi', 'Chintalapudi', 'చింతలపూడి'),
  ('eluru', 'denduluru', 'Denduluru', 'దेंदులూరు'),
  ('eluru', 'dwarakatirumala', 'Dwaraka Tirumala (Chinna Tirupati)', 'ద్వారకా తిరుమల'),
  ('eluru', 'eluru-rural', 'Eluru Rural', 'ఏలూరు రూరల్'),
  ('eluru', 'eluru-urban', 'Eluru Urban Carpet City', 'ఏలూరు అర్బన్'),
  ('eluru', 'jangareddygudem', 'Jangareddygudem Commercial Agency', 'జంగారెడ్డిగూడెం'),
  ('eluru', 'jeelugumilli', 'Jeelugumilli', 'జీలుగుమిల్లి'),
  ('eluru', 'kaikaluru', 'Kaikaluru Kolleru Sanctuary', 'కైకలూరు'),
  ('eluru', 'kalidindi', 'Kalidindi', 'కలిదిండి'),
  ('eluru', 'kamavarapukota', 'Kamavarapukota Guntupalli Caves', 'కామవరపుకోట'),
  ('eluru', 'koyyalagudem', 'Koyyalagudem', 'కొయ్యలగూడెం'),
  ('eluru', 'kukunoor', 'Kukunoor Tribal Region', 'కుక్కునూరు'),
  ('eluru', 'lingapalem', 'Lingapalem', 'లింగపాలెం'),
  ('eluru', 'mandavalli', 'Mandavalli', 'మండవల్లి'),
  ('eluru', 'mudinepalle', 'Mudinepalle', 'ముదినేపల్లి'),
  ('eluru', 'musunuru', 'Musunuru', 'ముసునూరు'),
  ('eluru', 'nidamarru', 'Nidamarru', 'నిడమర్రు'),
  ('eluru', 'nuzvid', 'Nuzvid Banganapalli Mango Capital', 'నూజివీడు'),
  ('eluru', 'pedapadu', 'Pedapadu', 'పెదపాడు'),
  ('eluru', 'pedavegi', 'Pedavegi Vengi Capital Heritage', 'పెదవేగి'),
  ('eluru', 'polavaram', 'Polavaram National Project Site', 'పోలవరం'),
  ('eluru', 't-narasapuram', 'T. Narasapuram', 'టి. నరసాపురం'),
  ('eluru', 'unguturu', 'Unguturu', 'ఉంగుటూరు'),
  ('eluru', 'velairpadu', 'Velairpadu Godavari Basin', 'వేలేరుపాడు'),
  ('krishna', 'avanigadda', 'Avanigadda Diviseema Gateway', 'అవనిగడ్డ'),
  ('krishna', 'bantumilli', 'Bantumilli', 'బంటుమిల్లి'),
  ('krishna', 'bapulapadu', 'Bapulapadu', 'బాపులపాడు'),
  ('krishna', 'challapalli', 'Challapalli Raja Palace', 'చల్లపల్లి'),
  ('krishna', 'gannavaram', 'Gannavaram', 'గన్నవరం'),
  ('krishna', 'ghantasala', 'Ghantasala Buddhist Heritage', 'ఘంటసాల'),
  ('krishna', 'gudivada', 'Gudivada Commercial Junction', 'గుడివాడ'),
  ('krishna', 'gudlavalleru', 'Gudlavalleru Engineering Hub', 'గుడ్లవల్లేరు'),
  ('krishna', 'guduru-krishna', 'Guduru', 'గూడూరు'),
  ('krishna', 'kankipadu', 'Kankipadu', 'కంకిపాడు'),
  ('krishna', 'koduru-krishna', 'Koduru Beach', 'కోడూరు'),
  ('krishna', 'kruthivennu', 'Kruthivennu', 'కృతివెన్ను'),
  ('krishna', 'machilipatnam-urban', 'Machilipatnam Coastal Port City', 'మచిలీపట్నం అర్బన్'),
  ('krishna', 'machilipatnam-rural', 'Machilipatnam Rural', 'మచిలీపట్నం రూరల్'),
  ('krishna', 'mopidevi', 'Mopidevi', 'మోపిదేవి'),
  ('krishna', 'movva', 'Movva Kshetrayya Kshetram', 'మొవ్వ'),
  ('krishna', 'nagayalanka', 'Nagayalanka Light House Delta', 'నాగాయలంక'),
  ('krishna', 'nandivada', 'Nandivada', 'నందివాడ'),
  ('krishna', 'pamarru', 'Pamarru', 'పామర్రు'),
  ('krishna', 'pamidimukkala', 'Pamidimukkala', 'పామిడిముక్కల'),
  ('krishna', 'pedana', 'Pedana Kalamkari & Handlooms', 'పెడన'),
  ('krishna', 'pedaparupudi', 'Pedaparupudi', 'పెదపారుపూడి'),
  ('krishna', 'penamaluru', 'Penamaluru', 'పెనమలూరు'),
  ('krishna', 'thotlavalluru', 'Thotlavalluru', 'తోట్లవల్లూరు'),
  ('krishna', 'unguturu', 'Unguturu', 'ఉంగుటూరు'),
  ('krishna', 'vuyyuru', 'Vuyyuru Sugar Factory City', 'వుయ్యూరు'),
  ('vijayawada-ntr', 'a-konduru', 'A. Konduru', 'ఎ. కొండూరు'),
  ('vijayawada-ntr', 'chandarlapadu', 'Chandarlapadu', 'చందర్లపాడు'),
  ('vijayawada-ntr', 'g-konduru', 'G. Konduru', 'జి. కొండూరు'),
  ('vijayawada-ntr', 'gampalagudem', 'Gampalagudem', 'గంపలగూడెం'),
  ('vijayawada-ntr', 'ibrahimpatnam-ntr', 'Ibrahimpatnam (Dr. NTTPS Thermal)', 'ఇబ్రహీంపట్నం'),
  ('vijayawada-ntr', 'jaggaiahpet', 'Jaggaiahpet Cement Belt', 'జగ్గయ్యపేట'),
  ('vijayawada-ntr', 'jaggayyapeta', 'Jaggayyapeta', 'జగ్గయ్యపేట'),
  ('vijayawada-ntr', 'kanchikacherla', 'Kanchikacherla', 'కంచికచర్ల'),
  ('vijayawada-ntr', 'kondapalli', 'Kondapalli Fort & Wooden Toys', 'కొండపల్లి'),
  ('vijayawada-ntr', 'mylavaram', 'Mylavaram', 'మైలవరం'),
  ('vijayawada-ntr', 'nandigama', 'Nandigama Commercial Town', 'నందిగామ'),
  ('vijayawada-ntr', 'penuganchiprolu', 'Penuganchiprolu Sri Tirupatamma Temple', 'పెనుగంచిప్రోలు'),
  ('vijayawada-ntr', 'reddigudem', 'Reddigudem', 'రెడ్డిగూడెం'),
  ('vijayawada-ntr', 'tiruvuru', 'Tiruvuru Mango Belt', 'తిరువూరు'),
  ('vijayawada-ntr', 'vatsavai', 'Vatsavai', 'వత్సవాయి'),
  ('vijayawada-ntr', 'veerullapadu', 'Veerullapadu', 'వీరుళ్లపాడు'),
  ('vijayawada-ntr', 'vijayawada-central', 'Vijayawada Central / Besant Road', 'విజయవాడ సెంట్రల్'),
  ('vijayawada-ntr', 'vijayawada-east', 'Vijayawada East / Benz Circle', 'విజయవాడ ఈస్ట్'),
  ('vijayawada-ntr', 'vijayawada-north', 'Vijayawada North / Gunadala Mary Matha', 'విజయవాడ నార్త్'),
  ('vijayawada-ntr', 'vijayawada-rural', 'Vijayawada Rural', 'విజయవాడ రూరల్'),
  ('vijayawada-ntr', 'vijayawada-west', 'Vijayawada West / Kanaka Durga Temple', 'విజయవాడ వెస్ట్ (దుర్గ గుడి)'),
  ('vijayawada-ntr', 'vissannapeta', 'Vissannapeta', 'విస్సన్నపేట'),
  ('guntur', 'chebrolu', 'Chebrolu Historic Chaturmukha Brahma', 'చేబ్రోలు'),
  ('guntur', 'duggirala', 'Duggirala World Turmeric Market', 'దుగ్గిరాల'),
  ('guntur', 'guntur-east', 'Guntur East / Mirchi Yard', 'గుంటూరు ఈస్ట్ (మిర్చి యార్డ్)'),
  ('guntur', 'guntur-rural', 'Guntur Rural', 'గుంటూరు రూరల్'),
  ('guntur', 'guntur-urban', 'Guntur Urban / Brodipet / Arundelpet', 'గుంటూరు అర్బన్'),
  ('guntur', 'guntur-west', 'Guntur West', 'గుంటూరు పశ్చిమ'),
  ('guntur', 'kakumanu', 'Kakumanu', 'కాకుమాను'),
  ('guntur', 'kollipara', 'Kollipara', 'కొల్లిపర'),
  ('guntur', 'mangalagiri', 'Mangalagiri Panakala Narasimha / AIIMS', 'మంగళగిరి'),
  ('guntur', 'medikonduru', 'Medikonduru', 'మేడికొండూరు'),
  ('guntur', 'pedakakani', 'Pedakakani Malleswara Temple', 'పెదకాకాని'),
  ('guntur', 'pedanandipadu', 'Pedanandipadu', 'పెదనందిపాడు'),
  ('guntur', 'phirangipuram', 'Phirangipuram', 'ఫిరంగిపురం'),
  ('guntur', 'ponnur', 'Ponnur Sakshi Ganapathi', 'పొన్నూరు'),
  ('guntur', 'prathipadu-gnt', 'Prathipadu', 'ప్రత్తిపాడు'),
  ('guntur', 'tadepalli', 'Tadepalli Capital Zone', 'తాడేపల్లి'),
  ('guntur', 'tadikonda', 'Tadikonda', 'తాడికొండ'),
  ('guntur', 'tenali', 'Tenali (Andhra Paris Cultural Capital)', 'తెనాలి'),
  ('guntur', 'thullur', 'Thullur (Amaravati Capital Seed Access)', 'తుళ్లూరు (అమరావతి)'),
  ('guntur', 'vatticherukuru', 'Vatticherukuru', 'వట్టిచెరుకూరు'),
  ('palnadu', 'amaravathi-heritage', 'Amaravathi Amaralingeswara & Mahastupa', 'అమరావతి'),
  ('palnadu', 'atchampeta', 'Atchampeta', 'అచ్చంపేట'),
  ('palnadu', 'bellamkonda', 'Bellamkonda Fort', 'బెల్లంకొండ'),
  ('palnadu', 'bollapalle', 'Bollapalle', 'బొల్లాపల్లి'),
  ('palnadu', 'chilakaluripet', 'Chilakaluripet Cotton & NH16', 'చిలకలూరిపేట'),
  ('palnadu', 'dachepalle', 'Dachepalle', 'దాచేపల్లి'),
  ('palnadu', 'durgi', 'Durgi', 'దుర్గి'),
  ('palnadu', 'edlapadu', 'Edlapadu', 'యడ్లపాడు'),
  ('palnadu', 'gurazala', 'Gurazala Palnadu Division', 'గురజాల'),
  ('palnadu', 'ipuru', 'Ipuru', 'ఈపూరు'),
  ('palnadu', 'karempudi', 'Karempudi Palnadu Heroes Temple', 'కారెంపూడి'),
  ('palnadu', 'krosuru', 'Krosuru', 'క్రోసూరు'),
  ('palnadu', 'machavaram', 'Machavaram', 'మాచవరం'),
  ('palnadu', 'macherla', 'Macherla Chennakesava Swamy', 'మాచర్ల'),
  ('palnadu', 'muppalla', 'Muppalla', 'ముప్పాళ్ల'),
  ('palnadu', 'nadendla', 'Nadendla', 'నాదెండ్ల'),
  ('palnadu', 'narasaraopet', 'Narasaraopet Kotappakonda Gateway', 'నరసరావుపేట'),
  ('palnadu', 'nekarikallu', 'Nekarikallu', 'నెకరికల్లు'),
  ('palnadu', 'nuzendla', 'Nuzendla', 'నూజెండ్ల'),
  ('palnadu', 'pedakurapadu', 'Pedakurapadu', 'పెదకూరపాడు'),
  ('palnadu', 'piduguralla', 'Piduguralla White Limestone City', 'పిడుగురాళ్ల'),
  ('palnadu', 'rajupalem', 'Rajupalem', 'రాజుపాలెం'),
  ('palnadu', 'rentachintala', 'Rentachintala', 'రెంటచింతల'),
  ('palnadu', 'rompicherla-pln', 'Rompicherla', 'రొంపిచర్ల'),
  ('palnadu', 'sattenapalle', 'Sattenapalle', 'సత్తెనపల్లి'),
  ('palnadu', 'savalyapuram', 'Savalyapuram', 'శావల్యాపురం'),
  ('palnadu', 'veldurthi', 'Veldurthi', 'వెల్దుర్తి'),
  ('palnadu', 'vinukonda', 'Vinukonda Hill Fort Town', 'వినుకొండ'),
  ('bapatla', 'addanki', 'Addanki Historic Inscription Town', 'అద్దంకి'),
  ('bapatla', 'amruthalur', 'Amruthalur', 'అమృతలూరు'),
  ('bapatla', 'ballikurava', 'Ballikurava', 'బల్లికురవ'),
  ('bapatla', 'bapatla-town', 'Bapatla Suryalanka Beach & Agriculture College', 'బాపట్ల'),
  ('bapatla', 'bhattiprolu', 'Bhattiprolu Ancient Buddhist Stupa', 'భట్టిప్రోలు'),
  ('bapatla', 'cherukupalle', 'Cherukupalle', 'చెరుకుపల్లి'),
  ('bapatla', 'chinaganjam', 'Chinaganjam Salt Pans', 'చినగంజాం'),
  ('bapatla', 'chirala', 'Chirala Handloom & Textile City', 'చీరాల'),
  ('bapatla', 'inkollu', 'Inkollu', 'ఇంకొల్లు'),
  ('bapatla', 'j-panguluru', 'J. Panguluru', 'జనకవరం పంగులూరు'),
  ('bapatla', 'karamchedu', 'Karamchedu', 'కారంచేడు'),
  ('bapatla', 'karlapalem', 'Karlapalem', 'కార్లపాలెం'),
  ('bapatla', 'kollur', 'Kollur', 'కొల్లూరు'),
  ('bapatla', 'korisapadu', 'Korisapadu', 'కోరిశపాడు'),
  ('bapatla', 'martur', 'Martur Granite Hub', 'మార్టూరు'),
  ('bapatla', 'nagaram', 'Nagaram', 'నగరం'),
  ('bapatla', 'nizampatnam', 'Nizampatnam Fishing Port & Delta', 'నిజాంపట్నం'),
  ('bapatla', 'parchur', 'Parchur', 'పర్చూరు'),
  ('bapatla', 'pittalavanipalem', 'Pittalavanipalem', 'పిట్టలవానిపాలెం'),
  ('bapatla', 'repalle', 'Repalle Coastal Terminal', 'రేపల్లె'),
  ('bapatla', 'santhamaguluru', 'Santhamaguluru', 'సంతమాగులూరు'),
  ('bapatla', 'tsundur', 'Tsundur', 'చుండూరు'),
  ('bapatla', 'vemuru', 'Vemuru', 'వేమూరు'),
  ('bapatla', 'vetapalem', 'Vetapalem Saraswatha Nikethanam', 'వేటపాలెం'),
  ('bapatla', 'yeddanapudi', 'Yeddanapudi', 'యద్దనపూడి'),
  ('prakasam', 'addanki', 'Addanki', 'అద్దంకి'),
  ('prakasam', 'ardhaveedu', 'Ardhaveedu', 'అర్థవీడు'),
  ('prakasam', 'ballikurava', 'Ballikurava', 'బల్లికురవ'),
  ('prakasam', 'bestawaripeta', 'Bestawaripeta', 'బెస్తవారిపేట'),
  ('prakasam', 'besthavaripeta', 'Besthavaripeta', 'బెస్తవారిపేట'),
  ('prakasam', 'cs-puram', 'C.S. Puram', 'సి.ఎస్. పురం'),
  ('prakasam', 'chandra-sekhara-puram', 'Chandra Sekhara Puram', 'చంద్రశేఖరపురం'),
  ('prakasam', 'chimakurthi', 'Chimakurthi', 'చీమకుర్తి'),
  ('prakasam', 'chimakurthy', 'Chimakurthy Galaxy Black Granite', 'చీమకుర్తి'),
  ('prakasam', 'cumbum', 'Cumbum Historic Ancient Lake', 'కంబం'),
  ('prakasam', 'darsi', 'Darsi', 'దర్శి'),
  ('prakasam', 'donakonda', 'Donakonda Industrial Belt', 'దొనకొండ'),
  ('prakasam', 'dornala', 'Dornala', 'దోర్నాల'),
  ('prakasam', 'giddalur', 'Giddalur Nallamala Foothills', 'గిద్దలూరు'),
  ('prakasam', 'gudluru', 'Gudluru', 'గుడ్లూరు'),
  ('prakasam', 'hanumanthuni-padu', 'Hanumanthuni Padu', 'హనుమంతునిపాడు'),
  ('prakasam', 'j-panguluru', 'J. Panguluru', 'జనకవరం పంగులూరు'),
  ('prakasam', 'kandukur', 'Kandukur Commercial Division', 'కందుకూరు'),
  ('prakasam', 'kandukuru', 'Kandukuru', 'కందుకూరు'),
  ('prakasam', 'kanigiri', 'Kanigiri', 'కనిగిరి'),
  ('prakasam', 'komarolu', 'Komarolu', 'కొమరోలు'),
  ('prakasam', 'konakanamitla', 'Konakanamitla', 'కొనకనమిట్ల'),
  ('prakasam', 'kondapi', 'Kondapi', 'కొండపి'),
  ('prakasam', 'korisapadu', 'Korisapadu', 'కోరిశపాడు'),
  ('prakasam', 'kothapatnam', 'Kothapatnam Sea Coast', 'కొత్తపట్నం'),
  ('prakasam', 'kurichedu', 'Kurichedu', 'కురిచేడు'),
  ('prakasam', 'lingasamudram', 'Lingasamudram', 'లింగసముద్రం'),
  ('prakasam', 'maddipadu', 'Maddipadu', 'మద్దిపాడు'),
  ('prakasam', 'markapur', 'Markapur Slate Industry', 'మార్కాపురం'),
  ('prakasam', 'markapuram', 'Markapuram', 'మార్కాపురం'),
  ('prakasam', 'marripudi', 'Marripudi', 'మర్రిపూడి'),
  ('prakasam', 'mundlamuru', 'Mundlamuru', 'ముండ్లమూరు'),
  ('prakasam', 'naguluppalapadu', 'Naguluppalapadu', 'నాగులుప్పలపాడు'),
  ('prakasam', 'ongole-urban', 'Ongole Breed Heritage City', 'ఒంగోలు అర్బన్'),
  ('prakasam', 'ongole-rural', 'Ongole Rural', 'ఒంగోలు రూరల్'),
  ('prakasam', 'ongole-urban-mandal', 'Ongole Urban', 'ఒంగోలు అర్బన్'),
  ('prakasam', 'pamuru', 'Pamuru', 'పామూరు'),
  ('prakasam', 'pedaaraveedu', 'Peda Araveedu', 'పెద్దారవీడు'),
  ('prakasam', 'pedacherlo-palle', 'Pedacherlo Palle', 'పెదచెర్లోపల్లె'),
  ('prakasam', 'podili', 'Podili', 'పొదిలి'),
  ('prakasam', 'ponnaluru', 'Ponnaluru', 'పొన్నలూరు'),
  ('prakasam', 'pullalacheruvu', 'Pullalacheruvu', 'పుల్లలచెరువు'),
  ('prakasam', 'racherla', 'Racherla', 'రాచర్ల'),
  ('prakasam', 'santhamaguluru', 'Santhamaguluru', 'సంతమాగులూరు'),
  ('prakasam', 'santhanuthalapadu', 'Santhanuthalapadu', 'సంతనూతలపాడు'),
  ('prakasam', 'singarayakonda', 'Singarayakonda Varaha Lakshmi Narasimha', 'సింగరాయకొండ'),
  ('prakasam', 'tangutur', 'Tangutur', 'టంగుటూరు'),
  ('prakasam', 'tarlupadu', 'Tarlupadu', 'తర్లుపాడు'),
  ('prakasam', 'thallur', 'Thallur', 'తాళ్లూరు'),
  ('prakasam', 'tripuranthakam', 'Tripuranthakam Srisailam Eastern Gateway', 'త్రిపురాంతకం'),
  ('prakasam', 'ulavapadu', 'Ulavapadu Export Banganapalli', 'ఉలవపాడు'),
  ('prakasam', 'veligandla', 'Veligandla', 'వెలిగండ్ల'),
  ('prakasam', 'voletivaripalem', 'Voletivaripalem', 'వోలేటివారిపాలెం'),
  ('prakasam', 'yerragondapalem', 'Yerragondapalem', 'యర్రగొండపాలెం'),
  ('prakasam', 'zarugumilli', 'Zarugumilli', 'జరుగుమల్లి'),
  ('sri-potti-sriramulu-nellore', 'allur', 'Allur', 'అల్లూరు'),
  ('sri-potti-sriramulu-nellore', 'anantasagaram', 'Anantasagaram Somashila Project', 'అనంతసాగరం (సోమశిల)'),
  ('sri-potti-sriramulu-nellore', 'ananthasagaram', 'Ananthasagaram', 'అనంతసాగరం'),
  ('sri-potti-sriramulu-nellore', 'anumasamudrampeta', 'Anumasamudrampeta', 'అనుమసముద్రంపేట'),
  ('sri-potti-sriramulu-nellore', 'atmakur-nlr', 'Atmakur Somashila Gateway', 'ఆత్మకూరు'),
  ('sri-potti-sriramulu-nellore', 'bogole', 'Bogole / Bitragunta Railway Yard', 'బోగోలు'),
  ('sri-potti-sriramulu-nellore', 'bogolu', 'Bogolu', 'బోగోలు'),
  ('sri-potti-sriramulu-nellore', 'buchireddypalem', 'Buchireddypalem Jonnawada Kamakshi', 'బుచ్చిరెడ్డిపాలెం (జొన్నవాడ)'),
  ('sri-potti-sriramulu-nellore', 'chejerla', 'Chejerla', 'చేజర్ల'),
  ('sri-potti-sriramulu-nellore', 'chillakur', 'Chillakur', 'చిల్లకూరు'),
  ('sri-potti-sriramulu-nellore', 'dagadarthi', 'Dagadarthi Non-Metro Airport Site', 'దగదర్తి'),
  ('sri-potti-sriramulu-nellore', 'duttalur', 'Duttalur', 'దుత్తలూరు'),
  ('sri-potti-sriramulu-nellore', 'indukurpet', 'Indukurpet Coastal Delta', 'ఇందుకూరుపేట'),
  ('sri-potti-sriramulu-nellore', 'jaladanki', 'Jaladanki', 'జలదంకి'),
  ('sri-potti-sriramulu-nellore', 'kaligiri', 'Kaligiri', 'కలిగిరి'),
  ('sri-potti-sriramulu-nellore', 'kaluvoya', 'Kaluvoya', 'కలువోయ'),
  ('sri-potti-sriramulu-nellore', 'kavali', 'Kavali Education & Trade City', 'కావలి'),
  ('sri-potti-sriramulu-nellore', 'kodavalur', 'Kodavalur', 'కొడవలూరు'),
  ('sri-potti-sriramulu-nellore', 'kondapuram-nlr', 'Kondapuram', 'కొండాపురం'),
  ('sri-potti-sriramulu-nellore', 'kota', 'Kota', 'కోట'),
  ('sri-potti-sriramulu-nellore', 'kovur-nlr', 'Kovur Penna River Fertile Belt', 'కోవూరు'),
  ('sri-potti-sriramulu-nellore', 'manubolu', 'Manubolu', 'మనుబోలు'),
  ('sri-potti-sriramulu-nellore', 'marripadu', 'Marripadu', 'మర్రిపాడు'),
  ('sri-potti-sriramulu-nellore', 'muthukur', 'Muthukur Deep Sea Port', 'ముత్తుకూరు (కృష్ణపట్నం పోర్ట్)'),
  ('sri-potti-sriramulu-nellore', 'muttukuru', 'Muttukuru', 'ముత్తుకూరు'),
  ('sri-potti-sriramulu-nellore', 'nellore-rural', 'Nellore Rural', 'నెల్లూరు రూరల్'),
  ('sri-potti-sriramulu-nellore', 'nellore-urban', 'Nellore Smart City / Ranganatha Swamy', 'నెల్లూరు అర్బన్'),
  ('sri-potti-sriramulu-nellore', 'nellore-urban-mandal', 'Nellore Urban', 'నెల్లూరు అర్బన్'),
  ('sri-potti-sriramulu-nellore', 'podalakur', 'Podalakur', 'పొదలకూరు'),
  ('sri-potti-sriramulu-nellore', 'rapur', 'Rapur Penchalakona Kshetram', 'రాపూరు (పెంచలకోన)'),
  ('sri-potti-sriramulu-nellore', 'rapuru', 'Rapuru', 'రాపూరు'),
  ('sri-potti-sriramulu-nellore', 'saidapuramu', 'Saidapuramu', 'సైదాపురం'),
  ('sri-potti-sriramulu-nellore', 'sangam', 'Sangam Triveni Sangamam', 'సంగం'),
  ('sri-potti-sriramulu-nellore', 'sitaramapuram', 'Sitaramapuram', 'సీతారామపురం'),
  ('sri-potti-sriramulu-nellore', 'sitarampuramu', 'Sitarampuramu', 'సీతారాంపురం'),
  ('sri-potti-sriramulu-nellore', 'thotapalligudur', 'Thotapalligudur', 'తోటపల్లిగూడూరు'),
  ('sri-potti-sriramulu-nellore', 'udayagiri', 'Udayagiri Hill Fort Heritage', 'ఉదయగిరి'),
  ('sri-potti-sriramulu-nellore', 'varikuntapadu', 'Varikuntapadu', 'వరికుంటపాడు'),
  ('sri-potti-sriramulu-nellore', 'venkatachalam', 'Venkatachalam', 'వెంకటాచలం'),
  ('sri-potti-sriramulu-nellore', 'vidavalur', 'Vidavalur', 'విడవలూరు'),
  ('sri-potti-sriramulu-nellore', 'vinjamur', 'Vinjamur', 'వింజమూరు'),
  ('kurnool', 'adoni-urban', 'Adoni Cotton & Grain Trade Hub', 'ఆదోని'),
  ('kurnool', 'adoni-rural', 'Adoni Rural', 'ఆదోని'),
  ('kurnool', 'adoni-urban-mandal', 'Adoni Urban', 'ఆదోని అర్బన్'),
  ('kurnool', 'alur', 'Alur', 'ఆలూరు'),
  ('kurnool', 'aspari', 'Aspari', 'ఆస్పరి'),
  ('kurnool', 'c-belagal', 'C. Belagal', 'సి. బెళగల్'),
  ('kurnool', 'chippagiri', 'Chippagiri', 'చిప్పగిరి'),
  ('kurnool', 'devanakonda', 'Devanakonda', 'దేవనకొండ'),
  ('kurnool', 'dhone', 'Dhone / Dronachalam Mining Hub', 'డోన్'),
  ('kurnool', 'gonagandla', 'Gonagandla', 'గోనెగండ్ల'),
  ('kurnool', 'gonegandla', 'Gonegandla', 'గోనెగండ్ల'),
  ('kurnool', 'gudur-knl', 'Gudur', 'గూడూరు'),
  ('kurnool', 'halaharvi', 'Halaharvi', 'హాలహర్వి'),
  ('kurnool', 'holagunda', 'Holagunda', 'హొళగుంద'),
  ('kurnool', 'kallur-knl', 'Kallur Industrial Estate', 'కల్లూరు'),
  ('kurnool', 'kodumur', 'Kodumur', 'కోడుమూరు'),
  ('kurnool', 'kosigi', 'Kosigi', 'కోసిగి'),
  ('kurnool', 'kowthalam', 'Kowthalam', 'కౌతాళం'),
  ('kurnool', 'krishnagiri-knl', 'Krishnagiri', 'కృష్ణగిరి'),
  ('kurnool', 'kurnool-urban', 'Kurnool Historic Konda Reddy Buruju City', 'కర్నూలు అర్బన్'),
  ('kurnool', 'kurnool-rural', 'Kurnool Rural', 'కర్నూలు రూరల్'),
  ('kurnool', 'kurnool-urban-mandal', 'Kurnool Urban', 'కర్నూలు అర్బన్'),
  ('kurnool', 'maddikera', 'Maddikera East', 'మద్దికెర'),
  ('kurnool', 'mantralayam', 'Mantralayam Sri Raghavendra Swamy Mutt', 'మంత్రాలయం'),
  ('kurnool', 'nandavaram', 'Nandavaram Sri Chowdeshwari Devi', 'నందవరం'),
  ('kurnool', 'orvakal', 'Orvakal Rock Garden & Airport Corridor', 'ఓర్వకల్లు'),
  ('kurnool', 'pattikonda', 'Pattikonda', 'పత్తికొండ'),
  ('kurnool', 'peapully', 'Peapully Custard Apples', 'ప్యాపిలి'),
  ('kurnool', 'peddakadubur', 'Pedda Kadubur', 'పెద్దకడబూరు'),
  ('kurnool', 'tuggali', 'Tuggali Jonnagiri Gold & Diamond Fields', 'తుగ్గలి'),
  ('kurnool', 'veldurthi', 'Veldurthi', 'వెల్దుర్తి'),
  ('kurnool', 'yemmiganur', 'Yemmiganur Handloom Weavers City', 'ఎమ్మిగనూరు'),
  ('nandyal', 'allagadda', 'Allagadda World Sculpture Center', 'ఆళ్లగడ్డ'),
  ('nandyal', 'atmakur-ndl', 'Atmakur Nallamala Gateway', 'ఆత్మకూరు'),
  ('nandyal', 'banaganapalle', 'Banaganapalle Mangoes & Nawab Palace', 'బనగానపల్లె'),
  ('nandyal', 'bandiatmakur', 'Bandi Atmakur', 'బండి ఆత్మకూరు'),
  ('nandyal', 'bethamcherla', 'Bethamcherla Natural Flooring Slabs', 'బెతంచెర్ల'),
  ('nandyal', 'chagalamarri', 'Chagalamarri', 'చాగలమర్రి'),
  ('nandyal', 'dhone', 'Dhone', 'డోన్'),
  ('nandyal', 'dornipadu', 'Dornipadu', 'దొర్నిపాడు'),
  ('nandyal', 'gadivemula', 'Gadivemula', 'గడివేముల'),
  ('nandyal', 'gospadu', 'Gospadu', 'గోస్పాడు'),
  ('nandyal', 'jupadu-bungalow', 'Jupadu Bungalow', 'జూపాడు బంగళా'),
  ('nandyal', 'koilkuntla', 'Koilkuntla', 'కోవెలకుంట్ల'),
  ('nandyal', 'kolimigundla', 'Kolimigundla Belum Caves', 'కొలిమిగుండ్ల (బెలూం గుహలు)'),
  ('nandyal', 'kothapalle-ndl', 'Kothapalle', 'కొత్తపల్లె'),
  ('nandyal', 'mahanandi', 'Mahanandi Pushkarini Kshetram', 'మహానంది'),
  ('nandyal', 'midthur', 'Midthur', 'మిడ్తూరు'),
  ('nandyal', 'nandikotkur', 'Nandikotkur', 'నందికొట్కూరు'),
  ('nandyal', 'nandyal-urban', 'Nandyal Nava Nandi Kshetram', 'నంద్యాల అర్బన్'),
  ('nandyal', 'nandyal-rural', 'Nandyal Rural', 'నంద్యాల రూరల్'),
  ('nandyal', 'nandyal-urban-mandal', 'Nandyal Urban', 'నంద్యాల అర్బన్'),
  ('nandyal', 'owk', 'Owk Reservoir & Historic Palaces', 'ఔకు'),
  ('nandyal', 'pagidyala', 'Pagidyala', 'పగిడ్యాల'),
  ('nandyal', 'pamulapadu', 'Pamulapadu', 'పాములపాడు'),
  ('nandyal', 'panyam', 'Panyam Cement Belt', 'పాణ్యం'),
  ('nandyal', 'peapally', 'Peapally', 'ప్యాపిలి'),
  ('nandyal', 'rudravaram', 'Rudravaram', 'రుద్రవరం'),
  ('nandyal', 'sanjamala', 'Sanjamala', 'సంజామల'),
  ('nandyal', 'sirivella', 'Sirivella', 'శిరివెళ్ల'),
  ('nandyal', 'sirvella', 'Sirvella', 'శిరివెళ్ల'),
  ('nandyal', 'srisailam', 'Srisailam Mallikarjuna Bhramaramba Kshetram', 'శ్రీశైలం'),
  ('nandyal', 'uyyalawada', 'Uyyalawada First Freedom Fighter Land', 'ఉయ్యాలవాడ'),
  ('nandyal', 'velgodu', 'Velgodu Telugu Ganga Reservoir', 'వెలుగోడు'),
  ('anantapur', 'anantapur-rural', 'Anantapur Rural', 'అనంతపురం రూరల్'),
  ('anantapur', 'anantapur-urban', 'Anantapur Urban / Historic Tower', 'అనంతపురం అర్బన్'),
  ('anantapur', 'anantapuramu', 'Anantapuramu', 'అనంతపురం'),
  ('anantapur', 'atmakur-atp', 'Atmakur', 'ఆత్మకూరు'),
  ('anantapur', 'bk-samudram', 'B.K. Samudram', 'బికె సముద్రం'),
  ('anantapur', 'beluguppa', 'Beluguppa', 'బెలుగుప్ప'),
  ('anantapur', 'bommanahal', 'Bommanahal', 'బొమ్మనహాళ్'),
  ('anantapur', 'brahmasamudram', 'Brahmasamudram', 'బ్రహ్మసముద్రం'),
  ('anantapur', 'bukkaraya-samudram', 'Bukkaraya Samudram', 'బుక్కరాయసముద్రం'),
  ('anantapur', 'd-hirehal', 'D. Hirehal Iron Belt', 'డి. హిరేహాళ్'),
  ('anantapur', 'garladinne', 'Garladinne', 'గార్లదిన్నె'),
  ('anantapur', 'gooty', 'Gooty Historic Hill Citadel', 'గుత్తి'),
  ('anantapur', 'gummagatta', 'Gummagatta', 'గుమ్మఘట్ట'),
  ('anantapur', 'guntakal', 'Guntakal Railway Division Hub', 'గుంతకల్లు'),
  ('anantapur', 'kalyandurg', 'Kalyandurg Pomegranate Capital', 'కళ్యాణదుర్గం'),
  ('anantapur', 'kambadur', 'Kambadur Ancient Mallikarjuna Temple', 'కంబదూరు'),
  ('anantapur', 'kanekal', 'Kanekal', 'కణేకల్లు'),
  ('anantapur', 'kudair', 'Kudair', 'కూడేరు'),
  ('anantapur', 'kundurpi', 'Kundurpi Fort', 'కుందుర్పి'),
  ('anantapur', 'narpala', 'Narpala', 'నార్పల'),
  ('anantapur', 'pamidi', 'Pamidi Penna River Town', 'పామిడి'),
  ('anantapur', 'peddapappur', 'Peddapappur', 'పెద్దపప్పూరు'),
  ('anantapur', 'peddavadugur', 'Peddavadugur', 'పెద్దవడుగూరు'),
  ('anantapur', 'putlur', 'Putlur', 'పుట్లూరు'),
  ('anantapur', 'raptadu', 'Raptadu', 'రాప్తాడు'),
  ('anantapur', 'rayadurg', 'Rayadurg Hilltop Fort & Garment Industry', 'రాయదుర్గం'),
  ('anantapur', 'settur', 'Settur', 'శెట్టూరు'),
  ('anantapur', 'singanamala', 'Singanamala Large Fresh Lake', 'సింగనమల'),
  ('anantapur', 'tadipatri', 'Tadipatri Bugga Ramalingeswara Temple', 'తాడిపత్రి'),
  ('anantapur', 'uravakonda', 'Uravakonda Silk Weaving', 'ఉరవకొండ'),
  ('anantapur', 'vajrakarur', 'Vajrakarur Diamond Processing Fields', 'వజ్రకరూరు'),
  ('anantapur', 'vidapanakal', 'Vidapanakal', 'విడపనకల్లు'),
  ('anantapur', 'yadiki', 'Yadiki Underground Caves', 'యాడికి'),
  ('anantapur', 'yellanur', 'Yellanur', 'యల్లనూరు'),
  ('sri-sathya-sai', 'agali', 'Agali', 'అగళి'),
  ('sri-sathya-sai', 'amadagur', 'Amadagur', 'ఆమడగూరు'),
  ('sri-sathya-sai', 'amarapuram', 'Amarapuram', 'అమరాపురం'),
  ('sri-sathya-sai', 'bathalapalle', 'Bathalapalle', 'బత్తలపల్లి'),
  ('sri-sathya-sai', 'bukkapatnam', 'Bukkapatnam', 'బుక్కపట్నం'),
  ('sri-sathya-sai', 'ck-palle', 'C.K. Palle', 'సి.కె. పల్లి'),
  ('sri-sathya-sai', 'chennekothapalle', 'Chennekothapalle', 'చెన్నేకొత్తపల్లె'),
  ('sri-sathya-sai', 'chilamathur', 'Chilamathur Kodur Border Hub', 'చిలమత్తూరు'),
  ('sri-sathya-sai', 'dharmavaram', 'Dharmavaram World Heritage Silk Sarees', 'ధర్మవరం'),
  ('sri-sathya-sai', 'gandlapenta', 'Gandlapenta', 'గాండ్లపెంట'),
  ('sri-sathya-sai', 'gorantla', 'Gorantla Madhavaraya Temple', 'గొరంట్ల'),
  ('sri-sathya-sai', 'gudibanda', 'Gudibanda', 'గుడిబండ'),
  ('sri-sathya-sai', 'hindupur', 'Hindupur Industrial & Automobile Trade', 'హిందూపురం'),
  ('sri-sathya-sai', 'kadiri', 'Kadiri Khadri Lakshmi Narasimha Swamy', 'కదిరి'),
  ('sri-sathya-sai', 'kanaganapalle', 'Kanaganapalle', 'కనగానపల్లి'),
  ('sri-sathya-sai', 'kothacheruvu', 'Kothacheruvu', 'కొత్తచెరువు'),
  ('sri-sathya-sai', 'lepakshi', 'Lepakshi Monolithic Basavanna & Hanging Pillar', 'లేపాక్షి'),
  ('sri-sathya-sai', 'madakasira', 'Madakasira Hill Fort', 'మడకశిర'),
  ('sri-sathya-sai', 'mudigubba', 'Mudigubba', 'ముదిగుబ్బ'),
  ('sri-sathya-sai', 'np-kunta', 'N.P. Kunta 1000MW Solar Park', 'నంబులపూలకుంట'),
  ('sri-sathya-sai', 'nallacheruvu', 'Nallacheruvu', 'నల్లచెరువు'),
  ('sri-sathya-sai', 'nallamada', 'Nallamada', 'నల్లమాడ'),
  ('sri-sathya-sai', 'nambulapulakunta', 'Nambulapulakunta', 'నంబులపూలకుంట'),
  ('sri-sathya-sai', 'od-cheruvu', 'O.D. Cheruvu', 'ఓబులదేవరచెరువు'),
  ('sri-sathya-sai', 'obuladevaracheruvu', 'Obuladevaracheruvu', 'ఓబులదేవరచెరువు'),
  ('sri-sathya-sai', 'parigi-sss', 'Parigi', 'పరిగి'),
  ('sri-sathya-sai', 'penukonda', 'Penukonda Vijayanagara Second Capital & KIA Motors', 'పెనుకొండ'),
  ('sri-sathya-sai', 'puttaparthi', 'Puttaparthi Prasanthi Nilayam Spiritual Capital', 'పుట్టపర్తి'),
  ('sri-sathya-sai', 'ramagiri', 'Ramagiri Wind & Gold Belt', 'రామగిరి'),
  ('sri-sathya-sai', 'roddam', 'Roddam', 'రొద్దం'),
  ('sri-sathya-sai', 'rolla', 'Rolla', 'రొళ్ల'),
  ('sri-sathya-sai', 'somandepalle', 'Somandepalle', 'సోమందేపల్లి'),
  ('sri-sathya-sai', 'tadimarri', 'Tadimarri', 'తాడిమర్రి'),
  ('sri-sathya-sai', 'talupula', 'Talupula', 'తలుపుల'),
  ('sri-sathya-sai', 'tanakal', 'Tanakal', 'తనకల్లు'),
  ('kadapa-ysr', 'atlur', 'Atlur', 'అట్లూరు'),
  ('kadapa-ysr', 'b-kodur', 'B. Kodur', 'బి. కోడూరు'),
  ('kadapa-ysr', 'badvel', 'Badvel Commercial Division', 'బద్వేలు'),
  ('kadapa-ysr', 'brahmamgarimattam-mandal', 'Brahmamgarimattam', 'బ్రహ్మంగారిమఠం'),
  ('kadapa-ysr', 'chakrayapet', 'Chakrayapet', 'చక్రాయపేట'),
  ('kadapa-ysr', 'chapadu', 'Chapadu', 'చాపాడు'),
  ('kadapa-ysr', 'chennur-ysr', 'Chennur', 'చెన్నూరు'),
  ('kadapa-ysr', 'chinthakommadinne', 'Chinthakommadinne', 'చింతకొమ్మదిన్నె'),
  ('kadapa-ysr', 'duvvur', 'Duvvur', 'దువ్వూరు'),
  ('kadapa-ysr', 'gopavaram', 'Gopavaram Industrial Corridor', 'గోపవరం'),
  ('kadapa-ysr', 'jammalamadugu', 'Jammalamadugu (Gandikota Fort & Gorge)', 'జమ్మలమడుగు'),
  ('kadapa-ysr', 'kadapa-rural', 'Kadapa Rural', 'కడప రూరల్'),
  ('kadapa-ysr', 'kadapa-urban', 'Kadapa Urban / Ameen Peer Dargah / Devuni Kadapa', 'కడప అర్బన్'),
  ('kadapa-ysr', 'kalasapadu', 'Kalasapadu', 'కలసపాడు'),
  ('kadapa-ysr', 'kamalapuram', 'Kamalapuram Papaghni River', 'కమలాపురం'),
  ('kadapa-ysr', 'kasi-nayana', 'Kasi Nayana Avadhuta Kshetram', 'కాశీనాయన'),
  ('kadapa-ysr', 'khajipet', 'Khajipet', 'ఖాజీపేట'),
  ('kadapa-ysr', 'kondapuram-ysr', 'Kondapuram', 'కొండాపురం'),
  ('kadapa-ysr', 'lingala-ysr', 'Lingala', 'లింగాల'),
  ('kadapa-ysr', 'muddanur', 'Muddanur RTPP Thermal Power Station', 'ముద్దనూరు'),
  ('kadapa-ysr', 'mydukur', 'Mydukur Four-Roads Commercial Junction', 'మైదుకూరు'),
  ('kadapa-ysr', 'mylavaram-ysr', 'Mylavaram Reservoir Dam', 'మైలవరం'),
  ('kadapa-ysr', 'nandalur', 'Nandalur', 'నందలూరు'),
  ('kadapa-ysr', 'peddamudium', 'Peddamudium', 'పెద్దముడియం'),
  ('kadapa-ysr', 'pendlimarri', 'Pendlimarri', 'పెండ్లిమర్రి'),
  ('kadapa-ysr', 'porumamilla', 'Porumamilla 14th Century Historic Tank', 'పోరుమామిళ్ల'),
  ('kadapa-ysr', 'proddatur-gold', 'Proddatur (Second Bombay / Gold Hub)', 'ప్రొద్దుటూరు'),
  ('kadapa-ysr', 'pulivendla', 'Pulivendla', 'పులివెందుల'),
  ('kadapa-ysr', 'pulivendula', 'Pulivendula Banana & Horticulture Center', 'పులివెందుల'),
  ('kadapa-ysr', 'rajampet', 'Rajampet', 'రాజంపేట'),
  ('kadapa-ysr', 'rajupalem', 'Rajupalem', 'రాజుపాలెం'),
  ('kadapa-ysr', 's-mydukur', 'S.Mydukur', 'మైదుకూరు'),
  ('kadapa-ysr', 'siddhavatam', 'Siddhavatam Penna River Fort', 'సిద్ధవటం'),
  ('kadapa-ysr', 'sidhout', 'Sidhout', 'సిద్దవటం'),
  ('kadapa-ysr', 'simhadripuram', 'Simhadripuram', 'సింహాద్రిపురం'),
  ('kadapa-ysr', 'sri-avadhutha-kasinayana', 'Sri Avadhutha Kasinayana', 'శ్రీ అవధూత కాశీనాయన'),
  ('kadapa-ysr', 'brahmamgarimattam', 'Sri Potuluri Veerabrahmendra Swamy Mutt', 'బ్రహ్మంగారిమఠం'),
  ('kadapa-ysr', 't-sundupalle', 'T. Sundupalle', 'టి. సుండుపల్లె'),
  ('kadapa-ysr', 'thondur', 'Thondur', 'తొండూరు'),
  ('kadapa-ysr', 'vallur', 'Vallur Pushpagiri Peetham', 'వల్లూరు (పుష్పగిరి)'),
  ('kadapa-ysr', 'veeraballi', 'Veeraballi', 'వీరబల్లి'),
  ('kadapa-ysr', 'veerapunayunipalle', 'Veerapunayunipalle', 'వీరపునాయునిపల్లె'),
  ('kadapa-ysr', 'vempalle', 'Vempalle (Idupulapaya Valley)', 'వెంపల్లె'),
  ('kadapa-ysr', 'vemula', 'Vemula Uranium Corporation', 'వేముల'),
  ('kadapa-ysr', 'vontimitta', 'Vontimitta Sri Kodandarama Temple', 'ఒంటిమిట్ట'),
  ('kadapa-ysr', 'yerraguntla', 'Yerraguntla South India Cement Capital', 'ఎర్రగుంట్ల'),
  ('annamayya', 'b-kothakota', 'B. Kothakota Horsley Hills Gateway', 'బి. కొత్తకోట (హార్సిలీ హిల్స్)'),
  ('annamayya', 'beerangi-kothakota', 'Beerangi Kothakota', 'బి.కొత్తకోట'),
  ('annamayya', 'chinnamandem', 'Chinnamandem', 'చిన్నమండెం'),
  ('annamayya', 'chinnamandyam', 'Chinnamandyam', 'చిన్నమండెం'),
  ('annamayya', 'chitvel', 'Chitvel', 'చిట్వేలు'),
  ('annamayya', 'chowdepalle', 'Chowdepalle', 'చౌడేపల్లి'),
  ('annamayya', 'galiveedu', 'Galiveedu Solar Power Fields', 'గాలివీడు'),
  ('annamayya', 'gurramkonda', 'Gurramkonda Heritage Citadel', 'గుర్రంకొండ'),
  ('annamayya', 'kv-palle', 'K.V. Palle', 'కె.వి. పల్లె'),
  ('annamayya', 'kalakada', 'Kalakada', 'కలకడ'),
  ('annamayya', 'kalikiri', 'Kalikiri Sainik School', 'కలికిరి'),
  ('annamayya', 'kambhamvaripalle', 'Kambhamvaripalle', 'కంబంవారిపల్లె'),
  ('annamayya', 'kurabalakota', 'Kurabalakota', 'కురబలకోట'),
  ('annamayya', 'lakkireddipalli', 'Lakkireddipalli', 'లక్కిరెడ్డిపల్లె'),
  ('annamayya', 'lakkireddypalle', 'Lakkireddypalle', 'లక్కిరెడ్డిపల్లె'),
  ('annamayya', 'madanapalle', 'Madanapalle Silk City & Asia Largest Tomato Market', 'మదనపల్లె'),
  ('annamayya', 'mulakalacheruvu', 'Mulakalacheruvu', 'ములకలచెరువు'),
  ('annamayya', 'nandalur', 'Nandalur Soumyanatha Swamy Historic Temple', 'నందలూరు'),
  ('annamayya', 'nimmanapalle', 'Nimmanapalle Krishnamurti Foundation', 'నిమ్మనపల్లె'),
  ('annamayya', 'obulavaripalle', 'Obulavaripalle World Mangampeta Barites Mine', 'ఓబులవారిపల్లె'),
  ('annamayya', 'peddamandyam', 'Peddamandyam', 'పెద్దమండ్యం'),
  ('annamayya', 'peddathippasamudram', 'Peddathippasamudram', 'పెద్దతిప్పసముద్రం'),
  ('annamayya', 'penagalur', 'Penagalur', 'పెనగలూరు'),
  ('annamayya', 'pileru', 'Pileru Commercial Cross Roads', 'పీలేరు'),
  ('annamayya', 'pullampeta', 'Pullampeta', 'పుల్లంపేట'),
  ('annamayya', 'punganur', 'Punganur', 'పుంగనూరు'),
  ('annamayya', 'railway-koduru', 'Railway Koduru Mango & Banana Junction', 'రైల్వే కోడూరు'),
  ('annamayya', 'rajampet', 'Rajampet Education Hub', 'రాజంపేట'),
  ('annamayya', 'ramapuram', 'Ramapuram', 'రామాపురం'),
  ('annamayya', 'ramasamu-dram', 'Ramasamudram', 'రామసముద్రం'),
  ('annamayya', 'rayachoti', 'Rayachoti Headquarters / Veerabhadra Swamy', 'రాయచోటి'),
  ('annamayya', 'sambepalle', 'Sambepalle', 'సంబేపల్లి'),
  ('annamayya', 'sambepalli', 'Sambepalli', 'సంబేపల్లి'),
  ('annamayya', 'sodam', 'Sodam', 'సోదం'),
  ('annamayya', 'somala', 'Somala', 'సోమల'),
  ('annamayya', 't-sundupalle', 'T. Sundupalle', 'టి. సుండుపల్లె'),
  ('annamayya', 'tallapaka', 'Tallapaka Sri Pada Kavitha Pitamaha Janmasthalam', 'తాళ్లపాక'),
  ('annamayya', 'thamballapalle', 'Thamballapalle', 'తంబళ్లపల్లె'),
  ('annamayya', 'valmikipuram', 'Valmikipuram (Vayalpadu)', 'వాల్మీకిపురం'),
  ('annamayya', 'veeraballi', 'Veeraballi', 'వీరబల్లి'),
  ('tirupati', 'balayapalle', 'Balayapalle', 'బాలాయపల్లె'),
  ('tirupati', 'buchinaidu-kandriga', 'Buchinaidu Kandriga', 'బుచ్చినాయుడు కండ్రిగ'),
  ('tirupati', 'chandragiri', 'Chandragiri Historic Vijayanagara Fort', 'చంద్రగిరి'),
  ('tirupati', 'chillakur', 'Chillakur', 'చిల్లకూరు'),
  ('tirupati', 'chinnagottigallu', 'Chinnagottigallu', 'చిన్నగొట్టిగల్లు'),
  ('tirupati', 'chittamur', 'Chittamur', 'చిట్టమూరు'),
  ('tirupati', 'chitvel', 'Chitvel', 'చిట్వేలు'),
  ('tirupati', 'dakkili', 'Dakkili', 'డక్కిలి'),
  ('tirupati', 'doravarisatram', 'Doravarisatram (Pulicat Bird Sanctuary)', 'దొరవారిసత్రం'),
  ('tirupati', 'gudur', 'Gudur Lemon Market & Railway Junction', 'గూడూరు'),
  ('tirupati', 'k-v-b-puram', 'K. V. B. Puram', 'కె.వి.బి.పురం'),
  ('tirupati', 'kodur', 'Kodur', 'కోడూరు'),
  ('tirupati', 'kota', 'Kota', 'కోట'),
  ('tirupati', 'nagalapuram', 'Nagalapuram Vedanarayana Swamy Temple', 'నాగలాపురం'),
  ('tirupati', 'naidupeta', 'Naidupeta Special Economic Zone', 'నాయుడుపేట'),
  ('tirupati', 'narayanavanam', 'Narayanavanam Sri Kalyana Venkateswara', 'నారాయణవనం'),
  ('tirupati', 'obulavaripalle', 'Obulavaripalle', 'ఓబులవారిపల్లె'),
  ('tirupati', 'ozili', 'Ozili', 'ఓజిలి'),
  ('tirupati', 'pakala', 'Pakala Lake & Railway Junction', 'పాకాల'),
  ('tirupati', 'pellakur', 'Pellakur', 'పెళ్లకూరు'),
  ('tirupati', 'penagalur', 'Penagalur', 'పెనగలూరు'),
  ('tirupati', 'pichatur', 'Pichatur Araniar Reservoir', 'పిచ్చాటూరు'),
  ('tirupati', 'pullampeta', 'Pullampeta', 'పుల్లంపేట'),
  ('tirupati', 'puttur', 'Puttur Joint Kattu & Commercial Town', 'పుత్తూరు'),
  ('tirupati', 'ramachandrapuram-tpt', 'Ramachandrapuram', 'రామచంద్రాపురం'),
  ('tirupati', 'renigunta', 'Renigunta Airport & Railway Terminus', 'రేణిగుంట'),
  ('tirupati', 'satyavedu', 'Satyavedu Border Industrial Belt', 'సత్యవేడు'),
  ('tirupati', 'srikalahasti', 'Srikalahasti Vayu Linga Kshetram', 'శ్రీకాళహస్తి'),
  ('tirupati', 'sullurpeta', 'Sullurpeta (Satish Dhawan Space Centre ISRO SHAR)', 'సూళ్లూరుపేట'),
  ('tirupati', 'tada', 'Tada Sri City Integrated Industrial Township', 'తడ (శ్రీసిటీ)'),
  ('tirupati', 'thottambedu', 'Thottambedu', 'తొట్టంబేడు'),
  ('tirupati', 'tirumala', 'Tirumala Lord Venkateswara Abode', 'తిరుమల'),
  ('tirupati', 'tirupati-rural', 'Tirupati Rural', 'తిరుపతి రూరల్'),
  ('tirupati', 'tirupati-urban', 'Tirupati Urban (Alipiri / Balaji Colony)', 'తిరుపతి అర్బన్'),
  ('tirupati', 'vadamalapeta', 'Vadamalapeta Appalayagunta Temple', 'వడమాలపేట'),
  ('tirupati', 'vakadu', 'Vakadu', 'వాకాడు'),
  ('tirupati', 'varadaiahpalem', 'Varadaiahpalem Spiritual Valley', 'వరదయ్యపాలెం'),
  ('tirupati', 'venkatagiri', 'Venkatagiri Heritage Zari Sarees & Palace', 'వెంకటగిరి'),
  ('tirupati', 'yerpedu', 'Yerpedu (IIT & IISER Campus)', 'ఏర్పేడు'),
  ('tirupati', 'yerravaripalem', 'Yerravaripalem Talakona Waterfalls', 'ఎర్రవారిపాలెం'),
  ('chittoor', 'baireddipalle', 'Baireddipalle', 'బైరెడ్డిపల్లె'),
  ('chittoor', 'bangarupalem', 'Bangarupalem', 'బంగారుపాలెం'),
  ('chittoor', 'bangurupalem', 'Bangurupalem', 'బంగారుపాలెం'),
  ('chittoor', 'bireddypalli', 'Bireddypalli', 'బైరెడ్డిపల్లి'),
  ('chittoor', 'chittoor-rural', 'Chittoor Rural', 'చిత్తూరు రూరల్'),
  ('chittoor', 'chittoor-urban', 'Chittoor Urban / Mango Pulp Capital', 'చిత్తూరు అర్బన్'),
  ('chittoor', 'chowdepalle', 'Chowdepalle Boyakonda Gangamma Temple', 'చౌడేపల్లి'),
  ('chittoor', 'gd-nellore', 'G.D. Nellore', 'గంగాధర నెల్లూరు'),
  ('chittoor', 'gangadhara-nellore', 'Gangadhara Nellore', 'గంగాధర నెల్లూరు'),
  ('chittoor', 'gangavaram-ctr', 'Gangavaram', 'గంగవరం'),
  ('chittoor', 'gudipala', 'Gudipala', 'గుడిపాల'),
  ('chittoor', 'gudipalle', 'Gudipalle', 'గుడిపల్లె'),
  ('chittoor', 'gudupalle', 'Gudupalle Dravidian University', 'గుడుపల్లె'),
  ('chittoor', 'irala', 'Irala', 'ఐరాల'),
  ('chittoor', 'kanipakam', 'Kanipakam Sri Varasiddhi Vinayaka Kshetram', 'కాణిపాకం'),
  ('chittoor', 'karvetinagaram', 'Karvetinagaram Heritage Rajahs Palace', 'కార్వేటినగరం'),
  ('chittoor', 'kuppam', 'Kuppam Tri-State Tri-Junction (AP-TN-KA)', 'కుప్పం'),
  ('chittoor', 'nagari', 'Nagari Weaving Town & Border Hub', 'నగరి'),
  ('chittoor', 'nindra', 'Nindra', 'నిండ్ర'),
  ('chittoor', 'palamaner', 'Palamaner Dairy Cattle Research & NH75', 'పలమనేరు'),
  ('chittoor', 'palasamudram', 'Palasamudram', 'పాలసముద్రం'),
  ('chittoor', 'peddapanjani', 'Peddapanjani', 'పెద్దపంజాణి'),
  ('chittoor', 'penumuru', 'Penumuru', 'పెనుమూరు'),
  ('chittoor', 'pulicherla', 'Pulicherla', 'పులిచెర్ల'),
  ('chittoor', 'punganur', 'Punganur World Miniature Dwarf Cattle Land', 'పుంగనూరు'),
  ('chittoor', 'puthalapattu', 'Puthalapattu', 'పూతలపట్టు'),
  ('chittoor', 'ramakuppam', 'Ramakuppam', 'రామకుప్పం'),
  ('chittoor', 'rompicherla-ctr', 'Rompicherla', 'రొంపిచర్ల'),
  ('chittoor', 'sr-puram', 'S.R. Puram', 'ఎస్.ఆర్. పురం'),
  ('chittoor', 'shanthipuram', 'Santhipuram', 'శాంతిపురం'),
  ('chittoor', 'sodam', 'Sodam', 'సోదం'),
  ('chittoor', 'somala', 'Somala', 'సోమల'),
  ('chittoor', 'sri-rangaraja-puram', 'Sri Rangaraja Puram', 'శ్రీరంగరాజపురం'),
  ('chittoor', 'thavanampalle', 'Thavanampalle Kanipakam Gateway', 'తవణంపల్లి'),
  ('chittoor', 'vedurukuppam', 'Vedurukuppam', 'వెదురుకుప్పం'),
  ('chittoor', 'v-kota', 'Venkatagirikota (V. Kota)', 'వి. కోట'),
  ('chittoor', 'vijayapuram', 'Vijayapuram', 'విజయపురం'),
  ('chittoor', 'yadamarri', 'Yadamarri', 'యాదమరి')
ON CONFLICT (district, slug) DO UPDATE SET name_en = EXCLUDED.name_en, name_te = EXCLUDED.name_te;

-- 4. Update fn_submit_profile() to generate state-aware sovereign matrimonial IDs
CREATE OR REPLACE FUNCTION fn_submit_profile() RETURNS TABLE (matrimonial_id text, coordinator_assigned boolean)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = matrimony_shared, pg_temp
AS $$
DECLARE
  v_me           uuid := fn_current_user_id();
  v_p            profiles%ROWTYPE;
  v_purpose      consent_purpose;
  v_coord        uuid;
  v_id           text;
  v_code         text;
  v_year         int;
  v_n            bigint;
  v_state_prefix text;
BEGIN
  IF v_me IS NULL THEN
    RAISE EXCEPTION 'no request identity' USING ERRCODE = 'insufficient_privilege';
  END IF;
  SELECT * INTO v_p FROM profiles WHERE root_user_id = v_me;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'profile not found' USING ERRCODE = 'no_data_found';
  END IF;
  IF v_p.status NOT IN ('draft', 'rejected') THEN
    RAISE EXCEPTION 'profile not in a submittable state (%)', v_p.status USING ERRCODE = 'object_not_in_prerequisite_state';
  END IF;
  IF v_p.occupation IS NULL OR v_p.education_degree IS NULL OR v_p.income_bracket IS NULL THEN
    RAISE EXCEPTION 'incomplete profile details' USING ERRCODE = 'check_violation';
  END IF;
  FOREACH v_purpose IN ARRAY '{community_pledge,profile_processing,coordinator_verification}'::consent_purpose[] LOOP
    IF NOT fn_latest_consent(v_me, v_purpose) THEN
      RAISE EXCEPTION 'consent % not granted', v_purpose USING ERRCODE = 'check_violation';
    END IF;
  END LOOP;

  v_coord := fn_pick_coordinator(v_p.ancestral_native_district, v_p.ancestral_native_mandal, v_me);
  v_id := v_p.matrimonial_id;
  IF v_id IS NULL THEN
    SELECT d.code INTO v_code FROM districts d WHERE d.slug = v_p.ancestral_native_district;
    IF v_code IS NULL THEN
      v_code := 'OTHR';
    END IF;

    IF v_p.ancestral_native_district IN (
      'srikakulam', 'vizianagaram', 'parvathipuram-manyam', 'alluri-sitharama-raju', 'visakhapatnam',
      'anakapalli', 'kakinada', 'konaseema', 'east-godavari', 'west-godavari', 'eluru', 'krishna',
      'vijayawada-ntr', 'guntur', 'palnadu', 'bapatla', 'prakasam', 'sri-potti-sriramulu-nellore',
      'kurnool', 'nandyal', 'anantapur', 'sri-sathya-sai', 'kadapa-ysr', 'annamayya', 'tirupati', 'chittoor'
    ) THEN
      v_state_prefix := 'AP';
    ELSIF v_p.ancestral_native_district = 'other-state' THEN
      v_state_prefix := 'IN';
    ELSE
      v_state_prefix := 'TG';
    END IF;

    v_year := extract(year FROM now() AT TIME ZONE 'Asia/Kolkata');
    INSERT INTO matrimonial_id_counters AS c (district_code, year, last_value) VALUES (v_code, v_year, 1)
    ON CONFLICT ON CONSTRAINT pk_matrimonial_id_counters DO UPDATE SET last_value = c.last_value + 1
    RETURNING c.last_value INTO v_n;
    v_id := format('NSM-%s-%s-%s-%s', v_state_prefix, v_code, v_year, lpad(v_n::text, greatest(4, length(v_n::text)), '0'));
  END IF;

  UPDATE profiles p
     SET status = 'pending_mandal_review', assigned_coordinator_user_id = v_coord,
         matrimonial_id = v_id, submitted_at = now()
   WHERE p.id = v_p.id;
  RETURN QUERY SELECT v_id, v_coord IS NOT NULL;
END $$;
