export interface MandalItem {
  district: string;
  slug: string;
  nameEn: string;
  nameTe?: string;
}

export interface DistrictItem {
  slug: string;
  code: string;
  nameEn: string;
  nameTe: string;
  state: 'telangana' | 'andhra-pradesh';
}

/**
 * Official 26 Districts of Andhra Pradesh based on the 2022 District Reorganization (AP Gazette)
 */
export const ALL_ANDHRA_DISTRICTS: DistrictItem[] = [
  // Uttarandhra (North Coastal)
  { slug: 'srikakulam', code: 'SKLM', nameEn: 'Srikakulam', nameTe: 'శ్రీకాకుళం', state: 'andhra-pradesh' },
  { slug: 'vizianagaram', code: 'VZNR', nameEn: 'Vizianagaram', nameTe: 'విజయనగరం', state: 'andhra-pradesh' },
  { slug: 'parvathipuram-manyam', code: 'PMNM', nameEn: 'Parvathipuram Manyam', nameTe: 'పార్వతీపురం మన్యం', state: 'andhra-pradesh' },
  { slug: 'alluri-sitharama-raju', code: 'ASRJ', nameEn: 'Alluri Sitharama Raju', nameTe: 'అల్లూరి సీతారామరాజు', state: 'andhra-pradesh' },
  { slug: 'visakhapatnam', code: 'VSPM', nameEn: 'Visakhapatnam', nameTe: 'విశాఖపట్నం', state: 'andhra-pradesh' },
  { slug: 'anakapalli', code: 'AKPL', nameEn: 'Anakapalli', nameTe: 'అనకాపల్లి', state: 'andhra-pradesh' },

  // Kosta Andhra (Coastal)
  { slug: 'kakinada', code: 'KKND', nameEn: 'Kakinada', nameTe: 'కాకినాడ', state: 'andhra-pradesh' },
  { slug: 'konaseema', code: 'KNSM', nameEn: 'Dr. B.R. Ambedkar Konaseema', nameTe: 'డా. బి.ఆర్. అంబేద్కర్ కోనసీమ', state: 'andhra-pradesh' },
  { slug: 'east-godavari', code: 'EGOD', nameEn: 'East Godavari (Rajamahendravaram)', nameTe: 'తూర్పు గోదావరి (రాజమహేంద్రవరం)', state: 'andhra-pradesh' },
  { slug: 'west-godavari', code: 'WGOD', nameEn: 'West Godavari (Bhimavaram)', nameTe: 'పశ్చిమ గోదావరి (భీమవరం)', state: 'andhra-pradesh' },
  { slug: 'eluru', code: 'ELRU', nameEn: 'Eluru', nameTe: 'ఏలూరు', state: 'andhra-pradesh' },
  { slug: 'krishna', code: 'KSHN', nameEn: 'Krishna (Machilipatnam)', nameTe: 'కృష్ణా (మచిలీపట్నం)', state: 'andhra-pradesh' },
  { slug: 'vijayawada-ntr', code: 'VNTR', nameEn: 'NTR (Vijayawada)', nameTe: 'ఎన్టీఆర్ (విజయవాడ)', state: 'andhra-pradesh' },
  { slug: 'guntur', code: 'GNTR', nameEn: 'Guntur', nameTe: 'గుంటూరు', state: 'andhra-pradesh' },
  { slug: 'palnadu', code: 'PLND', nameEn: 'Palnadu (Narasaraopet)', nameTe: 'పల్నాడు (నరసరావుపేట)', state: 'andhra-pradesh' },
  { slug: 'bapatla', code: 'BPTL', nameEn: 'Bapatla', nameTe: 'బాపట్ల', state: 'andhra-pradesh' },
  { slug: 'prakasam', code: 'PKSM', nameEn: 'Prakasam (Ongole)', nameTe: 'ప్రకాశం (ఒంగోలు)', state: 'andhra-pradesh' },
  { slug: 'sri-potti-sriramulu-nellore', code: 'SPSN', nameEn: 'Sri Potti Sriramulu Nellore', nameTe: 'శ్రీ పొట్టి శ్రీరాములు నెల్లూరు', state: 'andhra-pradesh' },

  // Rayalaseema
  { slug: 'kurnool', code: 'KRNL', nameEn: 'Kurnool', nameTe: 'కర్నూలు', state: 'andhra-pradesh' },
  { slug: 'nandyal', code: 'NDYL', nameEn: 'Nandyal', nameTe: 'నంద్యాల', state: 'andhra-pradesh' },
  { slug: 'anantapur', code: 'ANTP', nameEn: 'Ananthapuramu', nameTe: 'అనంతపురం', state: 'andhra-pradesh' },
  { slug: 'sri-sathya-sai', code: 'SSSI', nameEn: 'Sri Sathya Sai (Puttaparthi)', nameTe: 'శ్రీ సత్యసాయి (పుట్టపర్తి)', state: 'andhra-pradesh' },
  { slug: 'kadapa-ysr', code: 'KYSR', nameEn: 'YSR Kadapa', nameTe: 'వైఎస్సార్ కడప', state: 'andhra-pradesh' },
  { slug: 'annamayya', code: 'ANMY', nameEn: 'Annamayya (Rayachoti)', nameTe: 'అన్నమయ్య (రాయచోటి)', state: 'andhra-pradesh' },
  { slug: 'tirupati', code: 'TRPT', nameEn: 'Tirupati', nameTe: 'తిరుపతి', state: 'andhra-pradesh' },
  { slug: 'chittoor', code: 'CHTR', nameEn: 'Chittoor', nameTe: 'చిత్తూరు', state: 'andhra-pradesh' },
];

/**
 * Authentic Revenue Mandals and Major Towns for all 26 Districts of Andhra Pradesh
 * 100% Comprehensive coverage: 681 Official Revenue Mandals + prominent Urban Divisions & Historical Towns
 */
export const ANDHRA_PRADESH_MANDALS_MAP: Record<string, { slug: string; nameEn: string; nameTe: string }[]> = {
  'srikakulam': [
    { slug: 'amadalavalasa', nameEn: 'Amadalavalasa', nameTe: 'ఆమదాలవలస' },
    { slug: 'burja', nameEn: 'Burja', nameTe: 'బూర్జ' },
    { slug: 'etcherla', nameEn: 'Etcherla', nameTe: 'ఎచ్చెర్ల' },
    { slug: 'ganguvarisigadam', nameEn: 'Ganguvarisigadam', nameTe: 'గంగువారిసిగడం' },
    { slug: 'gara', nameEn: 'Gara', nameTe: 'గార' },
    { slug: 'hiramandalam', nameEn: 'Hiramandalam', nameTe: 'హీరమండలం' },
    { slug: 'ichchapuram', nameEn: 'Ichchapuram', nameTe: 'ఇచ్ఛాపురం' },
    { slug: 'jalumuru', nameEn: 'Jalumuru', nameTe: 'జలుమూరు' },
    { slug: 'kanchili', nameEn: 'Kanchili', nameTe: 'కంచిలి' },
    { slug: 'kaviti', nameEn: 'Kaviti', nameTe: 'కవిటి' },
    { slug: 'kotabommali', nameEn: 'Kotabommali', nameTe: 'కోటబొమ్మాళి' },
    { slug: 'lakshminarsupeta', nameEn: 'Lakshminarsupeta', nameTe: 'లక్ష్మీనర్సుపేట' },
    { slug: 'laveru', nameEn: 'Laveru', nameTe: 'లావేరు' },
    { slug: 'mandasa', nameEn: 'Mandasa', nameTe: 'మందస' },
    { slug: 'meliaputti', nameEn: 'Meliaputti', nameTe: 'మేళియాపుట్టి' },
    { slug: 'nandigam', nameEn: 'Nandigam', nameTe: 'నందిగాం' },
    { slug: 'narasannapeta', nameEn: 'Narasannapeta', nameTe: 'నరసన్నపేట' },
    { slug: 'palasa', nameEn: 'Palasa / Kasibugga', nameTe: 'పలాస / కాశీబుగ్గ' },
    { slug: 'pathapatnam', nameEn: 'Pathapatnam', nameTe: 'పాతపట్నం' },
    { slug: 'polaki', nameEn: 'Polaki', nameTe: 'పోలాకి' },
    { slug: 'ponduru', nameEn: 'Ponduru Khadi', nameTe: 'పొందూరు' },
    { slug: 'ranastalam', nameEn: 'Ranastalam', nameTe: 'రణస్థలం' },
    { slug: 'santhabommali', nameEn: 'Santhabommali', nameTe: 'సంతబొమ్మాళి' },
    { slug: 'saravakota', nameEn: 'Saravakota', nameTe: 'సారవకోట' },
    { slug: 'sarubujjili', nameEn: 'Sarubujjili', nameTe: 'సారుబుజ్జిలి' },
    { slug: 'sompeta', nameEn: 'Sompeta', nameTe: 'సోంపేట' },
    { slug: 'srikakulam-rural', nameEn: 'Srikakulam Rural', nameTe: 'శ్రీకాకుళం రూరల్' },
    { slug: 'srikakulam-urban', nameEn: 'Srikakulam Urban', nameTe: 'శ్రీకాకుళం అర్బన్' },
    { slug: 'tekkali', nameEn: 'Tekkali', nameTe: 'టెక్కలి' },
    { slug: 'vajrapukothuru', nameEn: 'Vajrapukothuru', nameTe: 'వజ్రపుకొత్తూరు' },
  ],
  'vizianagaram': [
    { slug: 'badangi', nameEn: 'Badangi', nameTe: 'బాడాంగి' },
    { slug: 'bhogapuram', nameEn: 'Bhogapuram Airport Zone', nameTe: 'భోగాపురం' },
    { slug: 'bobbili', nameEn: 'Bobbili Heritage Town', nameTe: 'బొబ్బిలి' },
    { slug: 'bondapalle', nameEn: 'Bondapalle', nameTe: 'బొండపల్లి' },
    { slug: 'cheepurupalle', nameEn: 'Cheepurupalle', nameTe: 'చీపురుపల్లి' },
    { slug: 'dattirajeru', nameEn: 'Dattirajeru', nameTe: 'దత్తిరాజేరు' },
    { slug: 'denkada', nameEn: 'Denkada', nameTe: 'డెంకాడ' },
    { slug: 'gajapathinagaram', nameEn: 'Gajapathinagaram', nameTe: 'గజపతినగరం' },
    { slug: 'gantyada', nameEn: 'Gantyada', nameTe: 'గంట్యాడ' },
    { slug: 'garividi', nameEn: 'Garividi', nameTe: 'గరివిడి' },
    { slug: 'gurla', nameEn: 'Gurla', nameTe: 'గుర్ల' },
    { slug: 'jami', nameEn: 'Jami', nameTe: 'జామి' },
    { slug: 'kothavalasa', nameEn: 'Kothavalasa', nameTe: 'కొత్తవలస' },
    { slug: 'lakkavarapukota', nameEn: 'Lakkavarapukota', nameTe: 'లక్కవరపుకోట' },
    { slug: 'mentada', nameEn: 'Mentada', nameTe: 'మెంటాడ' },
    { slug: 'merakamudidam', nameEn: 'Merakamudidam', nameTe: 'మెరకముడిదాం' },
    { slug: 'nellimarla', nameEn: 'Nellimarla', nameTe: 'నెల్లిమర్ల' },
    { slug: 'pusapatirega', nameEn: 'Pusapatirega', nameTe: 'పూసపాటిరేగ' },
    { slug: 'rajam', nameEn: 'Rajam', nameTe: 'రాజాం' },
    { slug: 'ramabhadrapuram', nameEn: 'Ramabhadrapuram', nameTe: 'రామభద్రపురం' },
    { slug: 'regidi-amadalavalasa', nameEn: 'Regidi Amadalavalasa', nameTe: 'రేగిడి ఆమదాలవలస' },
    { slug: 'sringavarapukota', nameEn: 'S.Kota (Sringavarapukota)', nameTe: 'శృంగవరపుకోట' },
    { slug: 'santhakaviti', nameEn: 'Santhakaviti', nameTe: 'సంతకవిటి' },
    { slug: 'srungavarapukota', nameEn: 'Srungavarapukota', nameTe: 'శృంగవరపుకోట (ఎస్.కోట)' },
    { slug: 'therlam', nameEn: 'Therlam', nameTe: 'తెర్లాం' },
    { slug: 'vangara', nameEn: 'Vangara', nameTe: 'వంగర' },
    { slug: 'vepada', nameEn: 'Vepada', nameTe: 'వేపాడ' },
    { slug: 'vizianagaram-rural', nameEn: 'Vizianagaram Rural', nameTe: 'విజయనగరం రూరల్' },
    { slug: 'vizianagaram-urban', nameEn: 'Vizianagaram Urban', nameTe: 'విజయనగరం అర్బన్' },
  ],
  'parvathipuram-manyam': [
    { slug: 'balijipeta', nameEn: 'Balijipeta', nameTe: 'బలిజిపేట' },
    { slug: 'bhamini', nameEn: 'Bhamini', nameTe: 'భామినీ' },
    { slug: 'garugubilli', nameEn: 'Garugubilli', nameTe: 'గరుగుబిల్లి' },
    { slug: 'gummalakshmipuram', nameEn: 'Gummalakshmipuram', nameTe: 'గుమ్మలక్ష్మీపురం' },
    { slug: 'gummalaxmipuram', nameEn: 'Gummalaxmipuram', nameTe: 'గుమ్మలక్ష్మీపురం' },
    { slug: 'jiyyammavalasa', nameEn: 'Jiyyammavalasa', nameTe: 'జియ్యమ్మవలస' },
    { slug: 'komarada', nameEn: 'Komarada', nameTe: 'కొమరాడ' },
    { slug: 'kurupam', nameEn: 'Kurupam', nameTe: 'కురుపాం' },
    { slug: 'makkuva', nameEn: 'Makkuva', nameTe: 'మక్కువ' },
    { slug: 'pachipenta', nameEn: 'Pachipenta', nameTe: 'పాచిపెంట' },
    { slug: 'palakonda', nameEn: 'Palakonda', nameTe: 'పాలకొండ' },
    { slug: 'parvathipuram', nameEn: 'Parvathipuram Headquarters', nameTe: 'పార్వతీపురం' },
    { slug: 'salur', nameEn: 'Salur', nameTe: 'సాలూరు' },
    { slug: 'seethampeta', nameEn: 'Seethampeta', nameTe: 'సీతంపేట' },
    { slug: 'seethanagaram', nameEn: 'Seethanagaram', nameTe: 'సీతానగరం' },
    { slug: 'veeraghattam', nameEn: 'Veeraghattam', nameTe: 'వీరఘట్టం' },
  ],
  'alluri-sitharama-raju': [
    { slug: 'addateegala', nameEn: 'Addateegala', nameTe: 'అడ్డతీగల' },
    { slug: 'ananthagiri', nameEn: 'Ananthagiri Borra Caves', nameTe: 'అనంతగిరి' },
    { slug: 'araku-valley', nameEn: 'Araku Valley Coffee Hills', nameTe: 'అరకు లోయ' },
    { slug: 'chintapalle', nameEn: 'Chintapalle Lambasingi', nameTe: 'చింతపల్లి (లంబసింగి)' },
    { slug: 'chintoor', nameEn: 'Chintoor / Koonavaram', nameTe: 'చింతూరు / కూనవరం' },
    { slug: 'chintur', nameEn: 'Chintur', nameTe: 'చింతూరు' },
    { slug: 'devipatnam', nameEn: 'Devipatnam', nameTe: 'దేవీపట్నం' },
    { slug: 'dumbriguda', nameEn: 'Dumbriguda', nameTe: 'డుంబ్రిగుడ' },
    { slug: 'etapaka', nameEn: 'Etapaka', nameTe: 'ఎటపాక' },
    { slug: 'g-madugula', nameEn: 'G. Madugula', nameTe: 'జి. మాడుగుల' },
    { slug: 'gangavaram-asr', nameEn: 'Gangavaram', nameTe: 'గంగవరం' },
    { slug: 'gudem-kotha-veedhi', nameEn: 'Gudem Kotha Veedhi', nameTe: 'గూడెం కొత్తవీధి' },
    { slug: 'gurthedu', nameEn: 'Gurthedu', nameTe: 'గూర్తేడు' },
    { slug: 'hukumpeta', nameEn: 'Hukumpeta', nameTe: 'హుకుంపేట' },
    { slug: 'koyyuru', nameEn: 'Koyyuru', nameTe: 'కొయ్యూరు' },
    { slug: 'kunavaram', nameEn: 'Kunavaram', nameTe: 'కూనవరం' },
    { slug: 'maredumilli', nameEn: 'Maredumilli Eco Forest', nameTe: 'మారేడుమిల్లి' },
    { slug: 'munchingiputtu', nameEn: 'Munchingi Puttu', nameTe: 'ముంచింగిపుట్టు' },
    { slug: 'paderu', nameEn: 'Paderu Headquarters', nameTe: 'పాడేరు' },
    { slug: 'pedabayalu', nameEn: 'Pedabayalu', nameTe: 'పెదబయలు' },
    { slug: 'rajavommangi', nameEn: 'Rajavommangi', nameTe: 'రాజవొమ్మంగి' },
    { slug: 'rampachodavaram', nameEn: 'Rampachodavaram Godavari Basin', nameTe: 'రంపచోడవరం' },
    { slug: 'vararamachandrapuram', nameEn: 'Vararamachandrapuram', nameTe: 'వరరామచంద్రపురం (వి.ఆర్.పురం)' },
    { slug: 'y-ramavaram', nameEn: 'Y. Ramavaram', nameTe: 'వై.రామవరం' },
  ],
  'visakhapatnam': [
    { slug: 'anandapuram', nameEn: 'Anandapuram', nameTe: 'ఆనందపురం' },
    { slug: 'bheemunipatnam', nameEn: 'Bheemunipatnam (Bheemili Beach)', nameTe: 'భీమునిపట్నం' },
    { slug: 'gajuwaka', nameEn: 'Gajuwaka Industrial Hub', nameTe: 'గాజువాక' },
    { slug: 'gopalapatnam', nameEn: 'Gopalapatnam / Simhachalam', nameTe: 'గోపాలపట్నం (సింహాచలం)' },
    { slug: 'madhurawada', nameEn: 'Madhurawada / IT SEZ', nameTe: 'మధురవాడ' },
    { slug: 'maharanipeta', nameEn: 'Maharanipeta (Collectorate)', nameTe: 'మహారాణిపేట' },
    { slug: 'mulagada', nameEn: 'Mulagada', nameTe: 'ములగాడ' },
    { slug: 'mvp-colony', nameEn: 'MVP Colony / Beach Road', nameTe: 'ఎం.వి.పి. కాలనీ' },
    { slug: 'padmanabham', nameEn: 'Padmanabham', nameTe: 'పద్మనాభం' },
    { slug: 'pedagantyada', nameEn: 'Pedagantyada Steel Plant', nameTe: 'పెదగంట్యాడ' },
    { slug: 'pendurthi', nameEn: 'Pendurthi', nameTe: 'పెందుర్తి' },
    { slug: 'seethammadhara', nameEn: 'Seethammadhara', nameTe: 'సీతమ్మధార' },
    { slug: 'visakhapatnam-rural', nameEn: 'Visakhapatnam Rural', nameTe: 'విశాఖపట్నం రూరల్' },
  ],
  'anakapalli': [
    { slug: 'anakapalle', nameEn: 'Anakapalle Jaggery Market', nameTe: 'అనకాపల్లి' },
    { slug: 'anakapalli', nameEn: 'Anakapalli', nameTe: 'అనకాపల్లి' },
    { slug: 'atchutapuram', nameEn: 'Atchutapuram SEZ', nameTe: 'అచ్యుతాపురం' },
    { slug: 'butchayyapeta', nameEn: 'Butchayyapeta', nameTe: 'బుచ్చయ్యపేట' },
    { slug: 'cheedikada', nameEn: 'Cheedikada', nameTe: 'చీడికాడ' },
    { slug: 'chodavaram', nameEn: 'Chodavaram', nameTe: 'చోడవరం' },
    { slug: 'devarapalle', nameEn: 'Devarapalle', nameTe: 'దేవరపల్లి' },
    { slug: 'devarapalli', nameEn: 'Devarapalli', nameTe: 'దేవరపల్లి' },
    { slug: 'golugonda', nameEn: 'Golugonda', nameTe: 'గొలుగొండ' },
    { slug: 'k-kotapadu', nameEn: 'K. Kotapadu', nameTe: 'కె. కోటపాడు' },
    { slug: 'kasimkota', nameEn: 'Kasimkota', nameTe: 'కాశీంకోట' },
    { slug: 'kotauratla', nameEn: 'Kotauratla', nameTe: 'కోటవురట్ల' },
    { slug: 'madugula', nameEn: 'Madugula Halwa Heritage', nameTe: 'మాడుగుల' },
    { slug: 'makavarapalem', nameEn: 'Makavarapalem', nameTe: 'మాకవరపాలెం' },
    { slug: 'munagapaka', nameEn: 'Munagapaka', nameTe: 'మునగపాక' },
    { slug: 'nakkapalle', nameEn: 'Nakkapalle', nameTe: 'నక్కపల్లి' },
    { slug: 'narsipatnam', nameEn: 'Narsipatnam', nameTe: 'నర్సీపట్నం' },
    { slug: 'nathavaram', nameEn: 'Nathavaram', nameTe: 'నాతవరం' },
    { slug: 'paravada', nameEn: 'Paravada', nameTe: 'పరవాడ' },
    { slug: 'parawada', nameEn: 'Parawada Pharma City', nameTe: 'పరవాడ' },
    { slug: 'payakaraopeta', nameEn: 'Payakaraopeta', nameTe: 'పాయకరావుపేట' },
    { slug: 'rambilli', nameEn: 'Rambilli Coastal', nameTe: 'రాంబిల్లి' },
    { slug: 'ravikamatham', nameEn: 'Ravikamatham', nameTe: 'రావికమతం' },
    { slug: 'rolugunta', nameEn: 'Rolugunta', nameTe: 'రోలుగుంట' },
    { slug: 's-rayavaram', nameEn: 'S. Rayavaram', nameTe: 'ఎస్. రాయవరం' },
    { slug: 'sabbavaram', nameEn: 'Sabbavaram', nameTe: 'సబ్బవరం' },
    { slug: 'sarvasiddhi-rayavaram', nameEn: 'Sarvasiddhi Rayavaram', nameTe: 'ఎస్.రాయవరం' },
    { slug: 'yelamanchili', nameEn: 'Yelamanchili', nameTe: 'యలమంచిలి' },
  ],
  'kakinada': [
    { slug: 'gandepalle', nameEn: 'Gandepalle', nameTe: 'గండేపల్లి' },
    { slug: 'gollaprolu', nameEn: 'Gollaprolu', nameTe: 'గొల్లప్రోలు' },
    { slug: 'jaggampeta', nameEn: 'Jaggampeta', nameTe: 'జగ్గంపేట' },
    { slug: 'kajuluru', nameEn: 'Kajuluru', nameTe: 'కాజులూరు' },
    { slug: 'kakinada-urban', nameEn: 'Kakinada Port & Smart City', nameTe: 'కాకినాడ అర్బన్' },
    { slug: 'kakinada-rural', nameEn: 'Kakinada Rural', nameTe: 'కాకినాడ రూరల్' },
    { slug: 'kakinada-urban-mandal', nameEn: 'Kakinada Urban', nameTe: 'కాకినాడ అర్బన్' },
    { slug: 'karapa', nameEn: 'Karapa', nameTe: 'కరప' },
    { slug: 'kirlampudi', nameEn: 'Kirlampudi', nameTe: 'కిర్లంపూడి' },
    { slug: 'kotananduru', nameEn: 'Kotananduru', nameTe: 'కోటనందూరు' },
    { slug: 'kothapalle', nameEn: 'Kothapalle', nameTe: 'కొత్తపల్లె' },
    { slug: 'pedapudi', nameEn: 'Pedapudi', nameTe: 'పెదపూడి' },
    { slug: 'peddapuram', nameEn: 'Peddapuram', nameTe: 'పెద్దాపురం' },
    { slug: 'pithapuram', nameEn: 'Pithapuram Sripada Kshetram', nameTe: 'పిఠాపురం' },
    { slug: 'prathipadu-kkn', nameEn: 'Prathipadu', nameTe: 'ప్రత్తిపాడు' },
    { slug: 'rowthulapudi', nameEn: 'Rowthulapudi', nameTe: 'రౌతులపూడి' },
    { slug: 'samalkota', nameEn: 'Samalkota Pancharama Kshetram', nameTe: 'సామర్లకోట' },
    { slug: 'sankhavaram', nameEn: 'Sankhavaram', nameTe: 'శంఖవరం' },
    { slug: 'thallarevu', nameEn: 'Thallarevu Coringa Mangroves', nameTe: 'తాళ్లరేవు' },
    { slug: 'thondangi', nameEn: 'Thondangi', nameTe: 'తొండంగి' },
    { slug: 'tuni', nameEn: 'Tuni Betel Leaf Market', nameTe: 'తుని' },
    { slug: 'u-kothapalli', nameEn: 'U. Kothapalli Uppada Beach', nameTe: 'ఉప్పాడ కొత్తపల్లి' },
    { slug: 'yeleswaram', nameEn: 'Yeleswaram', nameTe: 'ఏలేశ్వరం' },
  ],
  'konaseema': [
    { slug: 'ainavilli', nameEn: 'Ainavilli Siddhi Vinayaka', nameTe: 'ఐనవిల్లి' },
    { slug: 'alamuru', nameEn: 'Alamuru', nameTe: 'ఆలమూరు' },
    { slug: 'allavaram', nameEn: 'Allavaram', nameTe: 'అల్లవరం' },
    { slug: 'amalapuram', nameEn: 'Amalapuram Headquarters', nameTe: 'అమలాపురం' },
    { slug: 'ambajipeta', nameEn: 'Ambajipeta Coconut Center', nameTe: 'అంబాజీపేట' },
    { slug: 'atreyapuram', nameEn: 'Atreyapuram Pootharekulu Hub', nameTe: 'ఆత్రేయపురం' },
    { slug: 'i-polavaram', nameEn: 'I. Polavaram', nameTe: 'ఐ.పోలవరం' },
    { slug: 'k-gangavaram', nameEn: 'K. Gangavaram', nameTe: 'కె.గంగవరం' },
    { slug: 'kapileswarapuram', nameEn: 'Kapileswarapuram Zamindari Heritage', nameTe: 'కపిలేశ్వరపురం' },
    { slug: 'katrenikona', nameEn: 'Katrenikona', nameTe: 'కత్రేనికోన' },
    { slug: 'kothapeta', nameEn: 'Kothapeta', nameTe: 'కొత్తపేట' },
    { slug: 'malikipuram', nameEn: 'Malikipuram (Dindi Resorts)', nameTe: 'మలికిపురం' },
    { slug: 'mamidikuduru', nameEn: 'Mamidikuduru', nameTe: 'మామిడికుదురు' },
    { slug: 'mandapeta', nameEn: 'Mandapeta Rice Mill City', nameTe: 'మండపేట' },
    { slug: 'mummidivaram', nameEn: 'Mummidivaram Balayogi Kshetram', nameTe: 'ముమ్మిడివరం' },
    { slug: 'p-gannavaram', nameEn: 'P. Gannavaram Aqueduct', nameTe: 'పి. గన్నవరం' },
    { slug: 'ramachandrapuram', nameEn: 'Ramachandrapuram Draksharamam', nameTe: 'రామచంద్రపురం' },
    { slug: 'ravulapalem', nameEn: 'Ravulapalem Banana Market Hub', nameTe: 'రావులపాలెం' },
    { slug: 'rayavaram', nameEn: 'Rayavaram', nameTe: 'రాయవరం' },
    { slug: 'razole', nameEn: 'Razole Scenic Coconut Delta', nameTe: 'రాజోలు' },
    { slug: 'sakhinetipalle', nameEn: 'Sakhinetipalle', nameTe: 'సఖినేటిపల్లి' },
    { slug: 'sakinetipalli', nameEn: 'Sakinetipalli Antarvedi Sangamam', nameTe: 'సఖినేటిపల్లి (అంతర్వేది)' },
    { slug: 'uppalaguptam', nameEn: 'Uppalaguptam', nameTe: 'ఉప్పలగుప్తం' },
  ],
  'east-godavari': [
    { slug: 'anaparthi', nameEn: 'Anaparthi', nameTe: 'అనపర్తి' },
    { slug: 'biccavolu', nameEn: 'Biccavolu', nameTe: 'బిక్కవోలు' },
    { slug: 'bikkavolu', nameEn: 'Bikkavolu Historic Chalukya Temples', nameTe: 'బిక్కవోలు' },
    { slug: 'chagallu', nameEn: 'Chagallu Sugars', nameTe: 'చాగల్లు' },
    { slug: 'devarapalle-eg', nameEn: 'Devarapalle', nameTe: 'దేవరపల్లి' },
    { slug: 'gokavaram', nameEn: 'Gokavaram', nameTe: 'గోకవరం' },
    { slug: 'gopalapuram', nameEn: 'Gopalapuram', nameTe: 'గోపాలపురం' },
    { slug: 'kadiam', nameEn: 'Kadiam Flora Nurseries', nameTe: 'కడియం' },
    { slug: 'kapileswarapuram', nameEn: 'Kapileswarapuram', nameTe: 'కపిలేశ్వరపురం' },
    { slug: 'korukonda', nameEn: 'Korukonda Lakshmi Narasimha Swamy', nameTe: 'కోరుకొండ' },
    { slug: 'kovvur', nameEn: 'Kovvur Goshpada Kshetram', nameTe: 'కొవ్వూరు' },
    { slug: 'mandapeta', nameEn: 'Mandapeta', nameTe: 'మండపేట' },
    { slug: 'nallajerla', nameEn: 'Nallajerla', nameTe: 'నల్లజర్ల' },
    { slug: 'nidadavole', nameEn: 'Nidadavole Junction', nameTe: 'నిడదవోలు' },
    { slug: 'peravali', nameEn: 'Peravali', nameTe: 'పేరవలి' },
    { slug: 'rajahmundry-rural', nameEn: 'Rajahmundry Rural', nameTe: 'రాజమండ్రి రూరల్' },
    { slug: 'rajahmundry-urban', nameEn: 'Rajahmundry Urban', nameTe: 'రాజమండ్రి అర్బన్' },
    { slug: 'rajamahendravaram-rural', nameEn: 'Rajamahendravaram Rural', nameTe: 'రాజమండ్రి రూరల్' },
    { slug: 'rajamahendravaram-urban', nameEn: 'Rajamahendravaram Urban (Rajahmundry)', nameTe: 'రాజమండ్రి అర్బన్' },
    { slug: 'rajanagaram', nameEn: 'Rajanagaram Education Hub', nameTe: 'రాజానగరం' },
    { slug: 'rangampeta', nameEn: 'Rangampeta', nameTe: 'రంగంపేట' },
    { slug: 'rayavaram', nameEn: 'Rayavaram', nameTe: 'రాయవరం' },
    { slug: 'seethanagaram', nameEn: 'Seethanagaram', nameTe: 'సీతానగరం' },
    { slug: 'tallapudi', nameEn: 'Tallapudi', nameTe: 'తాళ్లపూడి' },
    { slug: 'undrajavaram', nameEn: 'Undrajavaram', nameTe: 'ఉండ్రాజవరం' },
  ],
  'west-godavari': [
    { slug: 'achanta', nameEn: 'Achanta Rameswara Swamy', nameTe: 'ఆచంట' },
    { slug: 'akividu', nameEn: 'Akividu Aquaculture Hub', nameTe: 'ఆకివీడు' },
    { slug: 'attili', nameEn: 'Attili', nameTe: 'అత్తిలి' },
    { slug: 'bhimavaram', nameEn: 'Bhimavaram Somarama Kshetram', nameTe: 'భీమవరం' },
    { slug: 'ganapavaram', nameEn: 'Ganapavaram', nameTe: 'గణపవరం' },
    { slug: 'iragavaram', nameEn: 'Iragavaram', nameTe: 'ఇరగవరం' },
    { slug: 'kalla', nameEn: 'Kalla', nameTe: 'కళ్ల' },
    { slug: 'mogalthur', nameEn: 'Mogalthur Heritage Town', nameTe: 'మొగల్తూరు' },
    { slug: 'narasapuram', nameEn: 'Narasapuram Lace & Port Town', nameTe: 'నర్సాపురం' },
    { slug: 'palacoderu', nameEn: 'Palacoderu', nameTe: 'పాలకోడేరు' },
    { slug: 'palakollu', nameEn: 'Palakollu Ksheerarama Kshetram', nameTe: 'పాలకొల్లు' },
    { slug: 'pentapadu', nameEn: 'Pentapadu', nameTe: 'పెంటపాడు' },
    { slug: 'penugonda', nameEn: 'Penugonda Vasavi Kanyaka Parameswari', nameTe: 'పెనుగొండ' },
    { slug: 'penumantra', nameEn: 'Penumantra', nameTe: 'పెనుమంత్ర' },
    { slug: 'poduru', nameEn: 'Poduru', nameTe: 'పోడూరు' },
    { slug: 'tadepalligudem', nameEn: 'Tadepalligudem NIT & Trade Center', nameTe: 'తాడేపల్లిగూడెం' },
    { slug: 'tanuku', nameEn: 'Tanuku Andhra Sugars Industrial Town', nameTe: 'తణుకు' },
    { slug: 'undi', nameEn: 'Undi', nameTe: 'ఉండి' },
    { slug: 'veeravasaram', nameEn: 'Veeravasaram', nameTe: 'వీరవాసరం' },
    { slug: 'yelamanchili-wg', nameEn: 'Yelamanchili', nameTe: 'యలమంచిలి' },
  ],
  'eluru': [
    { slug: 'agiripalli', nameEn: 'Agiripalli Shobhanachala Swamy', nameTe: 'ఆగిరిపల్లి' },
    { slug: 'bhimadole', nameEn: 'Bhimadole', nameTe: 'భీమడోలు' },
    { slug: 'buttayagudem', nameEn: 'Buttayagudem', nameTe: 'బుట్టాయగూడెం' },
    { slug: 'chatrai', nameEn: 'Chatrai', nameTe: 'చాట్రాయి' },
    { slug: 'chintalapudi', nameEn: 'Chintalapudi', nameTe: 'చింతలపూడి' },
    { slug: 'denduluru', nameEn: 'Denduluru', nameTe: 'దेंदులూరు' },
    { slug: 'dwarakatirumala', nameEn: 'Dwaraka Tirumala (Chinna Tirupati)', nameTe: 'ద్వారకా తిరుమల' },
    { slug: 'eluru-rural', nameEn: 'Eluru Rural', nameTe: 'ఏలూరు రూరల్' },
    { slug: 'eluru-urban', nameEn: 'Eluru Urban Carpet City', nameTe: 'ఏలూరు అర్బన్' },
    { slug: 'jangareddygudem', nameEn: 'Jangareddygudem Commercial Agency', nameTe: 'జంగారెడ్డిగూడెం' },
    { slug: 'jeelugumilli', nameEn: 'Jeelugumilli', nameTe: 'జీలుగుమిల్లి' },
    { slug: 'kaikaluru', nameEn: 'Kaikaluru Kolleru Sanctuary', nameTe: 'కైకలూరు' },
    { slug: 'kalidindi', nameEn: 'Kalidindi', nameTe: 'కలిదిండి' },
    { slug: 'kamavarapukota', nameEn: 'Kamavarapukota Guntupalli Caves', nameTe: 'కామవరపుకోట' },
    { slug: 'koyyalagudem', nameEn: 'Koyyalagudem', nameTe: 'కొయ్యలగూడెం' },
    { slug: 'kukunoor', nameEn: 'Kukunoor Tribal Region', nameTe: 'కుక్కునూరు' },
    { slug: 'lingapalem', nameEn: 'Lingapalem', nameTe: 'లింగపాలెం' },
    { slug: 'mandavalli', nameEn: 'Mandavalli', nameTe: 'మండవల్లి' },
    { slug: 'mudinepalle', nameEn: 'Mudinepalle', nameTe: 'ముదినేపల్లి' },
    { slug: 'musunuru', nameEn: 'Musunuru', nameTe: 'ముసునూరు' },
    { slug: 'nidamarru', nameEn: 'Nidamarru', nameTe: 'నిడమర్రు' },
    { slug: 'nuzvid', nameEn: 'Nuzvid Banganapalli Mango Capital', nameTe: 'నూజివీడు' },
    { slug: 'pedapadu', nameEn: 'Pedapadu', nameTe: 'పెదపాడు' },
    { slug: 'pedavegi', nameEn: 'Pedavegi Vengi Capital Heritage', nameTe: 'పెదవేగి' },
    { slug: 'polavaram', nameEn: 'Polavaram National Project Site', nameTe: 'పోలవరం' },
    { slug: 't-narasapuram', nameEn: 'T. Narasapuram', nameTe: 'టి. నరసాపురం' },
    { slug: 'unguturu', nameEn: 'Unguturu', nameTe: 'ఉంగుటూరు' },
    { slug: 'velairpadu', nameEn: 'Velairpadu Godavari Basin', nameTe: 'వేలేరుపాడు' },
  ],
  'krishna': [
    { slug: 'avanigadda', nameEn: 'Avanigadda Diviseema Gateway', nameTe: 'అవనిగడ్డ' },
    { slug: 'bantumilli', nameEn: 'Bantumilli', nameTe: 'బంటుమిల్లి' },
    { slug: 'bapulapadu', nameEn: 'Bapulapadu', nameTe: 'బాపులపాడు' },
    { slug: 'challapalli', nameEn: 'Challapalli Raja Palace', nameTe: 'చల్లపల్లి' },
    { slug: 'gannavaram', nameEn: 'Gannavaram', nameTe: 'గన్నవరం' },
    { slug: 'ghantasala', nameEn: 'Ghantasala Buddhist Heritage', nameTe: 'ఘంటసాల' },
    { slug: 'gudivada', nameEn: 'Gudivada Commercial Junction', nameTe: 'గుడివాడ' },
    { slug: 'gudlavalleru', nameEn: 'Gudlavalleru Engineering Hub', nameTe: 'గుడ్లవల్లేరు' },
    { slug: 'guduru-krishna', nameEn: 'Guduru', nameTe: 'గూడూరు' },
    { slug: 'kankipadu', nameEn: 'Kankipadu', nameTe: 'కంకిపాడు' },
    { slug: 'koduru-krishna', nameEn: 'Koduru Beach', nameTe: 'కోడూరు' },
    { slug: 'kruthivennu', nameEn: 'Kruthivennu', nameTe: 'కృతివెన్ను' },
    { slug: 'machilipatnam-urban', nameEn: 'Machilipatnam Coastal Port City', nameTe: 'మచిలీపట్నం అర్బన్' },
    { slug: 'machilipatnam-rural', nameEn: 'Machilipatnam Rural', nameTe: 'మచిలీపట్నం రూరల్' },
    { slug: 'mopidevi', nameEn: 'Mopidevi', nameTe: 'మోపిదేవి' },
    { slug: 'movva', nameEn: 'Movva Kshetrayya Kshetram', nameTe: 'మొవ్వ' },
    { slug: 'nagayalanka', nameEn: 'Nagayalanka Light House Delta', nameTe: 'నాగాయలంక' },
    { slug: 'nandivada', nameEn: 'Nandivada', nameTe: 'నందివాడ' },
    { slug: 'pamarru', nameEn: 'Pamarru', nameTe: 'పామర్రు' },
    { slug: 'pamidimukkala', nameEn: 'Pamidimukkala', nameTe: 'పామిడిముక్కల' },
    { slug: 'pedana', nameEn: 'Pedana Kalamkari & Handlooms', nameTe: 'పెడన' },
    { slug: 'pedaparupudi', nameEn: 'Pedaparupudi', nameTe: 'పెదపారుపూడి' },
    { slug: 'penamaluru', nameEn: 'Penamaluru', nameTe: 'పెనమలూరు' },
    { slug: 'thotlavalluru', nameEn: 'Thotlavalluru', nameTe: 'తోట్లవల్లూరు' },
    { slug: 'unguturu', nameEn: 'Unguturu', nameTe: 'ఉంగుటూరు' },
    { slug: 'vuyyuru', nameEn: 'Vuyyuru Sugar Factory City', nameTe: 'వుయ్యూరు' },
  ],
  'vijayawada-ntr': [
    { slug: 'a-konduru', nameEn: 'A. Konduru', nameTe: 'ఎ. కొండూరు' },
    { slug: 'chandarlapadu', nameEn: 'Chandarlapadu', nameTe: 'చందర్లపాడు' },
    { slug: 'g-konduru', nameEn: 'G. Konduru', nameTe: 'జి. కొండూరు' },
    { slug: 'gampalagudem', nameEn: 'Gampalagudem', nameTe: 'గంపలగూడెం' },
    { slug: 'ibrahimpatnam-ntr', nameEn: 'Ibrahimpatnam (Dr. NTTPS Thermal)', nameTe: 'ఇబ్రహీంపట్నం' },
    { slug: 'jaggaiahpet', nameEn: 'Jaggaiahpet Cement Belt', nameTe: 'జగ్గయ్యపేట' },
    { slug: 'jaggayyapeta', nameEn: 'Jaggayyapeta', nameTe: 'జగ్గయ్యపేట' },
    { slug: 'kanchikacherla', nameEn: 'Kanchikacherla', nameTe: 'కంచికచర్ల' },
    { slug: 'kondapalli', nameEn: 'Kondapalli Fort & Wooden Toys', nameTe: 'కొండపల్లి' },
    { slug: 'mylavaram', nameEn: 'Mylavaram', nameTe: 'మైలవరం' },
    { slug: 'nandigama', nameEn: 'Nandigama Commercial Town', nameTe: 'నందిగామ' },
    { slug: 'penuganchiprolu', nameEn: 'Penuganchiprolu Sri Tirupatamma Temple', nameTe: 'పెనుగంచిప్రోలు' },
    { slug: 'reddigudem', nameEn: 'Reddigudem', nameTe: 'రెడ్డిగూడెం' },
    { slug: 'tiruvuru', nameEn: 'Tiruvuru Mango Belt', nameTe: 'తిరువూరు' },
    { slug: 'vatsavai', nameEn: 'Vatsavai', nameTe: 'వత్సవాయి' },
    { slug: 'veerullapadu', nameEn: 'Veerullapadu', nameTe: 'వీరుళ్లపాడు' },
    { slug: 'vijayawada-central', nameEn: 'Vijayawada Central / Besant Road', nameTe: 'విజయవాడ సెంట్రల్' },
    { slug: 'vijayawada-east', nameEn: 'Vijayawada East / Benz Circle', nameTe: 'విజయవాడ ఈస్ట్' },
    { slug: 'vijayawada-north', nameEn: 'Vijayawada North / Gunadala Mary Matha', nameTe: 'విజయవాడ నార్త్' },
    { slug: 'vijayawada-rural', nameEn: 'Vijayawada Rural', nameTe: 'విజయవాడ రూరల్' },
    { slug: 'vijayawada-west', nameEn: 'Vijayawada West / Kanaka Durga Temple', nameTe: 'విజయవాడ వెస్ట్ (దుర్గ గుడి)' },
    { slug: 'vissannapeta', nameEn: 'Vissannapeta', nameTe: 'విస్సన్నపేట' },
  ],
  'guntur': [
    { slug: 'chebrolu', nameEn: 'Chebrolu Historic Chaturmukha Brahma', nameTe: 'చేబ్రోలు' },
    { slug: 'duggirala', nameEn: 'Duggirala World Turmeric Market', nameTe: 'దుగ్గిరాల' },
    { slug: 'guntur-east', nameEn: 'Guntur East / Mirchi Yard', nameTe: 'గుంటూరు ఈస్ట్ (మిర్చి యార్డ్)' },
    { slug: 'guntur-rural', nameEn: 'Guntur Rural', nameTe: 'గుంటూరు రూరల్' },
    { slug: 'guntur-urban', nameEn: 'Guntur Urban / Brodipet / Arundelpet', nameTe: 'గుంటూరు అర్బన్' },
    { slug: 'guntur-west', nameEn: 'Guntur West', nameTe: 'గుంటూరు పశ్చిమ' },
    { slug: 'kakumanu', nameEn: 'Kakumanu', nameTe: 'కాకుమాను' },
    { slug: 'kollipara', nameEn: 'Kollipara', nameTe: 'కొల్లిపర' },
    { slug: 'mangalagiri', nameEn: 'Mangalagiri Panakala Narasimha / AIIMS', nameTe: 'మంగళగిరి' },
    { slug: 'medikonduru', nameEn: 'Medikonduru', nameTe: 'మేడికొండూరు' },
    { slug: 'pedakakani', nameEn: 'Pedakakani Malleswara Temple', nameTe: 'పెదకాకాని' },
    { slug: 'pedanandipadu', nameEn: 'Pedanandipadu', nameTe: 'పెదనందిపాడు' },
    { slug: 'phirangipuram', nameEn: 'Phirangipuram', nameTe: 'ఫిరంగిపురం' },
    { slug: 'ponnur', nameEn: 'Ponnur Sakshi Ganapathi', nameTe: 'పొన్నూరు' },
    { slug: 'prathipadu-gnt', nameEn: 'Prathipadu', nameTe: 'ప్రత్తిపాడు' },
    { slug: 'tadepalli', nameEn: 'Tadepalli Capital Zone', nameTe: 'తాడేపల్లి' },
    { slug: 'tadikonda', nameEn: 'Tadikonda', nameTe: 'తాడికొండ' },
    { slug: 'tenali', nameEn: 'Tenali (Andhra Paris Cultural Capital)', nameTe: 'తెనాలి' },
    { slug: 'thullur', nameEn: 'Thullur (Amaravati Capital Seed Access)', nameTe: 'తుళ్లూరు (అమరావతి)' },
    { slug: 'vatticherukuru', nameEn: 'Vatticherukuru', nameTe: 'వట్టిచెరుకూరు' },
  ],
  'palnadu': [
    { slug: 'amaravathi-heritage', nameEn: 'Amaravathi Amaralingeswara & Mahastupa', nameTe: 'అమరావతి' },
    { slug: 'atchampeta', nameEn: 'Atchampeta', nameTe: 'అచ్చంపేట' },
    { slug: 'bellamkonda', nameEn: 'Bellamkonda Fort', nameTe: 'బెల్లంకొండ' },
    { slug: 'bollapalle', nameEn: 'Bollapalle', nameTe: 'బొల్లాపల్లి' },
    { slug: 'chilakaluripet', nameEn: 'Chilakaluripet Cotton & NH16', nameTe: 'చిలకలూరిపేట' },
    { slug: 'dachepalle', nameEn: 'Dachepalle', nameTe: 'దాచేపల్లి' },
    { slug: 'durgi', nameEn: 'Durgi', nameTe: 'దుర్గి' },
    { slug: 'edlapadu', nameEn: 'Edlapadu', nameTe: 'యడ్లపాడు' },
    { slug: 'gurazala', nameEn: 'Gurazala Palnadu Division', nameTe: 'గురజాల' },
    { slug: 'ipuru', nameEn: 'Ipuru', nameTe: 'ఈపూరు' },
    { slug: 'karempudi', nameEn: 'Karempudi Palnadu Heroes Temple', nameTe: 'కారెంపూడి' },
    { slug: 'krosuru', nameEn: 'Krosuru', nameTe: 'క్రోసూరు' },
    { slug: 'machavaram', nameEn: 'Machavaram', nameTe: 'మాచవరం' },
    { slug: 'macherla', nameEn: 'Macherla Chennakesava Swamy', nameTe: 'మాచర్ల' },
    { slug: 'muppalla', nameEn: 'Muppalla', nameTe: 'ముప్పాళ్ల' },
    { slug: 'nadendla', nameEn: 'Nadendla', nameTe: 'నాదెండ్ల' },
    { slug: 'narasaraopet', nameEn: 'Narasaraopet Kotappakonda Gateway', nameTe: 'నరసరావుపేట' },
    { slug: 'nekarikallu', nameEn: 'Nekarikallu', nameTe: 'నెకరికల్లు' },
    { slug: 'nuzendla', nameEn: 'Nuzendla', nameTe: 'నూజెండ్ల' },
    { slug: 'pedakurapadu', nameEn: 'Pedakurapadu', nameTe: 'పెదకూరపాడు' },
    { slug: 'piduguralla', nameEn: 'Piduguralla White Limestone City', nameTe: 'పిడుగురాళ్ల' },
    { slug: 'rajupalem', nameEn: 'Rajupalem', nameTe: 'రాజుపాలెం' },
    { slug: 'rentachintala', nameEn: 'Rentachintala', nameTe: 'రెంటచింతల' },
    { slug: 'rompicherla-pln', nameEn: 'Rompicherla', nameTe: 'రొంపిచర్ల' },
    { slug: 'sattenapalle', nameEn: 'Sattenapalle', nameTe: 'సత్తెనపల్లి' },
    { slug: 'savalyapuram', nameEn: 'Savalyapuram', nameTe: 'శావల్యాపురం' },
    { slug: 'veldurthi', nameEn: 'Veldurthi', nameTe: 'వెల్దుర్తి' },
    { slug: 'vinukonda', nameEn: 'Vinukonda Hill Fort Town', nameTe: 'వినుకొండ' },
  ],
  'bapatla': [
    { slug: 'addanki', nameEn: 'Addanki Historic Inscription Town', nameTe: 'అద్దంకి' },
    { slug: 'amruthalur', nameEn: 'Amruthalur', nameTe: 'అమృతలూరు' },
    { slug: 'ballikurava', nameEn: 'Ballikurava', nameTe: 'బల్లికురవ' },
    { slug: 'bapatla-town', nameEn: 'Bapatla Suryalanka Beach & Agriculture College', nameTe: 'బాపట్ల' },
    { slug: 'bhattiprolu', nameEn: 'Bhattiprolu Ancient Buddhist Stupa', nameTe: 'భట్టిప్రోలు' },
    { slug: 'cherukupalle', nameEn: 'Cherukupalle', nameTe: 'చెరుకుపల్లి' },
    { slug: 'chinaganjam', nameEn: 'Chinaganjam Salt Pans', nameTe: 'చినగంజాం' },
    { slug: 'chirala', nameEn: 'Chirala Handloom & Textile City', nameTe: 'చీరాల' },
    { slug: 'inkollu', nameEn: 'Inkollu', nameTe: 'ఇంకొల్లు' },
    { slug: 'j-panguluru', nameEn: 'J. Panguluru', nameTe: 'జనకవరం పంగులూరు' },
    { slug: 'karamchedu', nameEn: 'Karamchedu', nameTe: 'కారంచేడు' },
    { slug: 'karlapalem', nameEn: 'Karlapalem', nameTe: 'కార్లపాలెం' },
    { slug: 'kollur', nameEn: 'Kollur', nameTe: 'కొల్లూరు' },
    { slug: 'korisapadu', nameEn: 'Korisapadu', nameTe: 'కోరిశపాడు' },
    { slug: 'martur', nameEn: 'Martur Granite Hub', nameTe: 'మార్టూరు' },
    { slug: 'nagaram', nameEn: 'Nagaram', nameTe: 'నగరం' },
    { slug: 'nizampatnam', nameEn: 'Nizampatnam Fishing Port & Delta', nameTe: 'నిజాంపట్నం' },
    { slug: 'parchur', nameEn: 'Parchur', nameTe: 'పర్చూరు' },
    { slug: 'pittalavanipalem', nameEn: 'Pittalavanipalem', nameTe: 'పిట్టలవానిపాలెం' },
    { slug: 'repalle', nameEn: 'Repalle Coastal Terminal', nameTe: 'రేపల్లె' },
    { slug: 'santhamaguluru', nameEn: 'Santhamaguluru', nameTe: 'సంతమాగులూరు' },
    { slug: 'tsundur', nameEn: 'Tsundur', nameTe: 'చుండూరు' },
    { slug: 'vemuru', nameEn: 'Vemuru', nameTe: 'వేమూరు' },
    { slug: 'vetapalem', nameEn: 'Vetapalem Saraswatha Nikethanam', nameTe: 'వేటపాలెం' },
    { slug: 'yeddanapudi', nameEn: 'Yeddanapudi', nameTe: 'యద్దనపూడి' },
  ],
  'prakasam': [
    { slug: 'addanki', nameEn: 'Addanki', nameTe: 'అద్దంకి' },
    { slug: 'ardhaveedu', nameEn: 'Ardhaveedu', nameTe: 'అర్థవీడు' },
    { slug: 'ballikurava', nameEn: 'Ballikurava', nameTe: 'బల్లికురవ' },
    { slug: 'bestawaripeta', nameEn: 'Bestawaripeta', nameTe: 'బెస్తవారిపేట' },
    { slug: 'besthavaripeta', nameEn: 'Besthavaripeta', nameTe: 'బెస్తవారిపేట' },
    { slug: 'cs-puram', nameEn: 'C.S. Puram', nameTe: 'సి.ఎస్. పురం' },
    { slug: 'chandra-sekhara-puram', nameEn: 'Chandra Sekhara Puram', nameTe: 'చంద్రశేఖరపురం' },
    { slug: 'chimakurthi', nameEn: 'Chimakurthi', nameTe: 'చీమకుర్తి' },
    { slug: 'chimakurthy', nameEn: 'Chimakurthy Galaxy Black Granite', nameTe: 'చీమకుర్తి' },
    { slug: 'cumbum', nameEn: 'Cumbum Historic Ancient Lake', nameTe: 'కంబం' },
    { slug: 'darsi', nameEn: 'Darsi', nameTe: 'దర్శి' },
    { slug: 'donakonda', nameEn: 'Donakonda Industrial Belt', nameTe: 'దొనకొండ' },
    { slug: 'dornala', nameEn: 'Dornala', nameTe: 'దోర్నాల' },
    { slug: 'giddalur', nameEn: 'Giddalur Nallamala Foothills', nameTe: 'గిద్దలూరు' },
    { slug: 'gudluru', nameEn: 'Gudluru', nameTe: 'గుడ్లూరు' },
    { slug: 'hanumanthuni-padu', nameEn: 'Hanumanthuni Padu', nameTe: 'హనుమంతునిపాడు' },
    { slug: 'j-panguluru', nameEn: 'J. Panguluru', nameTe: 'జనకవరం పంగులూరు' },
    { slug: 'kandukur', nameEn: 'Kandukur Commercial Division', nameTe: 'కందుకూరు' },
    { slug: 'kandukuru', nameEn: 'Kandukuru', nameTe: 'కందుకూరు' },
    { slug: 'kanigiri', nameEn: 'Kanigiri', nameTe: 'కనిగిరి' },
    { slug: 'komarolu', nameEn: 'Komarolu', nameTe: 'కొమరోలు' },
    { slug: 'konakanamitla', nameEn: 'Konakanamitla', nameTe: 'కొనకనమిట్ల' },
    { slug: 'kondapi', nameEn: 'Kondapi', nameTe: 'కొండపి' },
    { slug: 'korisapadu', nameEn: 'Korisapadu', nameTe: 'కోరిశపాడు' },
    { slug: 'kothapatnam', nameEn: 'Kothapatnam Sea Coast', nameTe: 'కొత్తపట్నం' },
    { slug: 'kurichedu', nameEn: 'Kurichedu', nameTe: 'కురిచేడు' },
    { slug: 'lingasamudram', nameEn: 'Lingasamudram', nameTe: 'లింగసముద్రం' },
    { slug: 'maddipadu', nameEn: 'Maddipadu', nameTe: 'మద్దిపాడు' },
    { slug: 'markapur', nameEn: 'Markapur Slate Industry', nameTe: 'మార్కాపురం' },
    { slug: 'markapuram', nameEn: 'Markapuram', nameTe: 'మార్కాపురం' },
    { slug: 'marripudi', nameEn: 'Marripudi', nameTe: 'మర్రిపూడి' },
    { slug: 'mundlamuru', nameEn: 'Mundlamuru', nameTe: 'ముండ్లమూరు' },
    { slug: 'naguluppalapadu', nameEn: 'Naguluppalapadu', nameTe: 'నాగులుప్పలపాడు' },
    { slug: 'ongole-urban', nameEn: 'Ongole Breed Heritage City', nameTe: 'ఒంగోలు అర్బన్' },
    { slug: 'ongole-rural', nameEn: 'Ongole Rural', nameTe: 'ఒంగోలు రూరల్' },
    { slug: 'ongole-urban-mandal', nameEn: 'Ongole Urban', nameTe: 'ఒంగోలు అర్బన్' },
    { slug: 'pamuru', nameEn: 'Pamuru', nameTe: 'పామూరు' },
    { slug: 'pedaaraveedu', nameEn: 'Peda Araveedu', nameTe: 'పెద్దారవీడు' },
    { slug: 'pedacherlo-palle', nameEn: 'Pedacherlo Palle', nameTe: 'పెదచెర్లోపల్లె' },
    { slug: 'podili', nameEn: 'Podili', nameTe: 'పొదిలి' },
    { slug: 'ponnaluru', nameEn: 'Ponnaluru', nameTe: 'పొన్నలూరు' },
    { slug: 'pullalacheruvu', nameEn: 'Pullalacheruvu', nameTe: 'పుల్లలచెరువు' },
    { slug: 'racherla', nameEn: 'Racherla', nameTe: 'రాచర్ల' },
    { slug: 'santhamaguluru', nameEn: 'Santhamaguluru', nameTe: 'సంతమాగులూరు' },
    { slug: 'santhanuthalapadu', nameEn: 'Santhanuthalapadu', nameTe: 'సంతనూతలపాడు' },
    { slug: 'singarayakonda', nameEn: 'Singarayakonda Varaha Lakshmi Narasimha', nameTe: 'సింగరాయకొండ' },
    { slug: 'tangutur', nameEn: 'Tangutur', nameTe: 'టంగుటూరు' },
    { slug: 'tarlupadu', nameEn: 'Tarlupadu', nameTe: 'తర్లుపాడు' },
    { slug: 'thallur', nameEn: 'Thallur', nameTe: 'తాళ్లూరు' },
    { slug: 'tripuranthakam', nameEn: 'Tripuranthakam Srisailam Eastern Gateway', nameTe: 'త్రిపురాంతకం' },
    { slug: 'ulavapadu', nameEn: 'Ulavapadu Export Banganapalli', nameTe: 'ఉలవపాడు' },
    { slug: 'veligandla', nameEn: 'Veligandla', nameTe: 'వెలిగండ్ల' },
    { slug: 'voletivaripalem', nameEn: 'Voletivaripalem', nameTe: 'వోలేటివారిపాలెం' },
    { slug: 'yerragondapalem', nameEn: 'Yerragondapalem', nameTe: 'యర్రగొండపాలెం' },
    { slug: 'zarugumilli', nameEn: 'Zarugumilli', nameTe: 'జరుగుమల్లి' },
  ],
  'sri-potti-sriramulu-nellore': [
    { slug: 'allur', nameEn: 'Allur', nameTe: 'అల్లూరు' },
    { slug: 'anantasagaram', nameEn: 'Anantasagaram Somashila Project', nameTe: 'అనంతసాగరం (సోమశిల)' },
    { slug: 'ananthasagaram', nameEn: 'Ananthasagaram', nameTe: 'అనంతసాగరం' },
    { slug: 'anumasamudrampeta', nameEn: 'Anumasamudrampeta', nameTe: 'అనుమసముద్రంపేట' },
    { slug: 'atmakur-nlr', nameEn: 'Atmakur Somashila Gateway', nameTe: 'ఆత్మకూరు' },
    { slug: 'bogole', nameEn: 'Bogole / Bitragunta Railway Yard', nameTe: 'బోగోలు' },
    { slug: 'bogolu', nameEn: 'Bogolu', nameTe: 'బోగోలు' },
    { slug: 'buchireddypalem', nameEn: 'Buchireddypalem Jonnawada Kamakshi', nameTe: 'బుచ్చిరెడ్డిపాలెం (జొన్నవాడ)' },
    { slug: 'chejerla', nameEn: 'Chejerla', nameTe: 'చేజర్ల' },
    { slug: 'chillakur', nameEn: 'Chillakur', nameTe: 'చిల్లకూరు' },
    { slug: 'dagadarthi', nameEn: 'Dagadarthi Non-Metro Airport Site', nameTe: 'దగదర్తి' },
    { slug: 'duttalur', nameEn: 'Duttalur', nameTe: 'దుత్తలూరు' },
    { slug: 'indukurpet', nameEn: 'Indukurpet Coastal Delta', nameTe: 'ఇందుకూరుపేట' },
    { slug: 'jaladanki', nameEn: 'Jaladanki', nameTe: 'జలదంకి' },
    { slug: 'kaligiri', nameEn: 'Kaligiri', nameTe: 'కలిగిరి' },
    { slug: 'kaluvoya', nameEn: 'Kaluvoya', nameTe: 'కలువోయ' },
    { slug: 'kavali', nameEn: 'Kavali Education & Trade City', nameTe: 'కావలి' },
    { slug: 'kodavalur', nameEn: 'Kodavalur', nameTe: 'కొడవలూరు' },
    { slug: 'kondapuram-nlr', nameEn: 'Kondapuram', nameTe: 'కొండాపురం' },
    { slug: 'kota', nameEn: 'Kota', nameTe: 'కోట' },
    { slug: 'kovur-nlr', nameEn: 'Kovur Penna River Fertile Belt', nameTe: 'కోవూరు' },
    { slug: 'manubolu', nameEn: 'Manubolu', nameTe: 'మనుబోలు' },
    { slug: 'marripadu', nameEn: 'Marripadu', nameTe: 'మర్రిపాడు' },
    { slug: 'muthukur', nameEn: 'Muthukur Deep Sea Port', nameTe: 'ముత్తుకూరు (కృష్ణపట్నం పోర్ట్)' },
    { slug: 'muttukuru', nameEn: 'Muttukuru', nameTe: 'ముత్తుకూరు' },
    { slug: 'nellore-rural', nameEn: 'Nellore Rural', nameTe: 'నెల్లూరు రూరల్' },
    { slug: 'nellore-urban', nameEn: 'Nellore Smart City / Ranganatha Swamy', nameTe: 'నెల్లూరు అర్బన్' },
    { slug: 'nellore-urban-mandal', nameEn: 'Nellore Urban', nameTe: 'నెల్లూరు అర్బన్' },
    { slug: 'podalakur', nameEn: 'Podalakur', nameTe: 'పొదలకూరు' },
    { slug: 'rapur', nameEn: 'Rapur Penchalakona Kshetram', nameTe: 'రాపూరు (పెంచలకోన)' },
    { slug: 'rapuru', nameEn: 'Rapuru', nameTe: 'రాపూరు' },
    { slug: 'saidapuramu', nameEn: 'Saidapuramu', nameTe: 'సైదాపురం' },
    { slug: 'sangam', nameEn: 'Sangam Triveni Sangamam', nameTe: 'సంగం' },
    { slug: 'sitaramapuram', nameEn: 'Sitaramapuram', nameTe: 'సీతారామపురం' },
    { slug: 'sitarampuramu', nameEn: 'Sitarampuramu', nameTe: 'సీతారాంపురం' },
    { slug: 'thotapalligudur', nameEn: 'Thotapalligudur', nameTe: 'తోటపల్లిగూడూరు' },
    { slug: 'udayagiri', nameEn: 'Udayagiri Hill Fort Heritage', nameTe: 'ఉదయగిరి' },
    { slug: 'varikuntapadu', nameEn: 'Varikuntapadu', nameTe: 'వరికుంటపాడు' },
    { slug: 'venkatachalam', nameEn: 'Venkatachalam', nameTe: 'వెంకటాచలం' },
    { slug: 'vidavalur', nameEn: 'Vidavalur', nameTe: 'విడవలూరు' },
    { slug: 'vinjamur', nameEn: 'Vinjamur', nameTe: 'వింజమూరు' },
  ],
  'kurnool': [
    { slug: 'adoni-urban', nameEn: 'Adoni Cotton & Grain Trade Hub', nameTe: 'ఆదోని' },
    { slug: 'adoni-rural', nameEn: 'Adoni Rural', nameTe: 'ఆదోని' },
    { slug: 'adoni-urban-mandal', nameEn: 'Adoni Urban', nameTe: 'ఆదోని అర్బన్' },
    { slug: 'alur', nameEn: 'Alur', nameTe: 'ఆలూరు' },
    { slug: 'aspari', nameEn: 'Aspari', nameTe: 'ఆస్పరి' },
    { slug: 'c-belagal', nameEn: 'C. Belagal', nameTe: 'సి. బెళగల్' },
    { slug: 'chippagiri', nameEn: 'Chippagiri', nameTe: 'చిప్పగిరి' },
    { slug: 'devanakonda', nameEn: 'Devanakonda', nameTe: 'దేవనకొండ' },
    { slug: 'dhone', nameEn: 'Dhone / Dronachalam Mining Hub', nameTe: 'డోన్' },
    { slug: 'gonagandla', nameEn: 'Gonagandla', nameTe: 'గోనెగండ్ల' },
    { slug: 'gonegandla', nameEn: 'Gonegandla', nameTe: 'గోనెగండ్ల' },
    { slug: 'gudur-knl', nameEn: 'Gudur', nameTe: 'గూడూరు' },
    { slug: 'halaharvi', nameEn: 'Halaharvi', nameTe: 'హాలహర్వి' },
    { slug: 'holagunda', nameEn: 'Holagunda', nameTe: 'హొళగుంద' },
    { slug: 'kallur-knl', nameEn: 'Kallur Industrial Estate', nameTe: 'కల్లూరు' },
    { slug: 'kodumur', nameEn: 'Kodumur', nameTe: 'కోడుమూరు' },
    { slug: 'kosigi', nameEn: 'Kosigi', nameTe: 'కోసిగి' },
    { slug: 'kowthalam', nameEn: 'Kowthalam', nameTe: 'కౌతాళం' },
    { slug: 'krishnagiri-knl', nameEn: 'Krishnagiri', nameTe: 'కృష్ణగిరి' },
    { slug: 'kurnool-urban', nameEn: 'Kurnool Historic Konda Reddy Buruju City', nameTe: 'కర్నూలు అర్బన్' },
    { slug: 'kurnool-rural', nameEn: 'Kurnool Rural', nameTe: 'కర్నూలు రూరల్' },
    { slug: 'kurnool-urban-mandal', nameEn: 'Kurnool Urban', nameTe: 'కర్నూలు అర్బన్' },
    { slug: 'maddikera', nameEn: 'Maddikera East', nameTe: 'మద్దికెర' },
    { slug: 'mantralayam', nameEn: 'Mantralayam Sri Raghavendra Swamy Mutt', nameTe: 'మంత్రాలయం' },
    { slug: 'nandavaram', nameEn: 'Nandavaram Sri Chowdeshwari Devi', nameTe: 'నందవరం' },
    { slug: 'orvakal', nameEn: 'Orvakal Rock Garden & Airport Corridor', nameTe: 'ఓర్వకల్లు' },
    { slug: 'pattikonda', nameEn: 'Pattikonda', nameTe: 'పత్తికొండ' },
    { slug: 'peapully', nameEn: 'Peapully Custard Apples', nameTe: 'ప్యాపిలి' },
    { slug: 'peddakadubur', nameEn: 'Pedda Kadubur', nameTe: 'పెద్దకడబూరు' },
    { slug: 'tuggali', nameEn: 'Tuggali Jonnagiri Gold & Diamond Fields', nameTe: 'తుగ్గలి' },
    { slug: 'veldurthi', nameEn: 'Veldurthi', nameTe: 'వెల్దుర్తి' },
    { slug: 'yemmiganur', nameEn: 'Yemmiganur Handloom Weavers City', nameTe: 'ఎమ్మిగనూరు' },
  ],
  'nandyal': [
    { slug: 'allagadda', nameEn: 'Allagadda World Sculpture Center', nameTe: 'ఆళ్లగడ్డ' },
    { slug: 'atmakur-ndl', nameEn: 'Atmakur Nallamala Gateway', nameTe: 'ఆత్మకూరు' },
    { slug: 'banaganapalle', nameEn: 'Banaganapalle Mangoes & Nawab Palace', nameTe: 'బనగానపల్లె' },
    { slug: 'bandiatmakur', nameEn: 'Bandi Atmakur', nameTe: 'బండి ఆత్మకూరు' },
    { slug: 'bethamcherla', nameEn: 'Bethamcherla Natural Flooring Slabs', nameTe: 'బెతంచెర్ల' },
    { slug: 'chagalamarri', nameEn: 'Chagalamarri', nameTe: 'చాగలమర్రి' },
    { slug: 'dhone', nameEn: 'Dhone', nameTe: 'డోన్' },
    { slug: 'dornipadu', nameEn: 'Dornipadu', nameTe: 'దొర్నిపాడు' },
    { slug: 'gadivemula', nameEn: 'Gadivemula', nameTe: 'గడివేముల' },
    { slug: 'gospadu', nameEn: 'Gospadu', nameTe: 'గోస్పాడు' },
    { slug: 'jupadu-bungalow', nameEn: 'Jupadu Bungalow', nameTe: 'జూపాడు బంగళా' },
    { slug: 'koilkuntla', nameEn: 'Koilkuntla', nameTe: 'కోవెలకుంట్ల' },
    { slug: 'kolimigundla', nameEn: 'Kolimigundla Belum Caves', nameTe: 'కొలిమిగుండ్ల (బెలూం గుహలు)' },
    { slug: 'kothapalle-ndl', nameEn: 'Kothapalle', nameTe: 'కొత్తపల్లె' },
    { slug: 'mahanandi', nameEn: 'Mahanandi Pushkarini Kshetram', nameTe: 'మహానంది' },
    { slug: 'midthur', nameEn: 'Midthur', nameTe: 'మిడ్తూరు' },
    { slug: 'nandikotkur', nameEn: 'Nandikotkur', nameTe: 'నందికొట్కూరు' },
    { slug: 'nandyal-urban', nameEn: 'Nandyal Nava Nandi Kshetram', nameTe: 'నంద్యాల అర్బన్' },
    { slug: 'nandyal-rural', nameEn: 'Nandyal Rural', nameTe: 'నంద్యాల రూరల్' },
    { slug: 'nandyal-urban-mandal', nameEn: 'Nandyal Urban', nameTe: 'నంద్యాల అర్బన్' },
    { slug: 'owk', nameEn: 'Owk Reservoir & Historic Palaces', nameTe: 'ఔకు' },
    { slug: 'pagidyala', nameEn: 'Pagidyala', nameTe: 'పగిడ్యాల' },
    { slug: 'pamulapadu', nameEn: 'Pamulapadu', nameTe: 'పాములపాడు' },
    { slug: 'panyam', nameEn: 'Panyam Cement Belt', nameTe: 'పాణ్యం' },
    { slug: 'peapally', nameEn: 'Peapally', nameTe: 'ప్యాపిలి' },
    { slug: 'rudravaram', nameEn: 'Rudravaram', nameTe: 'రుద్రవరం' },
    { slug: 'sanjamala', nameEn: 'Sanjamala', nameTe: 'సంజామల' },
    { slug: 'sirivella', nameEn: 'Sirivella', nameTe: 'శిరివెళ్ల' },
    { slug: 'sirvella', nameEn: 'Sirvella', nameTe: 'శిరివెళ్ల' },
    { slug: 'srisailam', nameEn: 'Srisailam Mallikarjuna Bhramaramba Kshetram', nameTe: 'శ్రీశైలం' },
    { slug: 'uyyalawada', nameEn: 'Uyyalawada First Freedom Fighter Land', nameTe: 'ఉయ్యాలవాడ' },
    { slug: 'velgodu', nameEn: 'Velgodu Telugu Ganga Reservoir', nameTe: 'వెలుగోడు' },
  ],
  'anantapur': [
    { slug: 'anantapur-rural', nameEn: 'Anantapur Rural', nameTe: 'అనంతపురం రూరల్' },
    { slug: 'anantapur-urban', nameEn: 'Anantapur Urban / Historic Tower', nameTe: 'అనంతపురం అర్బన్' },
    { slug: 'anantapuramu', nameEn: 'Anantapuramu', nameTe: 'అనంతపురం' },
    { slug: 'atmakur-atp', nameEn: 'Atmakur', nameTe: 'ఆత్మకూరు' },
    { slug: 'bk-samudram', nameEn: 'B.K. Samudram', nameTe: 'బికె సముద్రం' },
    { slug: 'beluguppa', nameEn: 'Beluguppa', nameTe: 'బెలుగుప్ప' },
    { slug: 'bommanahal', nameEn: 'Bommanahal', nameTe: 'బొమ్మనహాళ్' },
    { slug: 'brahmasamudram', nameEn: 'Brahmasamudram', nameTe: 'బ్రహ్మసముద్రం' },
    { slug: 'bukkaraya-samudram', nameEn: 'Bukkaraya Samudram', nameTe: 'బుక్కరాయసముద్రం' },
    { slug: 'd-hirehal', nameEn: 'D. Hirehal Iron Belt', nameTe: 'డి. హిరేహాళ్' },
    { slug: 'garladinne', nameEn: 'Garladinne', nameTe: 'గార్లదిన్నె' },
    { slug: 'gooty', nameEn: 'Gooty Historic Hill Citadel', nameTe: 'గుత్తి' },
    { slug: 'gummagatta', nameEn: 'Gummagatta', nameTe: 'గుమ్మఘట్ట' },
    { slug: 'guntakal', nameEn: 'Guntakal Railway Division Hub', nameTe: 'గుంతకల్లు' },
    { slug: 'kalyandurg', nameEn: 'Kalyandurg Pomegranate Capital', nameTe: 'కళ్యాణదుర్గం' },
    { slug: 'kambadur', nameEn: 'Kambadur Ancient Mallikarjuna Temple', nameTe: 'కంబదూరు' },
    { slug: 'kanekal', nameEn: 'Kanekal', nameTe: 'కణేకల్లు' },
    { slug: 'kudair', nameEn: 'Kudair', nameTe: 'కూడేరు' },
    { slug: 'kundurpi', nameEn: 'Kundurpi Fort', nameTe: 'కుందుర్పి' },
    { slug: 'narpala', nameEn: 'Narpala', nameTe: 'నార్పల' },
    { slug: 'pamidi', nameEn: 'Pamidi Penna River Town', nameTe: 'పామిడి' },
    { slug: 'peddapappur', nameEn: 'Peddapappur', nameTe: 'పెద్దపప్పూరు' },
    { slug: 'peddavadugur', nameEn: 'Peddavadugur', nameTe: 'పెద్దవడుగూరు' },
    { slug: 'putlur', nameEn: 'Putlur', nameTe: 'పుట్లూరు' },
    { slug: 'raptadu', nameEn: 'Raptadu', nameTe: 'రాప్తాడు' },
    { slug: 'rayadurg', nameEn: 'Rayadurg Hilltop Fort & Garment Industry', nameTe: 'రాయదుర్గం' },
    { slug: 'settur', nameEn: 'Settur', nameTe: 'శెట్టూరు' },
    { slug: 'singanamala', nameEn: 'Singanamala Large Fresh Lake', nameTe: 'సింగనమల' },
    { slug: 'tadipatri', nameEn: 'Tadipatri Bugga Ramalingeswara Temple', nameTe: 'తాడిపత్రి' },
    { slug: 'uravakonda', nameEn: 'Uravakonda Silk Weaving', nameTe: 'ఉరవకొండ' },
    { slug: 'vajrakarur', nameEn: 'Vajrakarur Diamond Processing Fields', nameTe: 'వజ్రకరూరు' },
    { slug: 'vidapanakal', nameEn: 'Vidapanakal', nameTe: 'విడపనకల్లు' },
    { slug: 'yadiki', nameEn: 'Yadiki Underground Caves', nameTe: 'యాడికి' },
    { slug: 'yellanur', nameEn: 'Yellanur', nameTe: 'యల్లనూరు' },
  ],
  'sri-sathya-sai': [
    { slug: 'agali', nameEn: 'Agali', nameTe: 'అగళి' },
    { slug: 'amadagur', nameEn: 'Amadagur', nameTe: 'ఆమడగూరు' },
    { slug: 'amarapuram', nameEn: 'Amarapuram', nameTe: 'అమరాపురం' },
    { slug: 'bathalapalle', nameEn: 'Bathalapalle', nameTe: 'బత్తలపల్లి' },
    { slug: 'bukkapatnam', nameEn: 'Bukkapatnam', nameTe: 'బుక్కపట్నం' },
    { slug: 'ck-palle', nameEn: 'C.K. Palle', nameTe: 'సి.కె. పల్లి' },
    { slug: 'chennekothapalle', nameEn: 'Chennekothapalle', nameTe: 'చెన్నేకొత్తపల్లె' },
    { slug: 'chilamathur', nameEn: 'Chilamathur Kodur Border Hub', nameTe: 'చిలమత్తూరు' },
    { slug: 'dharmavaram', nameEn: 'Dharmavaram World Heritage Silk Sarees', nameTe: 'ధర్మవరం' },
    { slug: 'gandlapenta', nameEn: 'Gandlapenta', nameTe: 'గాండ్లపెంట' },
    { slug: 'gorantla', nameEn: 'Gorantla Madhavaraya Temple', nameTe: 'గొరంట్ల' },
    { slug: 'gudibanda', nameEn: 'Gudibanda', nameTe: 'గుడిబండ' },
    { slug: 'hindupur', nameEn: 'Hindupur Industrial & Automobile Trade', nameTe: 'హిందూపురం' },
    { slug: 'kadiri', nameEn: 'Kadiri Khadri Lakshmi Narasimha Swamy', nameTe: 'కదిరి' },
    { slug: 'kanaganapalle', nameEn: 'Kanaganapalle', nameTe: 'కనగానపల్లి' },
    { slug: 'kothacheruvu', nameEn: 'Kothacheruvu', nameTe: 'కొత్తచెరువు' },
    { slug: 'lepakshi', nameEn: 'Lepakshi Monolithic Basavanna & Hanging Pillar', nameTe: 'లేపాక్షి' },
    { slug: 'madakasira', nameEn: 'Madakasira Hill Fort', nameTe: 'మడకశిర' },
    { slug: 'mudigubba', nameEn: 'Mudigubba', nameTe: 'ముదిగుబ్బ' },
    { slug: 'np-kunta', nameEn: 'N.P. Kunta 1000MW Solar Park', nameTe: 'నంబులపూలకుంట' },
    { slug: 'nallacheruvu', nameEn: 'Nallacheruvu', nameTe: 'నల్లచెరువు' },
    { slug: 'nallamada', nameEn: 'Nallamada', nameTe: 'నల్లమాడ' },
    { slug: 'nambulapulakunta', nameEn: 'Nambulapulakunta', nameTe: 'నంబులపూలకుంట' },
    { slug: 'od-cheruvu', nameEn: 'O.D. Cheruvu', nameTe: 'ఓబులదేవరచెరువు' },
    { slug: 'obuladevaracheruvu', nameEn: 'Obuladevaracheruvu', nameTe: 'ఓబులదేవరచెరువు' },
    { slug: 'parigi-sss', nameEn: 'Parigi', nameTe: 'పరిగి' },
    { slug: 'penukonda', nameEn: 'Penukonda Vijayanagara Second Capital & KIA Motors', nameTe: 'పెనుకొండ' },
    { slug: 'puttaparthi', nameEn: 'Puttaparthi Prasanthi Nilayam Spiritual Capital', nameTe: 'పుట్టపర్తి' },
    { slug: 'ramagiri', nameEn: 'Ramagiri Wind & Gold Belt', nameTe: 'రామగిరి' },
    { slug: 'roddam', nameEn: 'Roddam', nameTe: 'రొద్దం' },
    { slug: 'rolla', nameEn: 'Rolla', nameTe: 'రొళ్ల' },
    { slug: 'somandepalle', nameEn: 'Somandepalle', nameTe: 'సోమందేపల్లి' },
    { slug: 'tadimarri', nameEn: 'Tadimarri', nameTe: 'తాడిమర్రి' },
    { slug: 'talupula', nameEn: 'Talupula', nameTe: 'తలుపుల' },
    { slug: 'tanakal', nameEn: 'Tanakal', nameTe: 'తనకల్లు' },
  ],
  'kadapa-ysr': [
    { slug: 'atlur', nameEn: 'Atlur', nameTe: 'అట్లూరు' },
    { slug: 'b-kodur', nameEn: 'B. Kodur', nameTe: 'బి. కోడూరు' },
    { slug: 'badvel', nameEn: 'Badvel Commercial Division', nameTe: 'బద్వేలు' },
    { slug: 'brahmamgarimattam-mandal', nameEn: 'Brahmamgarimattam', nameTe: 'బ్రహ్మంగారిమఠం' },
    { slug: 'chakrayapet', nameEn: 'Chakrayapet', nameTe: 'చక్రాయపేట' },
    { slug: 'chapadu', nameEn: 'Chapadu', nameTe: 'చాపాడు' },
    { slug: 'chennur-ysr', nameEn: 'Chennur', nameTe: 'చెన్నూరు' },
    { slug: 'chinthakommadinne', nameEn: 'Chinthakommadinne', nameTe: 'చింతకొమ్మదిన్నె' },
    { slug: 'duvvur', nameEn: 'Duvvur', nameTe: 'దువ్వూరు' },
    { slug: 'gopavaram', nameEn: 'Gopavaram Industrial Corridor', nameTe: 'గోపవరం' },
    { slug: 'jammalamadugu', nameEn: 'Jammalamadugu (Gandikota Fort & Gorge)', nameTe: 'జమ్మలమడుగు' },
    { slug: 'kadapa-rural', nameEn: 'Kadapa Rural', nameTe: 'కడప రూరల్' },
    { slug: 'kadapa-urban', nameEn: 'Kadapa Urban / Ameen Peer Dargah / Devuni Kadapa', nameTe: 'కడప అర్బన్' },
    { slug: 'kalasapadu', nameEn: 'Kalasapadu', nameTe: 'కలసపాడు' },
    { slug: 'kamalapuram', nameEn: 'Kamalapuram Papaghni River', nameTe: 'కమలాపురం' },
    { slug: 'kasi-nayana', nameEn: 'Kasi Nayana Avadhuta Kshetram', nameTe: 'కాశీనాయన' },
    { slug: 'khajipet', nameEn: 'Khajipet', nameTe: 'ఖాజీపేట' },
    { slug: 'kondapuram-ysr', nameEn: 'Kondapuram', nameTe: 'కొండాపురం' },
    { slug: 'lingala-ysr', nameEn: 'Lingala', nameTe: 'లింగాల' },
    { slug: 'muddanur', nameEn: 'Muddanur RTPP Thermal Power Station', nameTe: 'ముద్దనూరు' },
    { slug: 'mydukur', nameEn: 'Mydukur Four-Roads Commercial Junction', nameTe: 'మైదుకూరు' },
    { slug: 'mylavaram-ysr', nameEn: 'Mylavaram Reservoir Dam', nameTe: 'మైలవరం' },
    { slug: 'nandalur', nameEn: 'Nandalur', nameTe: 'నందలూరు' },
    { slug: 'peddamudium', nameEn: 'Peddamudium', nameTe: 'పెద్దముడియం' },
    { slug: 'pendlimarri', nameEn: 'Pendlimarri', nameTe: 'పెండ్లిమర్రి' },
    { slug: 'porumamilla', nameEn: 'Porumamilla 14th Century Historic Tank', nameTe: 'పోరుమామిళ్ల' },
    { slug: 'proddatur-gold', nameEn: 'Proddatur (Second Bombay / Gold Hub)', nameTe: 'ప్రొద్దుటూరు' },
    { slug: 'pulivendla', nameEn: 'Pulivendla', nameTe: 'పులివెందుల' },
    { slug: 'pulivendula', nameEn: 'Pulivendula Banana & Horticulture Center', nameTe: 'పులివెందుల' },
    { slug: 'rajampet', nameEn: 'Rajampet', nameTe: 'రాజంపేట' },
    { slug: 'rajupalem', nameEn: 'Rajupalem', nameTe: 'రాజుపాలెం' },
    { slug: 's-mydukur', nameEn: 'S.Mydukur', nameTe: 'మైదుకూరు' },
    { slug: 'siddhavatam', nameEn: 'Siddhavatam Penna River Fort', nameTe: 'సిద్ధవటం' },
    { slug: 'sidhout', nameEn: 'Sidhout', nameTe: 'సిద్దవటం' },
    { slug: 'simhadripuram', nameEn: 'Simhadripuram', nameTe: 'సింహాద్రిపురం' },
    { slug: 'sri-avadhutha-kasinayana', nameEn: 'Sri Avadhutha Kasinayana', nameTe: 'శ్రీ అవధూత కాశీనాయన' },
    { slug: 'brahmamgarimattam', nameEn: 'Sri Potuluri Veerabrahmendra Swamy Mutt', nameTe: 'బ్రహ్మంగారిమఠం' },
    { slug: 't-sundupalle', nameEn: 'T. Sundupalle', nameTe: 'టి. సుండుపల్లె' },
    { slug: 'thondur', nameEn: 'Thondur', nameTe: 'తొండూరు' },
    { slug: 'vallur', nameEn: 'Vallur Pushpagiri Peetham', nameTe: 'వల్లూరు (పుష్పగిరి)' },
    { slug: 'veeraballi', nameEn: 'Veeraballi', nameTe: 'వీరబల్లి' },
    { slug: 'veerapunayunipalle', nameEn: 'Veerapunayunipalle', nameTe: 'వీరపునాయునిపల్లె' },
    { slug: 'vempalle', nameEn: 'Vempalle (Idupulapaya Valley)', nameTe: 'వెంపల్లె' },
    { slug: 'vemula', nameEn: 'Vemula Uranium Corporation', nameTe: 'వేముల' },
    { slug: 'vontimitta', nameEn: 'Vontimitta Sri Kodandarama Temple', nameTe: 'ఒంటిమిట్ట' },
    { slug: 'yerraguntla', nameEn: 'Yerraguntla South India Cement Capital', nameTe: 'ఎర్రగుంట్ల' },
  ],
  'annamayya': [
    { slug: 'b-kothakota', nameEn: 'B. Kothakota Horsley Hills Gateway', nameTe: 'బి. కొత్తకోట (హార్సిలీ హిల్స్)' },
    { slug: 'beerangi-kothakota', nameEn: 'Beerangi Kothakota', nameTe: 'బి.కొత్తకోట' },
    { slug: 'chinnamandem', nameEn: 'Chinnamandem', nameTe: 'చిన్నమండెం' },
    { slug: 'chinnamandyam', nameEn: 'Chinnamandyam', nameTe: 'చిన్నమండెం' },
    { slug: 'chitvel', nameEn: 'Chitvel', nameTe: 'చిట్వేలు' },
    { slug: 'chowdepalle', nameEn: 'Chowdepalle', nameTe: 'చౌడేపల్లి' },
    { slug: 'galiveedu', nameEn: 'Galiveedu Solar Power Fields', nameTe: 'గాలివీడు' },
    { slug: 'gurramkonda', nameEn: 'Gurramkonda Heritage Citadel', nameTe: 'గుర్రంకొండ' },
    { slug: 'kv-palle', nameEn: 'K.V. Palle', nameTe: 'కె.వి. పల్లె' },
    { slug: 'kalakada', nameEn: 'Kalakada', nameTe: 'కలకడ' },
    { slug: 'kalikiri', nameEn: 'Kalikiri Sainik School', nameTe: 'కలికిరి' },
    { slug: 'kambhamvaripalle', nameEn: 'Kambhamvaripalle', nameTe: 'కంబంవారిపల్లె' },
    { slug: 'kurabalakota', nameEn: 'Kurabalakota', nameTe: 'కురబలకోట' },
    { slug: 'lakkireddipalli', nameEn: 'Lakkireddipalli', nameTe: 'లక్కిరెడ్డిపల్లె' },
    { slug: 'lakkireddypalle', nameEn: 'Lakkireddypalle', nameTe: 'లక్కిరెడ్డిపల్లె' },
    { slug: 'madanapalle', nameEn: 'Madanapalle Silk City & Asia Largest Tomato Market', nameTe: 'మదనపల్లె' },
    { slug: 'mulakalacheruvu', nameEn: 'Mulakalacheruvu', nameTe: 'ములకలచెరువు' },
    { slug: 'nandalur', nameEn: 'Nandalur Soumyanatha Swamy Historic Temple', nameTe: 'నందలూరు' },
    { slug: 'nimmanapalle', nameEn: 'Nimmanapalle Krishnamurti Foundation', nameTe: 'నిమ్మనపల్లె' },
    { slug: 'obulavaripalle', nameEn: 'Obulavaripalle World Mangampeta Barites Mine', nameTe: 'ఓబులవారిపల్లె' },
    { slug: 'peddamandyam', nameEn: 'Peddamandyam', nameTe: 'పెద్దమండ్యం' },
    { slug: 'peddathippasamudram', nameEn: 'Peddathippasamudram', nameTe: 'పెద్దతిప్పసముద్రం' },
    { slug: 'penagalur', nameEn: 'Penagalur', nameTe: 'పెనగలూరు' },
    { slug: 'pileru', nameEn: 'Pileru Commercial Cross Roads', nameTe: 'పీలేరు' },
    { slug: 'pullampeta', nameEn: 'Pullampeta', nameTe: 'పుల్లంపేట' },
    { slug: 'punganur', nameEn: 'Punganur', nameTe: 'పుంగనూరు' },
    { slug: 'railway-koduru', nameEn: 'Railway Koduru Mango & Banana Junction', nameTe: 'రైల్వే కోడూరు' },
    { slug: 'rajampet', nameEn: 'Rajampet Education Hub', nameTe: 'రాజంపేట' },
    { slug: 'ramapuram', nameEn: 'Ramapuram', nameTe: 'రామాపురం' },
    { slug: 'ramasamu-dram', nameEn: 'Ramasamudram', nameTe: 'రామసముద్రం' },
    { slug: 'rayachoti', nameEn: 'Rayachoti Headquarters / Veerabhadra Swamy', nameTe: 'రాయచోటి' },
    { slug: 'sambepalle', nameEn: 'Sambepalle', nameTe: 'సంబేపల్లి' },
    { slug: 'sambepalli', nameEn: 'Sambepalli', nameTe: 'సంబేపల్లి' },
    { slug: 'sodam', nameEn: 'Sodam', nameTe: 'సోదం' },
    { slug: 'somala', nameEn: 'Somala', nameTe: 'సోమల' },
    { slug: 't-sundupalle', nameEn: 'T. Sundupalle', nameTe: 'టి. సుండుపల్లె' },
    { slug: 'tallapaka', nameEn: 'Tallapaka Sri Pada Kavitha Pitamaha Janmasthalam', nameTe: 'తాళ్లపాక' },
    { slug: 'thamballapalle', nameEn: 'Thamballapalle', nameTe: 'తంబళ్లపల్లె' },
    { slug: 'valmikipuram', nameEn: 'Valmikipuram (Vayalpadu)', nameTe: 'వాల్మీకిపురం' },
    { slug: 'veeraballi', nameEn: 'Veeraballi', nameTe: 'వీరబల్లి' },
  ],
  'tirupati': [
    { slug: 'balayapalle', nameEn: 'Balayapalle', nameTe: 'బాలాయపల్లె' },
    { slug: 'buchinaidu-kandriga', nameEn: 'Buchinaidu Kandriga', nameTe: 'బుచ్చినాయుడు కండ్రిగ' },
    { slug: 'chandragiri', nameEn: 'Chandragiri Historic Vijayanagara Fort', nameTe: 'చంద్రగిరి' },
    { slug: 'chillakur', nameEn: 'Chillakur', nameTe: 'చిల్లకూరు' },
    { slug: 'chinnagottigallu', nameEn: 'Chinnagottigallu', nameTe: 'చిన్నగొట్టిగల్లు' },
    { slug: 'chittamur', nameEn: 'Chittamur', nameTe: 'చిట్టమూరు' },
    { slug: 'chitvel', nameEn: 'Chitvel', nameTe: 'చిట్వేలు' },
    { slug: 'dakkili', nameEn: 'Dakkili', nameTe: 'డక్కిలి' },
    { slug: 'doravarisatram', nameEn: 'Doravarisatram (Pulicat Bird Sanctuary)', nameTe: 'దొరవారిసత్రం' },
    { slug: 'gudur', nameEn: 'Gudur Lemon Market & Railway Junction', nameTe: 'గూడూరు' },
    { slug: 'k-v-b-puram', nameEn: 'K. V. B. Puram', nameTe: 'కె.వి.బి.పురం' },
    { slug: 'kodur', nameEn: 'Kodur', nameTe: 'కోడూరు' },
    { slug: 'kota', nameEn: 'Kota', nameTe: 'కోట' },
    { slug: 'nagalapuram', nameEn: 'Nagalapuram Vedanarayana Swamy Temple', nameTe: 'నాగలాపురం' },
    { slug: 'naidupeta', nameEn: 'Naidupeta Special Economic Zone', nameTe: 'నాయుడుపేట' },
    { slug: 'narayanavanam', nameEn: 'Narayanavanam Sri Kalyana Venkateswara', nameTe: 'నారాయణవనం' },
    { slug: 'obulavaripalle', nameEn: 'Obulavaripalle', nameTe: 'ఓబులవారిపల్లె' },
    { slug: 'ozili', nameEn: 'Ozili', nameTe: 'ఓజిలి' },
    { slug: 'pakala', nameEn: 'Pakala Lake & Railway Junction', nameTe: 'పాకాల' },
    { slug: 'pellakur', nameEn: 'Pellakur', nameTe: 'పెళ్లకూరు' },
    { slug: 'penagalur', nameEn: 'Penagalur', nameTe: 'పెనగలూరు' },
    { slug: 'pichatur', nameEn: 'Pichatur Araniar Reservoir', nameTe: 'పిచ్చాటూరు' },
    { slug: 'pullampeta', nameEn: 'Pullampeta', nameTe: 'పుల్లంపేట' },
    { slug: 'puttur', nameEn: 'Puttur Joint Kattu & Commercial Town', nameTe: 'పుత్తూరు' },
    { slug: 'ramachandrapuram-tpt', nameEn: 'Ramachandrapuram', nameTe: 'రామచంద్రాపురం' },
    { slug: 'renigunta', nameEn: 'Renigunta Airport & Railway Terminus', nameTe: 'రేణిగుంట' },
    { slug: 'satyavedu', nameEn: 'Satyavedu Border Industrial Belt', nameTe: 'సత్యవేడు' },
    { slug: 'srikalahasti', nameEn: 'Srikalahasti Vayu Linga Kshetram', nameTe: 'శ్రీకాళహస్తి' },
    { slug: 'sullurpeta', nameEn: 'Sullurpeta (Satish Dhawan Space Centre ISRO SHAR)', nameTe: 'సూళ్లూరుపేట' },
    { slug: 'tada', nameEn: 'Tada Sri City Integrated Industrial Township', nameTe: 'తడ (శ్రీసిటీ)' },
    { slug: 'thottambedu', nameEn: 'Thottambedu', nameTe: 'తొట్టంబేడు' },
    { slug: 'tirumala', nameEn: 'Tirumala Lord Venkateswara Abode', nameTe: 'తిరుమల' },
    { slug: 'tirupati-rural', nameEn: 'Tirupati Rural', nameTe: 'తిరుపతి రూరల్' },
    { slug: 'tirupati-urban', nameEn: 'Tirupati Urban (Alipiri / Balaji Colony)', nameTe: 'తిరుపతి అర్బన్' },
    { slug: 'vadamalapeta', nameEn: 'Vadamalapeta Appalayagunta Temple', nameTe: 'వడమాలపేట' },
    { slug: 'vakadu', nameEn: 'Vakadu', nameTe: 'వాకాడు' },
    { slug: 'varadaiahpalem', nameEn: 'Varadaiahpalem Spiritual Valley', nameTe: 'వరదయ్యపాలెం' },
    { slug: 'venkatagiri', nameEn: 'Venkatagiri Heritage Zari Sarees & Palace', nameTe: 'వెంకటగిరి' },
    { slug: 'yerpedu', nameEn: 'Yerpedu (IIT & IISER Campus)', nameTe: 'ఏర్పేడు' },
    { slug: 'yerravaripalem', nameEn: 'Yerravaripalem Talakona Waterfalls', nameTe: 'ఎర్రవారిపాలెం' },
  ],
  'chittoor': [
    { slug: 'baireddipalle', nameEn: 'Baireddipalle', nameTe: 'బైరెడ్డిపల్లె' },
    { slug: 'bangarupalem', nameEn: 'Bangarupalem', nameTe: 'బంగారుపాలెం' },
    { slug: 'bangurupalem', nameEn: 'Bangurupalem', nameTe: 'బంగారుపాలెం' },
    { slug: 'bireddypalli', nameEn: 'Bireddypalli', nameTe: 'బైరెడ్డిపల్లి' },
    { slug: 'chittoor-rural', nameEn: 'Chittoor Rural', nameTe: 'చిత్తూరు రూరల్' },
    { slug: 'chittoor-urban', nameEn: 'Chittoor Urban / Mango Pulp Capital', nameTe: 'చిత్తూరు అర్బన్' },
    { slug: 'chowdepalle', nameEn: 'Chowdepalle Boyakonda Gangamma Temple', nameTe: 'చౌడేపల్లి' },
    { slug: 'gd-nellore', nameEn: 'G.D. Nellore', nameTe: 'గంగాధర నెల్లూరు' },
    { slug: 'gangadhara-nellore', nameEn: 'Gangadhara Nellore', nameTe: 'గంగాధర నెల్లూరు' },
    { slug: 'gangavaram-ctr', nameEn: 'Gangavaram', nameTe: 'గంగవరం' },
    { slug: 'gudipala', nameEn: 'Gudipala', nameTe: 'గుడిపాల' },
    { slug: 'gudipalle', nameEn: 'Gudipalle', nameTe: 'గుడిపల్లె' },
    { slug: 'gudupalle', nameEn: 'Gudupalle Dravidian University', nameTe: 'గుడుపల్లె' },
    { slug: 'irala', nameEn: 'Irala', nameTe: 'ఐరాల' },
    { slug: 'kanipakam', nameEn: 'Kanipakam Sri Varasiddhi Vinayaka Kshetram', nameTe: 'కాణిపాకం' },
    { slug: 'karvetinagaram', nameEn: 'Karvetinagaram Heritage Rajahs Palace', nameTe: 'కార్వేటినగరం' },
    { slug: 'kuppam', nameEn: 'Kuppam Tri-State Tri-Junction (AP-TN-KA)', nameTe: 'కుప్పం' },
    { slug: 'nagari', nameEn: 'Nagari Weaving Town & Border Hub', nameTe: 'నగరి' },
    { slug: 'nindra', nameEn: 'Nindra', nameTe: 'నిండ్ర' },
    { slug: 'palamaner', nameEn: 'Palamaner Dairy Cattle Research & NH75', nameTe: 'పలమనేరు' },
    { slug: 'palasamudram', nameEn: 'Palasamudram', nameTe: 'పాలసముద్రం' },
    { slug: 'peddapanjani', nameEn: 'Peddapanjani', nameTe: 'పెద్దపంజాణి' },
    { slug: 'penumuru', nameEn: 'Penumuru', nameTe: 'పెనుమూరు' },
    { slug: 'pulicherla', nameEn: 'Pulicherla', nameTe: 'పులిచెర్ల' },
    { slug: 'punganur', nameEn: 'Punganur World Miniature Dwarf Cattle Land', nameTe: 'పుంగనూరు' },
    { slug: 'puthalapattu', nameEn: 'Puthalapattu', nameTe: 'పూతలపట్టు' },
    { slug: 'ramakuppam', nameEn: 'Ramakuppam', nameTe: 'రామకుప్పం' },
    { slug: 'rompicherla-ctr', nameEn: 'Rompicherla', nameTe: 'రొంపిచర్ల' },
    { slug: 'sr-puram', nameEn: 'S.R. Puram', nameTe: 'ఎస్.ఆర్. పురం' },
    { slug: 'shanthipuram', nameEn: 'Santhipuram', nameTe: 'శాంతిపురం' },
    { slug: 'sodam', nameEn: 'Sodam', nameTe: 'సోదం' },
    { slug: 'somala', nameEn: 'Somala', nameTe: 'సోమల' },
    { slug: 'sri-rangaraja-puram', nameEn: 'Sri Rangaraja Puram', nameTe: 'శ్రీరంగరాజపురం' },
    { slug: 'thavanampalle', nameEn: 'Thavanampalle Kanipakam Gateway', nameTe: 'తవణంపల్లి' },
    { slug: 'vedurukuppam', nameEn: 'Vedurukuppam', nameTe: 'వెదురుకుప్పం' },
    { slug: 'v-kota', nameEn: 'Venkatagirikota (V. Kota)', nameTe: 'వి. కోట' },
    { slug: 'vijayapuram', nameEn: 'Vijayapuram', nameTe: 'విజయపురం' },
    { slug: 'yadamarri', nameEn: 'Yadamarri', nameTe: 'యాదమరి' },
  ],
};

/**
 * Helper to get all Andhra Pradesh mandals flat array with district tag
 */
export function getAllAndhraMandals(): MandalItem[] {
  const result: MandalItem[] = [];
  for (const [district, mandals] of Object.entries(ANDHRA_PRADESH_MANDALS_MAP)) {
    for (const m of mandals) {
      result.push({
        district,
        slug: m.slug,
        nameEn: m.nameEn,
        nameTe: m.nameTe,
      });
    }
  }
  return result;
}

/**
 * Retrieve mandals for a specific AP district
 */
export function getAndhraMandalsByDistrict(districtSlug: string): { slug: string; nameEn: string; nameTe: string }[] {
  return ANDHRA_PRADESH_MANDALS_MAP[districtSlug] || [];
}
