export interface MandalItem {
  district: string;
  slug: string;
  nameEn: string;
  nameTe?: string;
}

export interface DistrictItem {
  slug: string;
  code: string;
  nameEn: string;
  nameTe: string;
  state: 'telangana' | 'andhra-pradesh';
}

/**
 * Official 26 Districts of Andhra Pradesh based on the 2022 District Reorganization (AP Gazette)
 */
export const ALL_ANDHRA_DISTRICTS: DistrictItem[] = [
  // Uttarandhra (North Coastal)
  { slug: 'srikakulam', code: 'SKLM', nameEn: 'Srikakulam', nameTe: 'శ్రీకాకుళం', state: 'andhra-pradesh' },
  { slug: 'vizianagaram', code: 'VZNR', nameEn: 'Vizianagaram', nameTe: 'విజయనగరం', state: 'andhra-pradesh' },
  { slug: 'parvathipuram-manyam', code: 'PMNM', nameEn: 'Parvathipuram Manyam', nameTe: 'పార్వతీపురం మన్యం', state: 'andhra-pradesh' },
  { slug: 'alluri-sitharama-raju', code: 'ASR', nameEn: 'Alluri Sitharama Raju', nameTe: 'అల్లూరి సీతారామరాజు', state: 'andhra-pradesh' },
  { slug: 'visakhapatnam', code: 'VSP', nameEn: 'Visakhapatnam', nameTe: 'విశాఖపట్నం', state: 'andhra-pradesh' },
  { slug: 'anakapalli', code: 'AKPL', nameEn: 'Anakapalli', nameTe: 'అనకాపల్లి', state: 'andhra-pradesh' },

  // Kosta Andhra (Coastal)
  { slug: 'kakinada', code: 'KKD', nameEn: 'Kakinada', nameTe: 'కాకినాడ', state: 'andhra-pradesh' },
  { slug: 'konaseema', code: 'KNSM', nameEn: 'Dr. B.R. Ambedkar Konaseema', nameTe: 'డా. బి.ఆర్. అంబేద్కర్ కోనసీమ', state: 'andhra-pradesh' },
  { slug: 'east-godavari', code: 'EGOD', nameEn: 'East Godavari (Rajamahendravaram)', nameTe: 'తూర్పు గోదావరి (రాజమహేంద్రవరం)', state: 'andhra-pradesh' },
  { slug: 'west-godavari', code: 'WGOD', nameEn: 'West Godavari (Bhimavaram)', nameTe: 'పశ్చిమ గోదావరి (భీమవరం)', state: 'andhra-pradesh' },
  { slug: 'eluru', code: 'ELR', nameEn: 'Eluru', nameTe: 'ఏలూరు', state: 'andhra-pradesh' },
  { slug: 'krishna', code: 'KSHN', nameEn: 'Krishna (Machilipatnam)', nameTe: 'కృష్ణా (మచిలీపట్నం)', state: 'andhra-pradesh' },
  { slug: 'vijayawada-ntr', code: 'NTR', nameEn: 'NTR (Vijayawada)', nameTe: 'ఎన్టీఆర్ (విజయవాడ)', state: 'andhra-pradesh' },
  { slug: 'guntur', code: 'GNT', nameEn: 'Guntur', nameTe: 'గుంటూరు', state: 'andhra-pradesh' },
  { slug: 'palnadu', code: 'PLND', nameEn: 'Palnadu (Narasaraopet)', nameTe: 'పల్నాడు (నరసరావుపేట)', state: 'andhra-pradesh' },
  { slug: 'bapatla', code: 'BPTL', nameEn: 'Bapatla', nameTe: 'బాపట్ల', state: 'andhra-pradesh' },
  { slug: 'prakasam', code: 'PKSM', nameEn: 'Prakasam (Ongole)', nameTe: 'ప్రకాశం (ఒంగోలు)', state: 'andhra-pradesh' },
  { slug: 'sri-potti-sriramulu-nellore', code: 'NLR', nameEn: 'Sri Potti Sriramulu Nellore', nameTe: 'శ్రీ పొట్టి శ్రీరాములు నెల్లూరు', state: 'andhra-pradesh' },

  // Rayalaseema
  { slug: 'kurnool', code: 'KNL', nameEn: 'Kurnool', nameTe: 'కర్నూలు', state: 'andhra-pradesh' },
  { slug: 'nandyal', code: 'NDYL', nameEn: 'Nandyal', nameTe: 'నంద్యాల', state: 'andhra-pradesh' },
  { slug: 'anantapur', code: 'ANTP', nameEn: 'Ananthapuramu', nameTe: 'అనంతపురం', state: 'andhra-pradesh' },
  { slug: 'sri-sathya-sai', code: 'SSSI', nameEn: 'Sri Sathya Sai (Puttaparthi)', nameTe: 'శ్రీ సత్యసాయి (పుట్టపర్తి)', state: 'andhra-pradesh' },
  { slug: 'kadapa-ysr', code: 'YSR', nameEn: 'YSR Kadapa', nameTe: 'వైఎస్సార్ కడప', state: 'andhra-pradesh' },
  { slug: 'annamayya', code: 'ANMY', nameEn: 'Annamayya (Rayachoti)', nameTe: 'అన్నమయ్య (రాయచోటి)', state: 'andhra-pradesh' },
  { slug: 'tirupati', code: 'TPT', nameEn: 'Tirupati', nameTe: 'తిరుపతి', state: 'andhra-pradesh' },
  { slug: 'chittoor', code: 'CHTR', nameEn: 'Chittoor', nameTe: 'చిత్తూరు', state: 'andhra-pradesh' },
];

/**
 * Authentic Revenue Mandals and Major Towns for all 26 Districts of Andhra Pradesh
 */
export const ANDHRA_PRADESH_MANDALS_MAP: Record<string, { slug: string; nameEn: string; nameTe: string }[]> = {
  'srikakulam': [
    { slug: 'srikakulam-urban', nameEn: 'Srikakulam Urban', nameTe: 'శ్రీకాకుళం అర్బన్' },
    { slug: 'srikakulam-rural', nameEn: 'Srikakulam Rural', nameTe: 'శ్రీకాకుళం రూరల్' },
    { slug: 'amadalavalasa', nameEn: 'Amadalavalasa', nameTe: 'ఆమదాలవలస' },
    { slug: 'palasa', nameEn: 'Palasa / Kasibugga', nameTe: 'పలాస / కాశీబుగ్గ' },
    { slug: 'sompeta', nameEn: 'Sompeta', nameTe: 'సోంపేట' },
    { slug: 'ichchapuram', nameEn: 'Ichchapuram', nameTe: 'ఇచ్ఛాపురం' },
    { slug: 'tekkali', nameEn: 'Tekkali', nameTe: 'టెక్కలి' },
    { slug: 'narasannapeta', nameEn: 'Narasannapeta', nameTe: 'నరసన్నపేట' },
    { slug: 'etcherla', nameEn: 'Etcherla', nameTe: 'ఎచ్చెర్ల' },
    { slug: 'ranastalam', nameEn: 'Ranastalam', nameTe: 'రణస్థలం' },
    { slug: 'ponduru', nameEn: 'Ponduru Khadi', nameTe: 'పొందూరు' },
    { slug: 'kotabommali', nameEn: 'Kotabommali', nameTe: 'కోటబొమ్మాళి' },
    { slug: 'pathapatnam', nameEn: 'Pathapatnam', nameTe: 'పాతపట్నం' },
    { slug: 'mandasa', nameEn: 'Mandasa', nameTe: 'మందస' },
    { slug: 'kaviti', nameEn: 'Kaviti', nameTe: 'కవిటి' },
    { slug: 'vajrapukothuru', nameEn: 'Vajrapukothuru', nameTe: 'వజ్రపుకొత్తూరు' },
    { slug: 'jalumuru', nameEn: 'Jalumuru', nameTe: 'జలుమూరు' },
    { slug: 'polaki', nameEn: 'Polaki', nameTe: 'పోలాకి' },
    { slug: 'gara', nameEn: 'Gara', nameTe: 'గార' },
  ],
  'vizianagaram': [
    { slug: 'vizianagaram-urban', nameEn: 'Vizianagaram Urban', nameTe: 'విజయనగరం అర్బన్' },
    { slug: 'vizianagaram-rural', nameEn: 'Vizianagaram Rural', nameTe: 'విజయనగరం రూరల్' },
    { slug: 'bobbili', nameEn: 'Bobbili Heritage Town', nameTe: 'బొబ్బిలి' },
    { slug: 'cheepurupalle', nameEn: 'Cheepurupalle', nameTe: 'చీపురుపల్లి' },
    { slug: 'gajapathinagaram', nameEn: 'Gajapathinagaram', nameTe: 'గజపతినగరం' },
    { slug: 'nellimarla', nameEn: 'Nellimarla', nameTe: 'నెల్లిమర్ల' },
    { slug: 'rajam', nameEn: 'Rajam', nameTe: 'రాజాం' },
    { slug: 'kothavalasa', nameEn: 'Kothavalasa', nameTe: 'కొత్తవలస' },
    { slug: 'sringavarapukota', nameEn: 'S.Kota (Sringavarapukota)', nameTe: 'శృంగవరపుకోట' },
    { slug: 'pusapatirega', nameEn: 'Pusapatirega', nameTe: 'పూసపాటిరేగ' },
    { slug: 'bhogapuram', nameEn: 'Bhogapuram Airport Zone', nameTe: 'భోగాపురం' },
    { slug: 'garividi', nameEn: 'Garividi', nameTe: 'గరివిడి' },
    { slug: 'badangi', nameEn: 'Badangi', nameTe: 'బాడాంగి' },
    { slug: 'dattirajeru', nameEn: 'Dattirajeru', nameTe: 'దత్తిరాజేరు' },
    { slug: 'mentada', nameEn: 'Mentada', nameTe: 'మెంటాడ' },
    { slug: 'gantyada', nameEn: 'Gantyada', nameTe: 'గంట్యాడ' },
  ],
  'parvathipuram-manyam': [
    { slug: 'parvathipuram', nameEn: 'Parvathipuram Headquarters', nameTe: 'పార్వతీపురం' },
    { slug: 'salur', nameEn: 'Salur', nameTe: 'సాలూరు' },
    { slug: 'palakonda', nameEn: 'Palakonda', nameTe: 'పాలకొండ' },
    { slug: 'kurupam', nameEn: 'Kurupam', nameTe: 'కురుపాం' },
    { slug: 'gummalaxmipuram', nameEn: 'Gummalaxmipuram', nameTe: 'గుమ్మలక్ష్మీపురం' },
    { slug: 'garugubilli', nameEn: 'Garugubilli', nameTe: 'గరుగుబిల్లి' },
    { slug: 'komarada', nameEn: 'Komarada', nameTe: 'కొమరాడ' },
    { slug: 'jiyyammavalasa', nameEn: 'Jiyyammavalasa', nameTe: 'జియ్యమ్మవలస' },
    { slug: 'makkuva', nameEn: 'Makkuva', nameTe: 'మక్కువ' },
    { slug: 'seethampeta', nameEn: 'Seethampeta', nameTe: 'సీతంపేట' },
    { slug: 'veeraghattam', nameEn: 'Veeraghattam', nameTe: 'వీరఘట్టం' },
    { slug: 'bhamini', nameEn: 'Bhamini', nameTe: 'భామినీ' },
  ],
  'alluri-sitharama-raju': [
    { slug: 'paderu', nameEn: 'Paderu Headquarters', nameTe: 'పాడేరు' },
    { slug: 'araku-valley', nameEn: 'Araku Valley Coffee Hills', nameTe: 'అరకు లోయ' },
    { slug: 'rampachodavaram', nameEn: 'Rampachodavaram Godavari Basin', nameTe: 'రంపచోడవరం' },
    { slug: 'chintapalle', nameEn: 'Chintapalle Lambasingi', nameTe: 'చింతపల్లి (లంబసింగి)' },
    { slug: 'ananthagiri', nameEn: 'Ananthagiri Borra Caves', nameTe: 'అనంతగిరి' },
    { slug: 'dumbriguda', nameEn: 'Dumbriguda', nameTe: 'డుంబ్రిగుడ' },
    { slug: 'hukumpeta', nameEn: 'Hukumpeta', nameTe: 'హుకుంపేట' },
    { slug: 'g-madugula', nameEn: 'G. Madugula', nameTe: 'జి. మాడుగుల' },
    { slug: 'pedabayalu', nameEn: 'Pedabayalu', nameTe: 'పెదబయలు' },
    { slug: 'munchingiputtu', nameEn: 'Munchingi Puttu', nameTe: 'ముంచింగిపుట్టు' },
    { slug: 'addateegala', nameEn: 'Addateegala', nameTe: 'అడ్డతీగల' },
    { slug: 'maredumilli', nameEn: 'Maredumilli Eco Forest', nameTe: 'మారేడుమిల్లి' },
    { slug: 'gangavaram-asr', nameEn: 'Gangavaram', nameTe: 'గంగవరం' },
    { slug: 'chintoor', nameEn: 'Chintoor / Koonavaram', nameTe: 'చింతూరు / కూనవరం' },
  ],
  'visakhapatnam': [
    { slug: 'maharanipeta', nameEn: 'Maharanipeta (Collectorate)', nameTe: 'మహారాణిపేట' },
    { slug: 'gajuwaka', nameEn: 'Gajuwaka Industrial Hub', nameTe: 'గాజువాక' },
    { slug: 'visakhapatnam-rural', nameEn: 'Visakhapatnam Rural', nameTe: 'విశాఖపట్నం రూరల్' },
    { slug: 'bheemunipatnam', nameEn: 'Bheemunipatnam (Bheemili Beach)', nameTe: 'భీమునిపట్నం' },
    { slug: 'pendurthi', nameEn: 'Pendurthi', nameTe: 'పెందుర్తి' },
    { slug: 'madhurawada', nameEn: 'Madhurawada / IT SEZ', nameTe: 'మధురవాడ' },
    { slug: 'seethammadhara', nameEn: 'Seethammadhara', nameTe: 'సీతమ్మధార' },
    { slug: 'gopalapatnam', nameEn: 'Gopalapatnam / Simhachalam', nameTe: 'గోపాలపట్నం (సింహాచలం)' },
    { slug: 'mvp-colony', nameEn: 'MVP Colony / Beach Road', nameTe: 'ఎం.వి.పి. కాలనీ' },
    { slug: 'pedagantyada', nameEn: 'Pedagantyada Steel Plant', nameTe: 'పెదగంట్యాడ' },
    { slug: 'anandapuram', nameEn: 'Anandapuram', nameTe: 'ఆనందపురం' },
    { slug: 'padmanabham', nameEn: 'Padmanabham', nameTe: 'పద్మనాభం' },
  ],
  'anakapalli': [
    { slug: 'anakapalle', nameEn: 'Anakapalle Jaggery Market', nameTe: 'అనకాపల్లి' },
    { slug: 'chodavaram', nameEn: 'Chodavaram', nameTe: 'చోడవరం' },
    { slug: 'yelamanchili', nameEn: 'Yelamanchili', nameTe: 'యలమంచిలి' },
    { slug: 'narsipatnam', nameEn: 'Narsipatnam', nameTe: 'నర్సీపట్నం' },
    { slug: 'payakaraopeta', nameEn: 'Payakaraopeta', nameTe: 'పాయకరావుపేట' },
    { slug: 'kasimkota', nameEn: 'Kasimkota', nameTe: 'కాశీంకోట' },
    { slug: 'k-kotapadu', nameEn: 'K. Kotapadu', nameTe: 'కె. కోటపాడు' },
    { slug: 'devarapalle', nameEn: 'Devarapalle', nameTe: 'దేవరపల్లి' },
    { slug: 'madugula', nameEn: 'Madugula Halwa Heritage', nameTe: 'మాడుగుల' },
    { slug: 'munagapaka', nameEn: 'Munagapaka', nameTe: 'మునగపాక' },
    { slug: 'parawada', nameEn: 'Parawada Pharma City', nameTe: 'పరవాడ' },
    { slug: 'atchutapuram', nameEn: 'Atchutapuram SEZ', nameTe: 'అచ్యుతాపురం' },
    { slug: 'rambilli', nameEn: 'Rambilli Coastal', nameTe: 'రాంబిల్లి' },
    { slug: 's-rayavaram', nameEn: 'S. Rayavaram', nameTe: 'ఎస్. రాయవరం' },
    { slug: 'nakkapalle', nameEn: 'Nakkapalle', nameTe: 'నక్కపల్లి' },
    { slug: 'kotauratla', nameEn: 'Kotauratla', nameTe: 'కోటవురట్ల' },
    { slug: 'rolugunta', nameEn: 'Rolugunta', nameTe: 'రోలుగుంట' },
  ],
  'kakinada': [
    { slug: 'kakinada-urban', nameEn: 'Kakinada Port & Smart City', nameTe: 'కాకినాడ అర్బన్' },
    { slug: 'kakinada-rural', nameEn: 'Kakinada Rural', nameTe: 'కాకినాడ రూరల్' },
    { slug: 'samalkota', nameEn: 'Samalkota Pancharama Kshetram', nameTe: 'సామర్లకోట' },
    { slug: 'peddapuram', nameEn: 'Peddapuram', nameTe: 'పెద్దాపురం' },
    { slug: 'pithapuram', nameEn: 'Pithapuram Sripada Kshetram', nameTe: 'పిఠాపురం' },
    { slug: 'tuni', nameEn: 'Tuni Betel Leaf Market', nameTe: 'తుని' },
    { slug: 'prathipadu-kkn', nameEn: 'Prathipadu', nameTe: 'ప్రత్తిపాడు' },
    { slug: 'gollaprolu', nameEn: 'Gollaprolu', nameTe: 'గొల్లప్రోలు' },
    { slug: 'u-kothapalli', nameEn: 'U. Kothapalli Uppada Beach', nameTe: 'ఉప్పాడ కొత్తపల్లి' },
    { slug: 'karapa', nameEn: 'Karapa', nameTe: 'కరప' },
    { slug: 'thallarevu', nameEn: 'Thallarevu Coringa Mangroves', nameTe: 'తాళ్లరేవు' },
    { slug: 'kajuluru', nameEn: 'Kajuluru', nameTe: 'కాజులూరు' },
    { slug: 'kotananduru', nameEn: 'Kotananduru', nameTe: 'కోటనందూరు' },
    { slug: 'rowthulapudi', nameEn: 'Rowthulapudi', nameTe: 'రౌతులపూడి' },
    { slug: 'sankhavaram', nameEn: 'Sankhavaram', nameTe: 'శంఖవరం' },
    { slug: 'yeleswaram', nameEn: 'Yeleswaram', nameTe: 'ఏలేశ్వరం' },
    { slug: 'jaggampeta', nameEn: 'Jaggampeta', nameTe: 'జగ్గంపేట' },
    { slug: 'gandepalle', nameEn: 'Gandepalle', nameTe: 'గండేపల్లి' },
  ],
  'konaseema': [
    { slug: 'amalapuram', nameEn: 'Amalapuram Headquarters', nameTe: 'అమలాపురం' },
    { slug: 'ravulapalem', nameEn: 'Ravulapalem Banana Market Hub', nameTe: 'రావులపాలెం' },
    { slug: 'kothapeta', nameEn: 'Kothapeta', nameTe: 'కొత్తపేట' },
    { slug: 'ramachandrapuram', nameEn: 'Ramachandrapuram Draksharamam', nameTe: 'రామచంద్రపురం' },
    { slug: 'mandapeta', nameEn: 'Mandapeta Rice Mill City', nameTe: 'మండపేట' },
    { slug: 'mummidivaram', nameEn: 'Mummidivaram Balayogi Kshetram', nameTe: 'ముమ్మిడివరం' },
    { slug: 'razole', nameEn: 'Razole Scenic Coconut Delta', nameTe: 'రాజోలు' },
    { slug: 'malikipuram', nameEn: 'Malikipuram (Dindi Resorts)', nameTe: 'మలికిపురం' },
    { slug: 'sakinetipalli', nameEn: 'Sakinetipalli Antarvedi Sangamam', nameTe: 'సఖినేటిపల్లి (అంతర్వేది)' },
    { slug: 'allavaram', nameEn: 'Allavaram', nameTe: 'అల్లవరం' },
    { slug: 'katrenikona', nameEn: 'Katrenikona', nameTe: 'కత్రేనికోన' },
    { slug: 'uppalaguptam', nameEn: 'Uppalaguptam', nameTe: 'ఉప్పలగుప్తం' },
    { slug: 'ainavilli', nameEn: 'Ainavilli Siddhi Vinayaka', nameTe: 'ఐనవిల్లి' },
    { slug: 'ambajipeta', nameEn: 'Ambajipeta Coconut Center', nameTe: 'అంబాజీపేట' },
    { slug: 'p-gannavaram', nameEn: 'P. Gannavaram Aqueduct', nameTe: 'పి. గన్నవరం' },
    { slug: 'atreyapuram', nameEn: 'Atreyapuram Pootharekulu Hub', nameTe: 'ఆత్రేయపురం' },
    { slug: 'alamuru', nameEn: 'Alamuru', nameTe: 'ఆలమూరు' },
    { slug: 'rayavaram', nameEn: 'Rayavaram', nameTe: 'రాయవరం' },
    { slug: 'kapileswarapuram', nameEn: 'Kapileswarapuram Zamindari Heritage', nameTe: 'కపిలేశ్వరపురం' },
  ],
  'east-godavari': [
    { slug: 'rajamahendravaram-urban', nameEn: 'Rajamahendravaram Urban (Rajahmundry)', nameTe: 'రాజమండ్రి అర్బన్' },
    { slug: 'rajamahendravaram-rural', nameEn: 'Rajamahendravaram Rural', nameTe: 'రాజమండ్రి రూరల్' },
    { slug: 'kovvur', nameEn: 'Kovvur Goshpada Kshetram', nameTe: 'కొవ్వూరు' },
    { slug: 'nidadavole', nameEn: 'Nidadavole Junction', nameTe: 'నిడదవోలు' },
    { slug: 'anaparthi', nameEn: 'Anaparthi', nameTe: 'అనపర్తి' },
    { slug: 'bikkavolu', nameEn: 'Bikkavolu Historic Chalukya Temples', nameTe: 'బిక్కవోలు' },
    { slug: 'kadiam', nameEn: 'Kadiam Flora Nurseries', nameTe: 'కడియం' },
    { slug: 'korukonda', nameEn: 'Korukonda Lakshmi Narasimha Swamy', nameTe: 'కోరుకొండ' },
    { slug: 'rajanagaram', nameEn: 'Rajanagaram Education Hub', nameTe: 'రాజానగరం' },
    { slug: 'rangampeta', nameEn: 'Rangampeta', nameTe: 'రంగంపేట' },
    { slug: 'gokavaram', nameEn: 'Gokavaram', nameTe: 'గోకవరం' },
    { slug: 'seethanagaram', nameEn: 'Seethanagaram', nameTe: 'సీతానగరం' },
    { slug: 'chagallu', nameEn: 'Chagallu Sugars', nameTe: 'చాగల్లు' },
    { slug: 'tallapudi', nameEn: 'Tallapudi', nameTe: 'తాళ్లపూడి' },
    { slug: 'peravali', nameEn: 'Peravali', nameTe: 'పేరవలి' },
    { slug: 'undrajavaram', nameEn: 'Undrajavaram', nameTe: 'ఉండ్రాజవరం' },
    { slug: 'devarapalle-eg', nameEn: 'Devarapalle', nameTe: 'దేవరపల్లి' },
    { slug: 'gopalapuram', nameEn: 'Gopalapuram', nameTe: 'గోపాలపురం' },
  ],
  'west-godavari': [
    { slug: 'bhimavaram', nameEn: 'Bhimavaram Somarama Kshetram', nameTe: 'భీమవరం' },
    { slug: 'tanuku', nameEn: 'Tanuku Andhra Sugars Industrial Town', nameTe: 'తణుకు' },
    { slug: 'tadepalligudem', nameEn: 'Tadepalligudem NIT & Trade Center', nameTe: 'తాడేపల్లిగూడెం' },
    { slug: 'narasapuram', nameEn: 'Narasapuram Lace & Port Town', nameTe: 'నర్సాపురం' },
    { slug: 'palakollu', nameEn: 'Palakollu Ksheerarama Kshetram', nameTe: 'పాలకొల్లు' },
    { slug: 'akividu', nameEn: 'Akividu Aquaculture Hub', nameTe: 'ఆకివీడు' },
    { slug: 'kalla', nameEn: 'Kalla', nameTe: 'కళ్ల' },
    { slug: 'undi', nameEn: 'Undi', nameTe: 'ఉండి' },
    { slug: 'attili', nameEn: 'Attili', nameTe: 'అత్తిలి' },
    { slug: 'iragavaram', nameEn: 'Iragavaram', nameTe: 'ఇరగవరం' },
    { slug: 'pentapadu', nameEn: 'Pentapadu', nameTe: 'పెంటపాడు' },
    { slug: 'achanta', nameEn: 'Achanta Rameswara Swamy', nameTe: 'ఆచంట' },
    { slug: 'poduru', nameEn: 'Poduru', nameTe: 'పోడూరు' },
    { slug: 'penumantra', nameEn: 'Penumantra', nameTe: 'పెనుమంత్ర' },
    { slug: 'penugonda', nameEn: 'Penugonda Vasavi Kanyaka Parameswari', nameTe: 'పెనుగొండ' },
    { slug: 'mogalthur', nameEn: 'Mogalthur Heritage Town', nameTe: 'మొగల్తూరు' },
    { slug: 'yelamanchili-wg', nameEn: 'Yelamanchili', nameTe: 'యలమంచిలి' },
    { slug: 'veeravasaram', nameEn: 'Veeravasaram', nameTe: 'వీరవాసరం' },
  ],
  'eluru': [
    { slug: 'eluru-urban', nameEn: 'Eluru Urban Carpet City', nameTe: 'ఏలూరు అర్బన్' },
    { slug: 'eluru-rural', nameEn: 'Eluru Rural', nameTe: 'ఏలూరు రూరల్' },
    { slug: 'jangareddygudem', nameEn: 'Jangareddygudem Commercial Agency', nameTe: 'జంగారెడ్డిగూడెం' },
    { slug: 'nuzvid', nameEn: 'Nuzvid Banganapalli Mango Capital', nameTe: 'నూజివీడు' },
    { slug: 'chintalapudi', nameEn: 'Chintalapudi', nameTe: 'చింతలపూడి' },
    { slug: 'kaikaluru', nameEn: 'Kaikaluru Kolleru Sanctuary', nameTe: 'కైకలూరు' },
    { slug: 'mandavalli', nameEn: 'Mandavalli', nameTe: 'మండవల్లి' },
    { slug: 'mudinepalle', nameEn: 'Mudinepalle', nameTe: 'ముదినేపల్లి' },
    { slug: 'denduluru', nameEn: 'Denduluru', nameTe: 'దेंदులూరు' },
    { slug: 'pedavegi', nameEn: 'Pedavegi Vengi Capital Heritage', nameTe: 'పెదవేగి' },
    { slug: 'pedapadu', nameEn: 'Pedapadu', nameTe: 'పెదపాడు' },
    { slug: 'unguturu', nameEn: 'Unguturu', nameTe: 'ఉంగుటూరు' },
    { slug: 'bhimadole', nameEn: 'Bhimadole', nameTe: 'భీమడోలు' },
    { slug: 'nidamarru', nameEn: 'Nidamarru', nameTe: 'నిడమర్రు' },
    { slug: 'kamavarapukota', nameEn: 'Kamavarapukota Guntupalli Caves', nameTe: 'కామవరపుకోట' },
    { slug: 'dwarakatirumala', nameEn: 'Dwaraka Tirumala (Chinna Tirupati)', nameTe: 'ద్వారకా తిరుమల' },
    { slug: 't-narasapuram', nameEn: 'T. Narasapuram', nameTe: 'టి. నరసాపురం' },
    { slug: 'lingapalem', nameEn: 'Lingapalem', nameTe: 'లింగపాలెం' },
    { slug: 'musunuru', nameEn: 'Musunuru', nameTe: 'ముసునూరు' },
    { slug: 'agiripalli', nameEn: 'Agiripalli Shobhanachala Swamy', nameTe: 'ఆగిరిపల్లి' },
    { slug: 'chatrai', nameEn: 'Chatrai', nameTe: 'చాట్రాయి' },
    { slug: 'polavaram', nameEn: 'Polavaram National Project Site', nameTe: 'పోలవరం' },
    { slug: 'buttayagudem', nameEn: 'Buttayagudem', nameTe: 'బుట్టాయగూడెం' },
    { slug: 'jeelugumilli', nameEn: 'Jeelugumilli', nameTe: 'జీలుగుమిల్లి' },
    { slug: 'kukunoor', nameEn: 'Kukunoor Tribal Region', nameTe: 'కుక్కునూరు' },
    { slug: 'velairpadu', nameEn: 'Velairpadu Godavari Basin', nameTe: 'వేలేరుపాడు' },
  ],
  'krishna': [
    { slug: 'machilipatnam-urban', nameEn: 'Machilipatnam Coastal Port City', nameTe: 'మచిలీపట్నం అర్బన్' },
    { slug: 'machilipatnam-rural', nameEn: 'Machilipatnam Rural', nameTe: 'మచిలీపట్నం రూరల్' },
    { slug: 'gudivada', nameEn: 'Gudivada Commercial Junction', nameTe: 'గుడివాడ' },
    { slug: 'vuyyuru', nameEn: 'Vuyyuru Sugar Factory City', nameTe: 'వుయ్యూరు' },
    { slug: 'avanigadda', nameEn: 'Avanigadda Diviseema Gateway', nameTe: 'అవనిగడ్డ' },
    { slug: 'challapalli', nameEn: 'Challapalli Raja Palace', nameTe: 'చల్లపల్లి' },
    { slug: 'nagayalanka', nameEn: 'Nagayalanka Light House Delta', nameTe: 'నాగాయలంక' },
    { slug: 'koduru-krishna', nameEn: 'Koduru Beach', nameTe: 'కోడూరు' },
    { slug: 'pedana', nameEn: 'Pedana Kalamkari & Handlooms', nameTe: 'పెడన' },
    { slug: 'bantumilli', nameEn: 'Bantumilli', nameTe: 'బంటుమిల్లి' },
    { slug: 'kruthivennu', nameEn: 'Kruthivennu', nameTe: 'కృతివెన్ను' },
    { slug: 'guduru-krishna', nameEn: 'Guduru', nameTe: 'గూడూరు' },
    { slug: 'movva', nameEn: 'Movva Kshetrayya Kshetram', nameTe: 'మొవ్వ' },
    { slug: 'ghantasala', nameEn: 'Ghantasala Buddhist Heritage', nameTe: 'ఘంటసాల' },
    { slug: 'pamarru', nameEn: 'Pamarru', nameTe: 'పామర్రు' },
    { slug: 'thotlavalluru', nameEn: 'Thotlavalluru', nameTe: 'తోట్లవల్లూరు' },
    { slug: 'kankipadu', nameEn: 'Kankipadu', nameTe: 'కంకిపాడు' },
    { slug: 'penamaluru', nameEn: 'Penamaluru', nameTe: 'పెనమలూరు' },
    { slug: 'pedaparupudi', nameEn: 'Pedaparupudi', nameTe: 'పెదపారుపూడి' },
    { slug: 'nandivada', nameEn: 'Nandivada', nameTe: 'నందివాడ' },
    { slug: 'gudlavalleru', nameEn: 'Gudlavalleru Engineering Hub', nameTe: 'గుడ్లవల్లేరు' },
  ],
  'vijayawada-ntr': [
    { slug: 'vijayawada-central', nameEn: 'Vijayawada Central / Besant Road', nameTe: 'విజయవాడ సెంట్రల్' },
    { slug: 'vijayawada-east', nameEn: 'Vijayawada East / Benz Circle', nameTe: 'విజయవాడ ఈస్ట్' },
    { slug: 'vijayawada-west', nameEn: 'Vijayawada West / Kanaka Durga Temple', nameTe: 'విజయవాడ వెస్ట్ (దుర్గ గుడి)' },
    { slug: 'vijayawada-north', nameEn: 'Vijayawada North / Gunadala Mary Matha', nameTe: 'విజయవాడ నార్త్' },
    { slug: 'vijayawada-rural', nameEn: 'Vijayawada Rural', nameTe: 'విజయవాడ రూరల్' },
    { slug: 'jaggaiahpet', nameEn: 'Jaggaiahpet Cement Belt', nameTe: 'జగ్గయ్యపేట' },
    { slug: 'nandigama', nameEn: 'Nandigama Commercial Town', nameTe: 'నందిగామ' },
    { slug: 'ibrahimpatnam-ntr', nameEn: 'Ibrahimpatnam (Dr. NTTPS Thermal)', nameTe: 'ఇబ్రహీంపట్నం' },
    { slug: 'tiruvuru', nameEn: 'Tiruvuru Mango Belt', nameTe: 'తిరువూరు' },
    { slug: 'kondapalli', nameEn: 'Kondapalli Fort & Wooden Toys', nameTe: 'కొండపల్లి' },
    { slug: 'mylavaram', nameEn: 'Mylavaram', nameTe: 'మైలవరం' },
    { slug: 'g-konduru', nameEn: 'G. Konduru', nameTe: 'జి. కొండూరు' },
    { slug: 'kanchikacherla', nameEn: 'Kanchikacherla', nameTe: 'కంచికచర్ల' },
    { slug: 'veerullapadu', nameEn: 'Veerullapadu', nameTe: 'వీరుళ్లపాడు' },
    { slug: 'vatsavai', nameEn: 'Vatsavai', nameTe: 'వత్సవాయి' },
    { slug: 'penuganchiprolu', nameEn: 'Penuganchiprolu Sri Tirupatamma Temple', nameTe: 'పెనుగంచిప్రోలు' },
    { slug: 'chandarlapadu', nameEn: 'Chandarlapadu', nameTe: 'చందర్లపాడు' },
    { slug: 'a-konduru', nameEn: 'A. Konduru', nameTe: 'ఎ. కొండూరు' },
    { slug: 'gampalagudem', nameEn: 'Gampalagudem', nameTe: 'గంపలగూడెం' },
    { slug: 'vissannapeta', nameEn: 'Vissannapeta', nameTe: 'విస్సన్నపేట' },
  ],
  'guntur': [
    { slug: 'guntur-urban', nameEn: 'Guntur Urban / Brodipet / Arundelpet', nameTe: 'గుంటూరు అర్బన్' },
    { slug: 'guntur-east', nameEn: 'Guntur East / Mirchi Yard', nameTe: 'గుంటూరు ఈస్ట్ (మిర్చి యార్డ్)' },
    { slug: 'guntur-rural', nameEn: 'Guntur Rural', nameTe: 'గుంటూరు రూరల్' },
    { slug: 'tenali', nameEn: 'Tenali (Andhra Paris Cultural Capital)', nameTe: 'తెనాలి' },
    { slug: 'mangalagiri', nameEn: 'Mangalagiri Panakala Narasimha / AIIMS', nameTe: 'మంగళగిరి' },
    { slug: 'tadepalli', nameEn: 'Tadepalli Capital Zone', nameTe: 'తాడేపల్లి' },
    { slug: 'ponnur', nameEn: 'Ponnur Sakshi Ganapathi', nameTe: 'పొన్నూరు' },
    { slug: 'prathipadu-gnt', nameEn: 'Prathipadu', nameTe: 'ప్రత్తిపాడు' },
    { slug: 'tadikonda', nameEn: 'Tadikonda', nameTe: 'తాడికొండ' },
    { slug: 'thullur', nameEn: 'Thullur (Amaravati Capital Seed Access)', nameTe: 'తుళ్లూరు (అమరావతి)' },
    { slug: 'chebrolu', nameEn: 'Chebrolu Historic Chaturmukha Brahma', nameTe: 'చేబ్రోలు' },
    { slug: 'pedakakani', nameEn: 'Pedakakani Malleswara Temple', nameTe: 'పెదకాకాని' },
    { slug: 'medikonduru', nameEn: 'Medikonduru', nameTe: 'మేడికొండూరు' },
    { slug: 'pedanandipadu', nameEn: 'Pedanandipadu', nameTe: 'పెదనందిపాడు' },
    { slug: 'vatticherukuru', nameEn: 'Vatticherukuru', nameTe: 'వట్టిచెరుకూరు' },
    { slug: 'kakumanu', nameEn: 'Kakumanu', nameTe: 'కాకుమాను' },
    { slug: 'duggirala', nameEn: 'Duggirala World Turmeric Market', nameTe: 'దుగ్గిరాల' },
    { slug: 'kollipara', nameEn: 'Kollipara', nameTe: 'కొల్లిపర' },
  ],
  'palnadu': [
    { slug: 'narasaraopet', nameEn: 'Narasaraopet Kotappakonda Gateway', nameTe: 'నరసరావుపేట' },
    { slug: 'chilakaluripet', nameEn: 'Chilakaluripet Cotton & NH16', nameTe: 'చిలకలూరిపేట' },
    { slug: 'sattenapalle', nameEn: 'Sattenapalle', nameTe: 'సత్తెనపల్లి' },
    { slug: 'vinukonda', nameEn: 'Vinukonda Hill Fort Town', nameTe: 'వినుకొండ' },
    { slug: 'gurazala', nameEn: 'Gurazala Palnadu Division', nameTe: 'గురజాల' },
    { slug: 'macherla', nameEn: 'Macherla Chennakesava Swamy', nameTe: 'మాచర్ల' },
    { slug: 'piduguralla', nameEn: 'Piduguralla White Limestone City', nameTe: 'పిడుగురాళ్ల' },
    { slug: 'dachepalle', nameEn: 'Dachepalle', nameTe: 'దాచేపల్లి' },
    { slug: 'karempudi', nameEn: 'Karempudi Palnadu Heroes Temple', nameTe: 'కారెంపూడి' },
    { slug: 'rentachintala', nameEn: 'Rentachintala', nameTe: 'రెంటచింతల' },
    { slug: 'bellamkonda', nameEn: 'Bellamkonda Fort', nameTe: 'బెల్లంకొండ' },
    { slug: 'muppalla', nameEn: 'Muppalla', nameTe: 'ముప్పాళ్ల' },
    { slug: 'nadendla', nameEn: 'Nadendla', nameTe: 'నాదెండ్ల' },
    { slug: 'edlapadu', nameEn: 'Edlapadu', nameTe: 'యడ్లపాడు' },
    { slug: 'savalyapuram', nameEn: 'Savalyapuram', nameTe: 'శావల్యాపురం' },
    { slug: 'nuzendla', nameEn: 'Nuzendla', nameTe: 'నూజెండ్ల' },
    { slug: 'bollapalle', nameEn: 'Bollapalle', nameTe: 'బొల్లాపల్లి' },
    { slug: 'nekarikallu', nameEn: 'Nekarikallu', nameTe: 'నెకరికల్లు' },
    { slug: 'rompicherla-pln', nameEn: 'Rompicherla', nameTe: 'రొంపిచర్ల' },
    { slug: 'atchampeta', nameEn: 'Atchampeta', nameTe: 'అచ్చంపేట' },
    { slug: 'krosuru', nameEn: 'Krosuru', nameTe: 'క్రోసూరు' },
    { slug: 'amaravathi-heritage', nameEn: 'Amaravathi Amaralingeswara & Mahastupa', nameTe: 'అమరావతి' },
  ],
  'bapatla': [
    { slug: 'bapatla-town', nameEn: 'Bapatla Suryalanka Beach & Agriculture College', nameTe: 'బాపట్ల' },
    { slug: 'chirala', nameEn: 'Chirala Handloom & Textile City', nameTe: 'చీరాల' },
    { slug: 'repalle', nameEn: 'Repalle Coastal Terminal', nameTe: 'రేపల్లె' },
    { slug: 'parchur', nameEn: 'Parchur', nameTe: 'పర్చూరు' },
    { slug: 'addanki', nameEn: 'Addanki Historic Inscription Town', nameTe: 'అద్దంకి' },
    { slug: 'vetapalem', nameEn: 'Vetapalem Saraswatha Nikethanam', nameTe: 'వేటపాలెం' },
    { slug: 'karamchedu', nameEn: 'Karamchedu', nameTe: 'కారంచేడు' },
    { slug: 'chinaganjam', nameEn: 'Chinaganjam Salt Pans', nameTe: 'చినగంజాం' },
    { slug: 'inkollu', nameEn: 'Inkollu', nameTe: 'ఇంకొల్లు' },
    { slug: 'martur', nameEn: 'Martur Granite Hub', nameTe: 'మార్టూరు' },
    { slug: 'yeddanapudi', nameEn: 'Yeddanapudi', nameTe: 'యద్దనపూడి' },
    { slug: 'kollur', nameEn: 'Kollur', nameTe: 'కొల్లూరు' },
    { slug: 'bhattiprolu', nameEn: 'Bhattiprolu Ancient Buddhist Stupa', nameTe: 'భట్టిప్రోలు' },
    { slug: 'vemuru', nameEn: 'Vemuru', nameTe: 'వేమూరు' },
    { slug: 'amruthalur', nameEn: 'Amruthalur', nameTe: 'అమృతలూరు' },
    { slug: 'tsundur', nameEn: 'Tsundur', nameTe: 'చుండూరు' },
    { slug: 'nagaram', nameEn: 'Nagaram', nameTe: 'నగరం' },
    { slug: 'nizampatnam', nameEn: 'Nizampatnam Fishing Port & Delta', nameTe: 'నిజాంపట్నం' },
    { slug: 'pittalavanipalem', nameEn: 'Pittalavanipalem', nameTe: 'పిట్టలవానిపాలెం' },
    { slug: 'karlapalem', nameEn: 'Karlapalem', nameTe: 'కార్లపాలెం' },
    { slug: 'korisapadu', nameEn: 'Korisapadu', nameTe: 'కోరిశపాడు' },
    { slug: 'j-panguluru', nameEn: 'J. Panguluru', nameTe: 'జనకవరం పంగులూరు' },
    { slug: 'santhamaguluru', nameEn: 'Santhamaguluru', nameTe: 'సంతమాగులూరు' },
    { slug: 'ballikurava', nameEn: 'Ballikurava', nameTe: 'బల్లికురవ' },
  ],
  'prakasam': [
    { slug: 'ongole-urban', nameEn: 'Ongole Breed Heritage City', nameTe: 'ఒంగోలు అర్బన్' },
    { slug: 'ongole-rural', nameEn: 'Ongole Rural', nameTe: 'ఒంగోలు రూరల్' },
    { slug: 'kandukur', nameEn: 'Kandukur Commercial Division', nameTe: 'కందుకూరు' },
    { slug: 'markapur', nameEn: 'Markapur Slate Industry', nameTe: 'మార్కాపురం' },
    { slug: 'giddalur', nameEn: 'Giddalur Nallamala Foothills', nameTe: 'గిద్దలూరు' },
    { slug: 'kanigiri', nameEn: 'Kanigiri', nameTe: 'కనిగిరి' },
    { slug: 'podili', nameEn: 'Podili', nameTe: 'పొదిలి' },
    { slug: 'darsi', nameEn: 'Darsi', nameTe: 'దర్శి' },
    { slug: 'yerragondapalem', nameEn: 'Yerragondapalem', nameTe: 'యర్రగొండపాలెం' },
    { slug: 'chimakurthy', nameEn: 'Chimakurthy Galaxy Black Granite', nameTe: 'చీమకుర్తి' },
    { slug: 'singarayakonda', nameEn: 'Singarayakonda Varaha Lakshmi Narasimha', nameTe: 'సింగరాయకొండ' },
    { slug: 'tangutur', nameEn: 'Tangutur', nameTe: 'టంగుటూరు' },
    { slug: 'kothapatnam', nameEn: 'Kothapatnam Sea Coast', nameTe: 'కొత్తపట్నం' },
    { slug: 'maddipadu', nameEn: 'Maddipadu', nameTe: 'మద్దిపాడు' },
    { slug: 'santhanuthalapadu', nameEn: 'Santhanuthalapadu', nameTe: 'సంతనూతలపాడు' },
    { slug: 'naguluppalapadu', nameEn: 'Naguluppalapadu', nameTe: 'నాగులుప్పలపాడు' },
    { slug: 'zarugumilli', nameEn: 'Zarugumilli', nameTe: 'జరుగుమల్లి' },
    { slug: 'kondapi', nameEn: 'Kondapi', nameTe: 'కొండపి' },
    { slug: 'marripudi', nameEn: 'Marripudi', nameTe: 'మర్రిపూడి' },
    { slug: 'ponnaluru', nameEn: 'Ponnaluru', nameTe: 'పొన్నలూరు' },
    { slug: 'ulavapadu', nameEn: 'Ulavapadu Export Banganapalli', nameTe: 'ఉలవపాడు' },
    { slug: 'gudluru', nameEn: 'Gudluru', nameTe: 'గుడ్లూరు' },
    { slug: 'lingasamudram', nameEn: 'Lingasamudram', nameTe: 'లింగసముద్రం' },
    { slug: 'voletivaripalem', nameEn: 'Voletivaripalem', nameTe: 'వోలేటివారిపాలెం' },
    { slug: 'pamuru', nameEn: 'Pamuru', nameTe: 'పామూరు' },
    { slug: 'veligandla', nameEn: 'Veligandla', nameTe: 'వెలిగండ్ల' },
    { slug: 'cs-puram', nameEn: 'C.S. Puram', nameTe: 'సి.ఎస్. పురం' },
    { slug: 'pedaaraveedu', nameEn: 'Peda Araveedu', nameTe: 'పెద్దారవీడు' },
    { slug: 'cumbum', nameEn: 'Cumbum Historic Ancient Lake', nameTe: 'కంబం' },
    { slug: 'ardhaveedu', nameEn: 'Ardhaveedu', nameTe: 'అర్థవీడు' },
    { slug: 'racherla', nameEn: 'Racherla', nameTe: 'రాచర్ల' },
    { slug: 'komarolu', nameEn: 'Komarolu', nameTe: 'కొమరోలు' },
    { slug: 'besthavaripeta', nameEn: 'Besthavaripeta', nameTe: 'బెస్తవారిపేట' },
    { slug: 'pullalacheruvu', nameEn: 'Pullalacheruvu', nameTe: 'పుల్లలచెరువు' },
    { slug: 'tripuranthakam', nameEn: 'Tripuranthakam Srisailam Eastern Gateway', nameTe: 'త్రిపురాంతకం' },
    { slug: 'kurichedu', nameEn: 'Kurichedu', nameTe: 'కురిచేడు' },
    { slug: 'donakonda', nameEn: 'Donakonda Industrial Belt', nameTe: 'దొనకొండ' },
    { slug: 'mundlamuru', nameEn: 'Mundlamuru', nameTe: 'ముండ్లమూరు' },
    { slug: 'thallur', nameEn: 'Thallur', nameTe: 'తాళ్లూరు' },
  ],
  'sri-potti-sriramulu-nellore': [
    { slug: 'nellore-urban', nameEn: 'Nellore Smart City / Ranganatha Swamy', nameTe: 'నెల్లూరు అర్బన్' },
    { slug: 'nellore-rural', nameEn: 'Nellore Rural', nameTe: 'నెల్లూరు రూరల్' },
    { slug: 'kavali', nameEn: 'Kavali Education & Trade City', nameTe: 'కావలి' },
    { slug: 'atmakur-nlr', nameEn: 'Atmakur Somashila Gateway', nameTe: 'ఆత్మకూరు' },
    { slug: 'kovur-nlr', nameEn: 'Kovur Penna River Fertile Belt', nameTe: 'కోవూరు' },
    { slug: 'allur', nameEn: 'Allur', nameTe: 'అల్లూరు' },
    { slug: 'buchireddypalem', nameEn: 'Buchireddypalem Jonnawada Kamakshi', nameTe: 'బుచ్చిరెడ్డిపాలెం (జొన్నవాడ)' },
    { slug: 'indukurpet', nameEn: 'Indukurpet Coastal Delta', nameTe: 'ఇందుకూరుపేట' },
    { slug: 'kodavalur', nameEn: 'Kodavalur', nameTe: 'కొడవలూరు' },
    { slug: 'vidavalur', nameEn: 'Vidavalur', nameTe: 'విడవలూరు' },
    { slug: 'muthukur', nameEn: 'Muthukur Deep Sea Port', nameTe: 'ముత్తుకూరు (కృష్ణపట్నం పోర్ట్)' },
    { slug: 'thotapalligudur', nameEn: 'Thotapalligudur', nameTe: 'తోటపల్లిగూడూరు' },
    { slug: 'podalakur', nameEn: 'Podalakur', nameTe: 'పొదలకూరు' },
    { slug: 'manubolu', nameEn: 'Manubolu', nameTe: 'మనుబోలు' },
    { slug: 'venkatachalam', nameEn: 'Venkatachalam', nameTe: 'వెంకటాచలం' },
    { slug: 'rapur', nameEn: 'Rapur Penchalakona Kshetram', nameTe: 'రాపూరు (పెంచలకోన)' },
    { slug: 'kaluvoya', nameEn: 'Kaluvoya', nameTe: 'కలువోయ' },
    { slug: 'anantasagaram', nameEn: 'Anantasagaram Somashila Project', nameTe: 'అనంతసాగరం (సోమశిల)' },
    { slug: 'marripadu', nameEn: 'Marripadu', nameTe: 'మర్రిపాడు' },
    { slug: 'sitaramapuram', nameEn: 'Sitaramapuram', nameTe: 'సీతారామపురం' },
    { slug: 'varikuntapadu', nameEn: 'Varikuntapadu', nameTe: 'వరికుంటపాడు' },
    { slug: 'udayagiri', nameEn: 'Udayagiri Hill Fort Heritage', nameTe: 'ఉదయగిరి' },
    { slug: 'vinjamur', nameEn: 'Vinjamur', nameTe: 'వింజమూరు' },
    { slug: 'duttalur', nameEn: 'Duttalur', nameTe: 'దుత్తలూరు' },
    { slug: 'jaladanki', nameEn: 'Jaladanki', nameTe: 'జలదంకి' },
    { slug: 'kaligiri', nameEn: 'Kaligiri', nameTe: 'కలిగిరి' },
    { slug: 'kondapuram-nlr', nameEn: 'Kondapuram', nameTe: 'కొండాపురం' },
    { slug: 'bogole', nameEn: 'Bogole / Bitragunta Railway Yard', nameTe: 'బోగోలు' },
    { slug: 'dagadarthi', nameEn: 'Dagadarthi Non-Metro Airport Site', nameTe: 'దగదర్తి' },
    { slug: 'sangam', nameEn: 'Sangam Triveni Sangamam', nameTe: 'సంగం' },
  ],
  'kurnool': [
    { slug: 'kurnool-urban', nameEn: 'Kurnool Historic Konda Reddy Buruju City', nameTe: 'కర్నూలు అర్బన్' },
    { slug: 'kurnool-rural', nameEn: 'Kurnool Rural', nameTe: 'కర్నూలు రూరల్' },
    { slug: 'adoni-urban', nameEn: 'Adoni Cotton & Grain Trade Hub', nameTe: 'ఆదోని' },
    { slug: 'yemmiganur', nameEn: 'Yemmiganur Handloom Weavers City', nameTe: 'ఎమ్మిగనూరు' },
    { slug: 'dhone', nameEn: 'Dhone / Dronachalam Mining Hub', nameTe: 'డోన్' },
    { slug: 'pattikonda', nameEn: 'Pattikonda', nameTe: 'పత్తికొండ' },
    { slug: 'kodumur', nameEn: 'Kodumur', nameTe: 'కోడుమూరు' },
    { slug: 'mantralayam', nameEn: 'Mantralayam Sri Raghavendra Swamy Mutt', nameTe: 'మంత్రాలయం' },
    { slug: 'alur', nameEn: 'Alur', nameTe: 'ఆలూరు' },
    { slug: 'aspari', nameEn: 'Aspari', nameTe: 'ఆస్పరి' },
    { slug: 'devanakonda', nameEn: 'Devanakonda', nameTe: 'దేవనకొండ' },
    { slug: 'gonagandla', nameEn: 'Gonagandla', nameTe: 'గోనెగండ్ల' },
    { slug: 'holagunda', nameEn: 'Holagunda', nameTe: 'హొళగుంద' },
    { slug: 'halaharvi', nameEn: 'Halaharvi', nameTe: 'హాలహర్వి' },
    { slug: 'kallur-knl', nameEn: 'Kallur Industrial Estate', nameTe: 'కల్లూరు' },
    { slug: 'kosigi', nameEn: 'Kosigi', nameTe: 'కోసిగి' },
    { slug: 'kowthalam', nameEn: 'Kowthalam', nameTe: 'కౌతాళం' },
    { slug: 'krishnagiri-knl', nameEn: 'Krishnagiri', nameTe: 'కృష్ణగిరి' },
    { slug: 'maddikera', nameEn: 'Maddikera East', nameTe: 'మద్దికెర' },
    { slug: 'nandavaram', nameEn: 'Nandavaram Sri Chowdeshwari Devi', nameTe: 'నందవరం' },
    { slug: 'orvakal', nameEn: 'Orvakal Rock Garden & Airport Corridor', nameTe: 'ఓర్వకల్లు' },
    { slug: 'peapully', nameEn: 'Peapully Custard Apples', nameTe: 'ప్యాపిలి' },
    { slug: 'peddakadubur', nameEn: 'Pedda Kadubur', nameTe: 'పెద్దకడబూరు' },
    { slug: 'tuggali', nameEn: 'Tuggali Jonnagiri Gold & Diamond Fields', nameTe: 'తుగ్గలి' },
    { slug: 'veldurthi', nameEn: 'Veldurthi', nameTe: 'వెల్దుర్తి' },
    { slug: 'c-belagal', nameEn: 'C. Belagal', nameTe: 'సి. బెళగల్' },
    { slug: 'gudur-knl', nameEn: 'Gudur', nameTe: 'గూడూరు' },
  ],
  'nandyal': [
    { slug: 'nandyal-urban', nameEn: 'Nandyal Nava Nandi Kshetram', nameTe: 'నంద్యాల అర్బన్' },
    { slug: 'nandyal-rural', nameEn: 'Nandyal Rural', nameTe: 'నంద్యాల రూరల్' },
    { slug: 'allagadda', nameEn: 'Allagadda World Sculpture Center', nameTe: 'ఆళ్లగడ్డ' },
    { slug: 'banaganapalle', nameEn: 'Banaganapalle Mangoes & Nawab Palace', nameTe: 'బనగానపల్లె' },
    { slug: 'atmakur-ndl', nameEn: 'Atmakur Nallamala Gateway', nameTe: 'ఆత్మకూరు' },
    { slug: 'srisailam', nameEn: 'Srisailam Mallikarjuna Bhramaramba Kshetram', nameTe: 'శ్రీశైలం' },
    { slug: 'nandikotkur', nameEn: 'Nandikotkur', nameTe: 'నందికొట్కూరు' },
    { slug: 'koilkuntla', nameEn: 'Koilkuntla', nameTe: 'కోవెలకుంట్ల' },
    { slug: 'bethamcherla', nameEn: 'Bethamcherla Natural Flooring Slabs', nameTe: 'బెతంచెర్ల' },
    { slug: 'panyam', nameEn: 'Panyam Cement Belt', nameTe: 'పాణ్యం' },
    { slug: 'mahanandi', nameEn: 'Mahanandi Pushkarini Kshetram', nameTe: 'మహానంది' },
    { slug: 'gospadu', nameEn: 'Gospadu', nameTe: 'గోస్పాడు' },
    { slug: 'sanjamala', nameEn: 'Sanjamala', nameTe: 'సంజామల' },
    { slug: 'kolimigundla', nameEn: 'Kolimigundla Belum Caves', nameTe: 'కొలిమిగుండ్ల (బెలూం గుహలు)' },
    { slug: 'owk', nameEn: 'Owk Reservoir & Historic Palaces', nameTe: 'ఔకు' },
    { slug: 'sirvella', nameEn: 'Sirvella', nameTe: 'శిరివెళ్ల' },
    { slug: 'rudravaram', nameEn: 'Rudravaram', nameTe: 'రుద్రవరం' },
    { slug: 'chagalamarri', nameEn: 'Chagalamarri', nameTe: 'చాగలమర్రి' },
    { slug: 'uyyalawada', nameEn: 'Uyyalawada First Freedom Fighter Land', nameTe: 'ఉయ్యాలవాడ' },
    { slug: 'dornipadu', nameEn: 'Dornipadu', nameTe: 'దొర్నిపాడు' },
    { slug: 'gadivemula', nameEn: 'Gadivemula', nameTe: 'గడివేముల' },
    { slug: 'bandiatmakur', nameEn: 'Bandi Atmakur', nameTe: 'బండి ఆత్మకూరు' },
    { slug: 'pamulapadu', nameEn: 'Pamulapadu', nameTe: 'పాములపాడు' },
    { slug: 'jupadu-bungalow', nameEn: 'Jupadu Bungalow', nameTe: 'జూపాడు బంగళా' },
    { slug: 'midthur', nameEn: 'Midthur', nameTe: 'మిడ్తూరు' },
    { slug: 'pagidyala', nameEn: 'Pagidyala', nameTe: 'పగిడ్యాల' },
    { slug: 'kothapalle-ndl', nameEn: 'Kothapalle', nameTe: 'కొత్తపల్లె' },
    { slug: 'velgodu', nameEn: 'Velgodu Telugu Ganga Reservoir', nameTe: 'వెలుగోడు' },
  ],
  'anantapur': [
    { slug: 'anantapur-urban', nameEn: 'Anantapur Urban / Historic Tower', nameTe: 'అనంతపురం అర్బన్' },
    { slug: 'anantapur-rural', nameEn: 'Anantapur Rural', nameTe: 'అనంతపురం రూరల్' },
    { slug: 'guntakal', nameEn: 'Guntakal Railway Division Hub', nameTe: 'గుంతకల్లు' },
    { slug: 'tadipatri', nameEn: 'Tadipatri Bugga Ramalingeswara Temple', nameTe: 'తాడిపత్రి' },
    { slug: 'uravakonda', nameEn: 'Uravakonda Silk Weaving', nameTe: 'ఉరవకొండ' },
    { slug: 'kalyandurg', nameEn: 'Kalyandurg Pomegranate Capital', nameTe: 'కళ్యాణదుర్గం' },
    { slug: 'rayadurg', nameEn: 'Rayadurg Hilltop Fort & Garment Industry', nameTe: 'రాయదుర్గం' },
    { slug: 'pamidi', nameEn: 'Pamidi Penna River Town', nameTe: 'పామిడి' },
    { slug: 'yadiki', nameEn: 'Yadiki Underground Caves', nameTe: 'యాడికి' },
    { slug: 'peddapappur', nameEn: 'Peddapappur', nameTe: 'పెద్దపప్పూరు' },
    { slug: 'singanamala', nameEn: 'Singanamala Large Fresh Lake', nameTe: 'సింగనమల' },
    { slug: 'garladinne', nameEn: 'Garladinne', nameTe: 'గార్లదిన్నె' },
    { slug: 'kudair', nameEn: 'Kudair', nameTe: 'కూడేరు' },
    { slug: 'atmakur-atp', nameEn: 'Atmakur', nameTe: 'ఆత్మకూరు' },
    { slug: 'bk-samudram', nameEn: 'B.K. Samudram', nameTe: 'బికె సముద్రం' },
    { slug: 'vajrakarur', nameEn: 'Vajrakarur Diamond Processing Fields', nameTe: 'వజ్రకరూరు' },
    { slug: 'vidapanakal', nameEn: 'Vidapanakal', nameTe: 'విడపనకల్లు' },
    { slug: 'gooty', nameEn: 'Gooty Historic Hill Citadel', nameTe: 'గుత్తి' },
    { slug: 'peddavadugur', nameEn: 'Peddavadugur', nameTe: 'పెద్దవడుగూరు' },
    { slug: 'kanekal', nameEn: 'Kanekal', nameTe: 'కణేకల్లు' },
    { slug: 'bommanahal', nameEn: 'Bommanahal', nameTe: 'బొమ్మనహాళ్' },
    { slug: 'd-hirehal', nameEn: 'D. Hirehal Iron Belt', nameTe: 'డి. హిరేహాళ్' },
    { slug: 'gummagatta', nameEn: 'Gummagatta', nameTe: 'గుమ్మఘట్ట' },
    { slug: 'beluguppa', nameEn: 'Beluguppa', nameTe: 'బెలుగుప్ప' },
    { slug: 'brahmasamudram', nameEn: 'Brahmasamudram', nameTe: 'బ్రహ్మసముద్రం' },
    { slug: 'settur', nameEn: 'Settur', nameTe: 'శెట్టూరు' },
    { slug: 'kundurpi', nameEn: 'Kundurpi Fort', nameTe: 'కుందుర్పి' },
    { slug: 'kambadur', nameEn: 'Kambadur Ancient Mallikarjuna Temple', nameTe: 'కంబదూరు' },
    { slug: 'raptadu', nameEn: 'Raptadu', nameTe: 'రాప్తాడు' },
    { slug: 'putlur', nameEn: 'Putlur', nameTe: 'పుట్లూరు' },
    { slug: 'yellanur', nameEn: 'Yellanur', nameTe: 'యల్లనూరు' },
  ],
  'sri-sathya-sai': [
    { slug: 'puttaparthi', nameEn: 'Puttaparthi Prasanthi Nilayam Spiritual Capital', nameTe: 'పుట్టపర్తి' },
    { slug: 'dharmavaram', nameEn: 'Dharmavaram World Heritage Silk Sarees', nameTe: 'ధర్మవరం' },
    { slug: 'hindupur', nameEn: 'Hindupur Industrial & Automobile Trade', nameTe: 'హిందూపురం' },
    { slug: 'kadiri', nameEn: 'Kadiri Khadri Lakshmi Narasimha Swamy', nameTe: 'కదిరి' },
    { slug: 'penukonda', nameEn: 'Penukonda Vijayanagara Second Capital & KIA Motors', nameTe: 'పెనుకొండ' },
    { slug: 'madakasira', nameEn: 'Madakasira Hill Fort', nameTe: 'మడకశిర' },
    { slug: 'lepakshi', nameEn: 'Lepakshi Monolithic Basavanna & Hanging Pillar', nameTe: 'లేపాక్షి' },
    { slug: 'chilamathur', nameEn: 'Chilamathur Kodur Border Hub', nameTe: 'చిలమత్తూరు' },
    { slug: 'gorantla', nameEn: 'Gorantla Madhavaraya Temple', nameTe: 'గొరంట్ల' },
    { slug: 'bukkapatnam', nameEn: 'Bukkapatnam', nameTe: 'బుక్కపట్నం' },
    { slug: 'kothacheruvu', nameEn: 'Kothacheruvu', nameTe: 'కొత్తచెరువు' },
    { slug: 'bathalapalle', nameEn: 'Bathalapalle', nameTe: 'బత్తలపల్లి' },
    { slug: 'tadimarri', nameEn: 'Tadimarri', nameTe: 'తాడిమర్రి' },
    { slug: 'mudigubba', nameEn: 'Mudigubba', nameTe: 'ముదిగుబ్బ' },
    { slug: 'talupula', nameEn: 'Talupula', nameTe: 'తలుపుల' },
    { slug: 'np-kunta', nameEn: 'N.P. Kunta 1000MW Solar Park', nameTe: 'నంబులపూలకుంట' },
    { slug: 'gandlapenta', nameEn: 'Gandlapenta', nameTe: 'గాండ్లపెంట' },
    { slug: 'tanakal', nameEn: 'Tanakal', nameTe: 'తనకల్లు' },
    { slug: 'nallacheruvu', nameEn: 'Nallacheruvu', nameTe: 'నల్లచెరువు' },
    { slug: 'amadagur', nameEn: 'Amadagur', nameTe: 'ఆమడగూరు' },
    { slug: 'od-cheruvu', nameEn: 'O.D. Cheruvu', nameTe: 'ఓబులదేవరచెరువు' },
    { slug: 'nallamada', nameEn: 'Nallamada', nameTe: 'నల్లమాడ' },
    { slug: 'roddam', nameEn: 'Roddam', nameTe: 'రొద్దం' },
    { slug: 'somandepalle', nameEn: 'Somandepalle', nameTe: 'సోమందేపల్లి' },
    { slug: 'parigi-sss', nameEn: 'Parigi', nameTe: 'పరిగి' },
    { slug: 'gudibanda', nameEn: 'Gudibanda', nameTe: 'గుడిబండ' },
    { slug: 'amarapuram', nameEn: 'Amarapuram', nameTe: 'అమరాపురం' },
    { slug: 'agali', nameEn: 'Agali', nameTe: 'అగళి' },
    { slug: 'rolla', nameEn: 'Rolla', nameTe: 'రొళ్ల' },
    { slug: 'ck-palle', nameEn: 'C.K. Palle', nameTe: 'సి.కె. పల్లి' },
    { slug: 'kanaganapalle', nameEn: 'Kanaganapalle', nameTe: 'కనగానపల్లి' },
    { slug: 'ramagiri', nameEn: 'Ramagiri Wind & Gold Belt', nameTe: 'రామగిరి' },
  ],
  'kadapa-ysr': [
    { slug: 'kadapa-urban', nameEn: 'Kadapa Urban / Ameen Peer Dargah / Devuni Kadapa', nameTe: 'కడప అర్బన్' },
    { slug: 'kadapa-rural', nameEn: 'Kadapa Rural', nameTe: 'కడప రూరల్' },
    { slug: 'proddatur-gold', nameEn: 'Proddatur (Second Bombay / Gold Hub)', nameTe: 'ప్రొద్దుటూరు' },
    { slug: 'pulivendula', nameEn: 'Pulivendula Banana & Horticulture Center', nameTe: 'పులివెందుల' },
    { slug: 'jammalamadugu', nameEn: 'Jammalamadugu (Gandikota Fort & Gorge)', nameTe: 'జమ్మలమడుగు' },
    { slug: 'mydukur', nameEn: 'Mydukur Four-Roads Commercial Junction', nameTe: 'మైదుకూరు' },
    { slug: 'badvel', nameEn: 'Badvel Commercial Division', nameTe: 'బద్వేలు' },
    { slug: 'kamalapuram', nameEn: 'Kamalapuram Papaghni River', nameTe: 'కమలాపురం' },
    { slug: 'vontimitta', nameEn: 'Vontimitta Sri Kodandarama Temple', nameTe: 'ఒంటిమిట్ట' },
    { slug: 'siddhavatam', nameEn: 'Siddhavatam Penna River Fort', nameTe: 'సిద్ధవటం' },
    { slug: 'yerraguntla', nameEn: 'Yerraguntla South India Cement Capital', nameTe: 'ఎర్రగుంట్ల' },
    { slug: 'muddanur', nameEn: 'Muddanur RTPP Thermal Power Station', nameTe: 'ముద్దనూరు' },
    { slug: 'simhadripuram', nameEn: 'Simhadripuram', nameTe: 'సింహాద్రిపురం' },
    { slug: 'vempalle', nameEn: 'Vempalle (Idupulapaya Valley)', nameTe: 'వెంపల్లె' },
    { slug: 'lingala-ysr', nameEn: 'Lingala', nameTe: 'లింగాల' },
    { slug: 'thondur', nameEn: 'Thondur', nameTe: 'తొండూరు' },
    { slug: 'vemula', nameEn: 'Vemula Uranium Corporation', nameTe: 'వేముల' },
    { slug: 'chakrayapet', nameEn: 'Chakrayapet', nameTe: 'చక్రాయపేట' },
    { slug: 'kondapuram-ysr', nameEn: 'Kondapuram', nameTe: 'కొండాపురం' },
    { slug: 'mylavaram-ysr', nameEn: 'Mylavaram Reservoir Dam', nameTe: 'మైలవరం' },
    { slug: 'pendlimarri', nameEn: 'Pendlimarri', nameTe: 'పెండ్లిమర్రి' },
    { slug: 'chennur-ysr', nameEn: 'Chennur', nameTe: 'చెన్నూరు' },
    { slug: 'vallur', nameEn: 'Vallur Pushpagiri Peetham', nameTe: 'వల్లూరు (పుష్పగిరి)' },
    { slug: 'khajipet', nameEn: 'Khajipet', nameTe: 'ఖాజీపేట' },
    { slug: 'chapadu', nameEn: 'Chapadu', nameTe: 'చాపాడు' },
    { slug: 'duvvur', nameEn: 'Duvvur', nameTe: 'దువ్వూరు' },
    { slug: 'brahmamgarimattam', nameEn: 'Sri Potuluri Veerabrahmendra Swamy Mutt', nameTe: 'బ్రహ్మంగారిమఠం' },
    { slug: 'b-kodur', nameEn: 'B. Kodur', nameTe: 'బి. కోడూరు' },
    { slug: 'porumamilla', nameEn: 'Porumamilla 14th Century Historic Tank', nameTe: 'పోరుమామిళ్ల' },
    { slug: 'kalasapadu', nameEn: 'Kalasapadu', nameTe: 'కలసపాడు' },
    { slug: 'kasi-nayana', nameEn: 'Kasi Nayana Avadhuta Kshetram', nameTe: 'కాశీనాయన' },
    { slug: 'atlur', nameEn: 'Atlur', nameTe: 'అట్లూరు' },
    { slug: 'gopavaram', nameEn: 'Gopavaram Industrial Corridor', nameTe: 'గోపవరం' },
  ],
  'annamayya': [
    { slug: 'rayachoti', nameEn: 'Rayachoti Headquarters / Veerabhadra Swamy', nameTe: 'రాయచోటి' },
    { slug: 'madanapalle', nameEn: 'Madanapalle Silk City & Asia Largest Tomato Market', nameTe: 'మదనపల్లె' },
    { slug: 'rajampet', nameEn: 'Rajampet Education Hub', nameTe: 'రాజంపేట' },
    { slug: 'railway-koduru', nameEn: 'Railway Koduru Mango & Banana Junction', nameTe: 'రైల్వే కోడూరు' },
    { slug: 'thamballapalle', nameEn: 'Thamballapalle', nameTe: 'తంబళ్లపల్లె' },
    { slug: 'pileru', nameEn: 'Pileru Commercial Cross Roads', nameTe: 'పీలేరు' },
    { slug: 'valmikipuram', nameEn: 'Valmikipuram (Vayalpadu)', nameTe: 'వాల్మీకిపురం' },
    { slug: 'b-kothakota', nameEn: 'B. Kothakota Horsley Hills Gateway', nameTe: 'బి. కొత్తకోట (హార్సిలీ హిల్స్)' },
    { slug: 'kurabalakota', nameEn: 'Kurabalakota', nameTe: 'కురబలకోట' },
    { slug: 'nimmanapalle', nameEn: 'Nimmanapalle Krishnamurti Foundation', nameTe: 'నిమ్మనపల్లె' },
    { slug: 'ramasamu-dram', nameEn: 'Ramasamudram', nameTe: 'రామసముద్రం' },
    { slug: 'kalikiri', nameEn: 'Kalikiri Sainik School', nameTe: 'కలికిరి' },
    { slug: 'gurramkonda', nameEn: 'Gurramkonda Heritage Citadel', nameTe: 'గుర్రంకొండ' },
    { slug: 'kalakada', nameEn: 'Kalakada', nameTe: 'కలకడ' },
    { slug: 'kv-palle', nameEn: 'K.V. Palle', nameTe: 'కె.వి. పల్లె' },
    { slug: 'peddamandyam', nameEn: 'Peddamandyam', nameTe: 'పెద్దమండ్యం' },
    { slug: 'mulakalacheruvu', nameEn: 'Mulakalacheruvu', nameTe: 'ములకలచెరువు' },
    { slug: 'galiveedu', nameEn: 'Galiveedu Solar Power Fields', nameTe: 'గాలివీడు' },
    { slug: 'lakkireddypalle', nameEn: 'Lakkireddypalle', nameTe: 'లక్కిరెడ్డిపల్లె' },
    { slug: 'ramapuram', nameEn: 'Ramapuram', nameTe: 'రామాపురం' },
    { slug: 'chinnamandem', nameEn: 'Chinnamandem', nameTe: 'చిన్నమండెం' },
    { slug: 'sambepalle', nameEn: 'Sambepalle', nameTe: 'సంబేపల్లి' },
    { slug: 'veeraballi', nameEn: 'Veeraballi', nameTe: 'వీరబల్లి' },
    { slug: 't-sundupalle', nameEn: 'T. Sundupalle', nameTe: 'టి. సుండుపల్లె' },
    { slug: 'pullampeta', nameEn: 'Pullampeta', nameTe: 'పుల్లంపేట' },
    { slug: 'obulavaripalle', nameEn: 'Obulavaripalle World Mangampeta Barites Mine', nameTe: 'ఓబులవారిపల్లె' },
    { slug: 'penagalur', nameEn: 'Penagalur', nameTe: 'పెనగలూరు' },
    { slug: 'chitvel', nameEn: 'Chitvel', nameTe: 'చిట్వేలు' },
    { slug: 'nandalur', nameEn: 'Nandalur Soumyanatha Swamy Historic Temple', nameTe: 'నందలూరు' },
    { slug: 'tallapaka', nameEn: 'Tallapaka Sri Pada Kavitha Pitamaha Janmasthalam', nameTe: 'తాళ్లపాక' },
  ],
  'tirupati': [
    { slug: 'tirupati-urban', nameEn: 'Tirupati Urban (Alipiri / Balaji Colony)', nameTe: 'తిరుపతి అర్బన్' },
    { slug: 'tirupati-rural', nameEn: 'Tirupati Rural', nameTe: 'తిరుపతి రూరల్' },
    { slug: 'tirumala', nameEn: 'Tirumala Lord Venkateswara Abode', nameTe: 'తిరుమల' },
    { slug: 'srikalahasti', nameEn: 'Srikalahasti Vayu Linga Kshetram', nameTe: 'శ్రీకాళహస్తి' },
    { slug: 'gudur', nameEn: 'Gudur Lemon Market & Railway Junction', nameTe: 'గూడూరు' },
    { slug: 'sullurpeta', nameEn: 'Sullurpeta (Satish Dhawan Space Centre ISRO SHAR)', nameTe: 'సూళ్లూరుపేట' },
    { slug: 'venkatagiri', nameEn: 'Venkatagiri Heritage Zari Sarees & Palace', nameTe: 'వెంకటగిరి' },
    { slug: 'chandragiri', nameEn: 'Chandragiri Historic Vijayanagara Fort', nameTe: 'చంద్రగిరి' },
    { slug: 'renigunta', nameEn: 'Renigunta Airport & Railway Terminus', nameTe: 'రేణిగుంట' },
    { slug: 'yerpedu', nameEn: 'Yerpedu (IIT & IISER Campus)', nameTe: 'ఏర్పేడు' },
    { slug: 'thottambedu', nameEn: 'Thottambedu', nameTe: 'తొట్టంబేడు' },
    { slug: 'pellakur', nameEn: 'Pellakur', nameTe: 'పెళ్లకూరు' },
    { slug: 'naidupeta', nameEn: 'Naidupeta Special Economic Zone', nameTe: 'నాయుడుపేట' },
    { slug: 'ozili', nameEn: 'Ozili', nameTe: 'ఓజిలి' },
    { slug: 'chillakur', nameEn: 'Chillakur', nameTe: 'చిల్లకూరు' },
    { slug: 'kota', nameEn: 'Kota', nameTe: 'కోట' },
    { slug: 'vakadu', nameEn: 'Vakadu', nameTe: 'వాకాడు' },
    { slug: 'chittamur', nameEn: 'Chittamur', nameTe: 'చిట్టమూరు' },
    { slug: 'doravarisatram', nameEn: 'Doravarisatram (Pulicat Bird Sanctuary)', nameTe: 'దొరవారిసత్రం' },
    { slug: 'tada', nameEn: 'Tada Sri City Integrated Industrial Township', nameTe: 'తడ (శ్రీసిటీ)' },
    { slug: 'varadaiahpalem', nameEn: 'Varadaiahpalem Spiritual Valley', nameTe: 'వరదయ్యపాలెం' },
    { slug: 'satyavedu', nameEn: 'Satyavedu Border Industrial Belt', nameTe: 'సత్యవేడు' },
    { slug: 'nagalapuram', nameEn: 'Nagalapuram Vedanarayana Swamy Temple', nameTe: 'నాగలాపురం' },
    { slug: 'pichatur', nameEn: 'Pichatur Araniar Reservoir', nameTe: 'పిచ్చాటూరు' },
    { slug: 'narayanavanam', nameEn: 'Narayanavanam Sri Kalyana Venkateswara', nameTe: 'నారాయణవనం' },
    { slug: 'puttur', nameEn: 'Puttur Joint Kattu & Commercial Town', nameTe: 'పుత్తూరు' },
    { slug: 'vadamalapeta', nameEn: 'Vadamalapeta Appalayagunta Temple', nameTe: 'వడమాలపేట' },
    { slug: 'ramachandrapuram-tpt', nameEn: 'Ramachandrapuram', nameTe: 'రామచంద్రాపురం' },
    { slug: 'chinnagottigallu', nameEn: 'Chinnagottigallu', nameTe: 'చిన్నగొట్టిగల్లు' },
    { slug: 'yerravaripalem', nameEn: 'Yerravaripalem Talakona Waterfalls', nameTe: 'ఎర్రవారిపాలెం' },
    { slug: 'pakala', nameEn: 'Pakala Lake & Railway Junction', nameTe: 'పాకాల' },
  ],
  'chittoor': [
    { slug: 'chittoor-urban', nameEn: 'Chittoor Urban / Mango Pulp Capital', nameTe: 'చిత్తూరు అర్బన్' },
    { slug: 'chittoor-rural', nameEn: 'Chittoor Rural', nameTe: 'చిత్తూరు రూరల్' },
    { slug: 'nagari', nameEn: 'Nagari Weaving Town & Border Hub', nameTe: 'నగరి' },
    { slug: 'palamaner', nameEn: 'Palamaner Dairy Cattle Research & NH75', nameTe: 'పలమనేరు' },
    { slug: 'kuppam', nameEn: 'Kuppam Tri-State Tri-Junction (AP-TN-KA)', nameTe: 'కుప్పం' },
    { slug: 'kanipakam', nameEn: 'Kanipakam Sri Varasiddhi Vinayaka Kshetram', nameTe: 'కాణిపాకం' },
    { slug: 'bangurupalem', nameEn: 'Bangurupalem', nameTe: 'బంగారుపాలెం' },
    { slug: 'gudipala', nameEn: 'Gudipala', nameTe: 'గుడిపాల' },
    { slug: 'gd-nellore', nameEn: 'G.D. Nellore', nameTe: 'గంగాధర నెల్లూరు' },
    { slug: 'penumuru', nameEn: 'Penumuru', nameTe: 'పెనుమూరు' },
    { slug: 'puthalapattu', nameEn: 'Puthalapattu', nameTe: 'పూతలపట్టు' },
    { slug: 'irala', nameEn: 'Irala', nameTe: 'ఐరాల' },
    { slug: 'thavanampalle', nameEn: 'Thavanampalle Kanipakam Gateway', nameTe: 'తవణంపల్లి' },
    { slug: 'sr-puram', nameEn: 'S.R. Puram', nameTe: 'ఎస్.ఆర్. పురం' },
    { slug: 'vedurukuppam', nameEn: 'Vedurukuppam', nameTe: 'వెదురుకుప్పం' },
    { slug: 'karvetinagaram', nameEn: 'Karvetinagaram Heritage Rajahs Palace', nameTe: 'కార్వేటినగరం' },
    { slug: 'nindra', nameEn: 'Nindra', nameTe: 'నిండ్ర' },
    { slug: 'vijayapuram', nameEn: 'Vijayapuram', nameTe: 'విజయపురం' },
    { slug: 'bireddypalli', nameEn: 'Bireddypalli', nameTe: 'బైరెడ్డిపల్లి' },
    { slug: 'v-kota', nameEn: 'Venkatagirikota (V. Kota)', nameTe: 'వి. కోట' },
    { slug: 'peddapanjani', nameEn: 'Peddapanjani', nameTe: 'పెద్దపంజాణి' },
    { slug: 'gangavaram-ctr', nameEn: 'Gangavaram', nameTe: 'గంగవరం' },
    { slug: 'shanthipuram', nameEn: 'Santhipuram', nameTe: 'శాంతిపురం' },
    { slug: 'gudupalle', nameEn: 'Gudupalle Dravidian University', nameTe: 'గుడుపల్లె' },
    { slug: 'ramakuppam', nameEn: 'Ramakuppam', nameTe: 'రామకుప్పం' },
    { slug: 'chowdepalle', nameEn: 'Chowdepalle Boyakonda Gangamma Temple', nameTe: 'చౌడేపల్లి' },
    { slug: 'somala', nameEn: 'Somala', nameTe: 'సోమల' },
    { slug: 'sodam', nameEn: 'Sodam', nameTe: 'సోదం' },
    { slug: 'punganur', nameEn: 'Punganur World Miniature Dwarf Cattle Land', nameTe: 'పుంగనూరు' },
    { slug: 'yadamarri', nameEn: 'Yadamarri', nameTe: 'యాదమరి' },
    { slug: 'rompicherla-ctr', nameEn: 'Rompicherla', nameTe: 'రొంపిచర్ల' },
  ],
};
